### ISSUE TITLE
不错的库，发现几点问题和建议

### ISSUE THREAD

**Issue by jyh149129** [yangchaojiang/yjPlay#1]
1、现在的全屏后视频显示比例不对（看下图里的字幕显示可以看出来，横屏的时候正常）
![screenshot_2017-07-10-23-54-41-859_chuangyuan xiangjiang yjplay](https://user-images.githubusercontent.com/7726240/28027549-07a1406a-65cc-11e7-9e7f-ccd4826d00a1.png)
2、现在的全屏方式在android 6.0 上，标题栏 并不会被隐藏，会一直显示：
![screenshot_2017-07-11-00-07-21-235_chuangyuan xiangjiang yjplay](https://user-images.githubusercontent.com/7726240/28027850-2c4cda9a-65cd-11e7-8e94-ea51e9f87343.png)
3、对于hls流，进度条似乎显示的是每个分片的播放进度,而不是视频进度
4、建议加入网络变化通知,用流量的时候能有个提醒

谢谢

**Comment by yangchaojiang** [comment]
谢谢，你的建议，
2，因为你有你toobar ，toobar 没有处理，下个版本处理，
3.his流，基本所有播放器，都是相似分支的播放进度，无法播放视频进度
4，我正在加，最近我也做播放app，需要用播放器

**Comment by yangjiangs** [comment]
你的1.2.4的老问题，已在版本1.3.0 修复，谢谢你的支持
