### ISSUE TITLE
全屏回退到非全屏出现问题

### ISSUE THREAD

**Issue by caprice** [yangchaojiang/yjPlay#103]
问题现象：先小屏播放，然后全拼播放，这个时候按home键，再打开app,然后从全屏退到小屏，出现右侧留一片空白，如下图现象：
![image](https://user-images.githubusercontent.com/2981114/38797834-5c2dd5ce-4192-11e8-842e-f3269eabc313.png)

**Comment by yangchaojiang** [comment]
2.1.52 没有问题哦，请问你是用版本？ 或者代码是否有问题

**Comment by caprice** [comment]
这个问题应该还是存在的。我的版本是2.1.51，新版本你没有修改过相关代码的。该问题产生的原因应该是底部虚拟导航键的。全屏后你会设置导航键隐藏，但当按home键后然后回来，系统会让虚拟导航键出现：
![image](https://user-images.githubusercontent.com/2981114/38816354-7d5d408c-41c8-11e8-9084-59c440443f85.png)
这个时候去退出全屏就会出现我所说的问题了。
而右侧空白那个宽度就是导航键的高度，暂时还没想到解决的办法，我看腾讯视频也有类似的问题，只不过退出全屏这个是好的

**Comment by yangchaojiang** [comment]
好的，我看看

**Comment by yangchaojiang** [comment]
2.1.58 版本，已修改。
 不好意思，上传带仓库老是出问题。白天没有时间。

**Comment by yangchaojiang** [comment]
@caprice

**Comment by caprice** [comment]
已修复，多谢!
