### ISSUE TITLE
提个建议,能否播放在底部加一个实时进度

### ISSUE THREAD

**Issue by jaysowen** [yangchaojiang/yjPlay#104]
如题,就想节操播放器一样,这样体验比较好,用户有一个观看预期,谢谢

**Comment by yangchaojiang** [comment]
截个图看一下

**Comment by jaysowen** [comment]
![wechatimg10](https://user-images.githubusercontent.com/508850/38985132-17234228-43fb-11e8-8574-5f5dc8501e0a.jpeg)
类似开眼的这种mini progressbar.

**Comment by yangchaojiang** [comment]
后期版本，开放一个接口和一个拓展布局。自己根据需求去实现。

**Comment by yangchaojiang** [comment]
每个人都需求不一样的，我都不能实现本库里。

**Comment by jaysowen** [comment]
好的,多谢

**Comment by yangchaojiang** [comment]
//开启实时进度
        videoPlayerView.setOpenProgress2(true);  版本：2.1.70
