### ISSUE TITLE
请问支持m3u8的缓存么？MP4直链缓存是可以，但这个格式的不知道是否支持

### ISSUE THREAD

**Issue by zhiyou007** [yangchaojiang/yjPlay#107]
请问支持m3u8的缓存么？MP4直链缓存是可以，但这个格式的不知道是否支持

**Comment by yangchaojiang** [comment]
支持缓存，

**Comment by zhiyou007** [comment]
好像不行，m3u8格式的播放列表，好像不支持缓存，直接的视频格式倒是支持，缓存DEMO里，我试了，报错

**Comment by yangchaojiang** [comment]
HlsDownloader,DashDownloader,SsDownloader,SegmentDownloader。

**Comment by zhiyou007** [comment]
@yangchaojiang 这几个类如何使用啊，在哪有介绍

**Comment by zhiyou007** [comment]
我试了下：  https://www3.laqddc.com/hls/2018/04/27/8N8pSAQX/playlist.m3u8，用自定义缓存类HlsDownloader，发现下载下来的m3u8的播放文件，而不是去下载m3u8里的资源文件

**Comment by zhiyou007** [comment]
exoPlayerManager.setLoadModel(LoadModelType.PERCENR);
在DEMO第一个选项里载入上面播放地址，然后换成百分比现实，没有现实百分比

**Comment by yangchaojiang** [comment]
您好。版本2.1.80 已经支持。

**Comment by yangchaojiang** [comment]
您好。版本2.1.80 已经支持。下载流媒体文件。使用参看demo
