### ISSUE TITLE
【BUG&优化】重力翻转不行

### ISSUE THREAD

**Issue by zhiyou007** [yangchaojiang/yjPlay#109]
问题现象：点全屏按钮以后就不能自动翻转
错误日志：无

**Comment by yangchaojiang** [comment]
你没有重写方法 
 @Override
            public void onConfigurationChanged(Configuration newConfig) {
                exoPlayerManager.onConfigurationChanged(newConfig);//横竖屏切换
                super.onConfigurationChanged(newConfig);
            }****
