### ISSUE TITLE
楼主，如何禁掉声音

### ISSUE THREAD

**Issue by hqAnd** [yangchaojiang/yjPlay#11]
现在需要个需求，播放视频不播放声音，包括使用增加音量键，请问可以做到吗。谢谢楼主

**Comment by yangchaojiang** [comment]
你可以在activity屏蔽 音量键，你可以
 exoPlayerManager.getPlayer().getVolume();
 exoPlayerManager.getPlayer().setVolume(0);
播放器的音量进行控制

**Comment by yangchaojiang** [comment]
在activity  重写
 @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        // TODO Auto-generated method stub
         if (keyCode == KeyEvent.KEYCODE_VOLUME_UP) {
            return false;
        } else return super.onKeyUp(keyCode, event);
    }

**Comment by hqAnd** [comment]
好的。我去试试

**Comment by yangchaojiang** [comment]
可以了吗

**Comment by hqAnd** [comment]
exoPlayerManager.getPlayer().setVolume(0);这个方法不好使。我吧项目jar下下来了。吧音量滑动事件禁掉了。之后audioManager.setStreamVolume(AudioManager.STREAM_MUSIC, 0, 0);用这个方法设置的音量，禁掉手机的音量键。达成了我的需求

**Comment by hqAnd** [comment]
我这面需要一个页面同时播放两个视频。也就是需要两个播放控件，找了好久找到您的播放器，两个播放器不冲突，可以同时播放。点赞。谢谢楼主了

**Comment by yangchaojiang** [comment]
exoPlayerManager.getPlayer().setVolume(0) 设置音量的。不能音量滑动事件禁掉，苦笑，也可以的，
每个人需求不是一样的

**Comment by yangchaojiang** [comment]
好用的话 star 一下 谢谢了

**Comment by hqAnd** [comment]
楼主，还有个问题咨询，我需要在控件上加个按钮，如何做到点击我的按钮开始播放视频。谢谢。star了

**Comment by yangchaojiang** [comment]
这个ManualPlayer 手动播放 ，目前支持 控制布局自定义样式，目前不开放用户控制事件，但是有通知
  exoPlayerManager.setVideoInfoListener(new VideoInfoListener() }  进行你业务处理。demo  有自定义布局实例的

**Comment by hqAnd** [comment]
楼主，方便加个qq么 。这样探讨有些麻烦。504821602.麻烦了

**Comment by yangchaojiang** [comment]
1007181167
