### ISSUE TITLE
类型转化错误

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#110]
java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to chuangyuan.ycj.videolibrary.video.ExoDataBean
        at chuangyuan.ycj.videolibrary.widget.VideoPlayerView.onRestoreInstanceState(VideoPlayerView.java:137)
        at android.view.View.dispatchRestoreInstanceState(View.java:15866)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3394)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3400)
        at android.view.View.restoreHierarchyState(View.java:15844)
        at

**Comment by h3clikejava** [comment]
控件放在ViewPager里，左右滑动，就报这个崩溃了

**Comment by h3clikejava** [comment]
2.1.51 版本是好的，2.1.58就有问题了

**Comment by yangchaojiang** [comment]
请问你自定义了吗？

**Comment by h3clikejava** [comment]
- -" 这显然不是我自定义的类啊。而且2.1.51是好的

**Comment by h3clikejava** [comment]
我测过了，如果把ViewPager中的Fragment布局里面直接使用VideoPlayerView，也会崩溃，一样的错误。
你可以试一下，就把view_list_2.xml中的RecyclerView替换为VideoPlayerView。

附上源码:
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical"
    >

    <chuangyuan.ycj.videolibrary.widget.VideoPlayerView
        android:id="@+id/photo_local_grid_fullscreen_videoview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/transparent"
        app:player_layout_id="@layout/simple_exo_view"
        app:controller_layout_id="@layout/simple_exo_playback_control_view"
        app:player_error_layout_id="@layout/custom_play_error"
        app:player_back_image="@drawable/transparent"
        app:resize_mode="fit"
        app:surface_type="surface_view" />

</LinearLayout>
`

我看了类型转换附近最近是没有改代码的。2.1.51~2.1.52之间改了什么没有TAG我找不到，但是应该是这里面改了什么才导致出来的新问题

**Comment by yangchaojiang** [comment]
没有开启列表，模式哦

**Comment by yangchaojiang** [comment]
app:player_list

**Comment by h3clikejava** [comment]
直接拿Demo试就好了，就替换一下RecyclerView为VideoPlayerView，你会遇到跟我一样的问题。[Demo里的ViewPagerFragment部分]

**Comment by h3clikejava** [comment]
左右滑动，往回滑动，就崩了。

**Comment by yangchaojiang** [comment]
你试一下2.1.73

**Comment by h3clikejava** [comment]
可以了，你是找到原因了吗？

**Comment by h3clikejava** [comment]
好的，可以了。我看了下，你就是判断了一下。也行吧，反正可以了，谢谢 👍

**Comment by yangchaojiang** [comment]
是的。忘判断了:joy::joy::joy::joy:
