### ISSUE TITLE
手势布局不显示

### ISSUE THREAD

**Issue by jaysowen** [yangchaojiang/yjPlay#116]
问题现象：demo自定义媒体里面滑动可以调节音量,进度和亮度但是布局文件不会显示
另外请教一下在已经设置手势布局的情况下,为什么同样不显示布局,但是手势有效果.我用的是ManualPlayer,谢谢

**Comment by yangchaojiang** [comment]
是自定义布局的没有实现是吧。不好意思，最近太忙了。没事回复。我看看代码

**Comment by jaysowen** [comment]
好像是我这边的问题,自己拷贝代码之后然后属性没有生效,暂时关闭.打扰了~
