### ISSUE TITLE
无法播放本地视频，另Activity全屏后点后退，会出现系统状态条

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#12]
无法播放本地视频，提示错误
java.net.MalformedURLException: Protocol not found: /storage/emulated/0/Movies/AVRecSample/2017-09-25-14-12-12.mp4

调用方法为
exoPlayerManager.setPlayUri("/storage/emulated/0/Movies/AVRecSample/2017-09-25-14-12-12.mp4");

改为
exoPlayerManager.setPlayUri("file:///storage/emulated/0/Movies/AVRecSample/2017-09-25-14-12-12.mp4");
仍然提示
Unexpected ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection

貌似是不认识本地路径。

我的
网络正常
这个视频文件是存在的
应用也有运行时读写权限
网络视频地址是可以正常播放的

![image](https://user-images.githubusercontent.com/4688773/30796267-f152578e-a196-11e7-899c-68ade7df96c5.png)

另：
设置默认全屏之后，点击放大，再点击后退键返回初始状态的时候全屏失效了。
截图另补

**Comment by yangchaojiang** [comment]
6.0 请上加权限哦

**Comment by yangchaojiang** [comment]
点错了

**Comment by yangchaojiang** [comment]
重新开一下

**Comment by h3clikejava** [comment]
试了很多遍都不行，确定有权限的

**Comment by yangchaojiang** [comment]
您好，谢谢建议，由于半个版本我魄剥离数据源，实现自定义。默认数据源http方式处理，所以不支持，本地路径，你自定义数据源据行了
![image](https://user-images.githubusercontent.com/13806413/30797793-d82f22aa-a209-11e7-8139-2cc6441b2aea.png)
![image](https://user-images.githubusercontent.com/13806413/30797805-e12c2718-a209-11e7-89f3-80a11f71dccf.png)

**Comment by yangchaojiang** [comment]
可以了吧，觉得好用，star 一下

**Comment by yangchaojiang** [comment]
对了 你所说 返回事件，需要重写activity的 onBackPressed(),播放器对back监听
 
![image](https://user-images.githubusercontent.com/13806413/30798361-f2fc6c80-a20b-11e7-902e-4e3bd9b2f3ff.png)

**Comment by h3clikejava** [comment]
确实可以播放本地视频了，感谢

另全屏的问题，我设置了onBackPressed的监听，没用
截图如下
![image](https://user-images.githubusercontent.com/4688773/30798530-9cf59512-a19f-11e7-97d1-3b486b30d045.png)
全屏Activity正常，点击右下角全屏按钮会横屏

![image](https://user-images.githubusercontent.com/4688773/30798547-a9d08828-a19f-11e7-97c7-b01a78adc600.png)
横屏播放，一切正常，准备点击back键

![image](https://user-images.githubusercontent.com/4688773/30798572-c06e06f0-a19f-11e7-84a6-27e146bdf313.png)
点击back键之后，顶部状态条跑出来了

我这边看到横竖屏播放的时候没有任何状态的回掉，因此我也没法处理这个情况。

**Comment by yangchaojiang** [comment]
亲 有这个需求比较特殊哦。 常规竖屏正常播放 i额可以在建
![image](https://user-images.githubusercontent.com/13806413/30800014-3e2e2036-a211-11e7-882f-ca632c1f0f5e.png)

代码：

**Comment by yangchaojiang** [comment]
if (!VideoPlayUtils.isLand(this)){ //隐藏状态栏的
            VideoPlayUtils.hideActionBar(this);
       }

**Comment by h3clikejava** [comment]
全屏应该是很正常的需求吧，状态条太丑了
可以可以，都可以了，感谢感谢
给你点赞

**Comment by yangchaojiang** [comment]
苦笑，我们全屏都是横屏，竖屏正常。状态条分手机小米和华为，就不难看。

**Comment by yangchaojiang** [comment]
谢谢支持了
