### ISSUE TITLE
请问如何加入FFmpeg支持呢？

### ISSUE THREAD

**Issue by magicLanjie** [yangchaojiang/yjPlay#125]
问题现象：rmvb  avi 格式加载异常
错误日志：xxxxxx

**Comment by yangchaojiang** [comment]
参考google  [exoplayer](https://github.com/google/ExoPlayer) 引用所需要的FFmpeg库的拓展，保持google拓展功能

**Comment by yangchaojiang** [comment]
目前eoxplayer 是不支持的rmvb avi    exoPlayer 所提供FFmpeg 只是对音频的解码
需要自己写解码的代码
