### ISSUE TITLE
com.google.android.exoplayer2.ParserException: Lacing only supported in Simp

### ISSUE THREAD

**Issue by magicLanjie** [yangchaojiang/yjPlay#127]
问题现象：打开一个视频流出现这种错误
错误日志：com.google.android.exoplayer2.ParserException: Lacing only supported in Simp

**Comment by magicLanjie** [comment]
恩恩 是的。

**Comment by yangchaojiang** [comment]
的不好意思，有点忙， 赶项目， 没有及时。

**Comment by yangchaojiang** [comment]
错误是指需要Simp环境下 支持的， 方便你的视频链接的提供一下吗？

**Comment by magicLanjie** [comment]
不好意思，我也才看到，这个视频链接不好给，是下载到了本地来播放的
