### ISSUE TITLE
请问播放本地缓存加密视频怎么播放？

### ISSUE THREAD

**Issue by zhoushidevelop** [yangchaojiang/yjPlay#128]
问题现象：xxxxx
错误日志：xxxxxx

**Comment by yangchaojiang** [comment]
缓存 还是你的用原来网络url的的地址？内部自动判断是否有缓存

**Comment by zhoushidevelop** [comment]
![image](https://user-images.githubusercontent.com/21030327/41885287-eac33eae-7929-11e8-9490-37ec687a1cad.png)
这个视频我已经缓存完成了，系统判断HashaMap中也有缓存了，然后我要在断网的情况下播放这个缓存视频怎么处理，我传的还是原来网络url的地址，但是提示却还是网络加载视频失败。怎么搞。 求解：
