### ISSUE TITLE
作为组件加入布局，点击全屏第一次是界面横竖切换

### ISSUE THREAD

**Issue by I18N486** [yangchaojiang/yjPlay#130]
问题现象：以组件的形式作为界面的一部分时，播放视频点击全屏按钮，第一次是界面横竖切换，第二次才是全屏。
错误日志：null

界面布局：
       <LinearLayout
           android:layout_width="0dp"
           android:layout_weight="3"
           android:layout_height="match_parent"
           android:orientation="vertical">
           <chuangyuan.ycj.videolibrary.widget.VideoPlayerView
               android:id="@+id/videoplayer"
               android:layout_width="match_parent"
               android:layout_height="560dp" />
           <android.support.v7.widget.RecyclerView
               android:id="@+id/lecture_review_picture"
               android:layout_width="match_parent"
               android:layout_height="match_parent" />
       </LinearLayout>

界面属性：
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="landscape"

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/42145041-55e77aee-7df1-11e8-9122-e023b1d20bbd.png)
  你的页面默认是横屏呀， 横屏切换肯定是竖屏哦
