### ISSUE TITLE
关于支持网络类型 提示是否播放(可自定义屏蔽)的疑问

### ISSUE THREAD

**Issue by ouyangmingzhuanyong** [yangchaojiang/yjPlay#131]
对于视频功能介绍的第11条 支持网络类型 提示是否播放(可自定义屏蔽)。请问exoPlayerManager提供什么具体方法实现屏蔽当前网络为移动网络的弹窗？demo看了好像没有找到

**Comment by yangchaojiang** [comment]
VideoPlayerManager.getInstance().setClick(true) 就不提示了
