### ISSUE TITLE
能否增加自定义旋转角度 因为手机拍摄的视频 没法全屏(填满整个窗口)

### ISSUE THREAD

**Issue by oooo7777777** [yangchaojiang/yjPlay#135]
能否增加自定义旋转角度?
 因为手机拍摄的视频 没法全屏(填满整个窗口)

**Comment by yangchaojiang** [comment]
????? 现在四种渲染视频大小的模式

**Comment by magicLanjie** [comment]
如何自定义旋转角度呢？

**Comment by yangchaojiang** [comment]
用播放的控件    
  getPlayerView().getVideoSurfaceView().setVideoRotation();

**Comment by magicLanjie** [comment]
如果说手机拍摄的时候，全屏的效果不好，旋转的时候直接就全屏了

**Comment by yangchaojiang** [comment]
| reference | 1.fit          正常模式
-- | -- | --
  | reference | 2.fixed_16_9  保持的是视频的比例16:9
  | reference | 3.fixed_4_3   保持的是视频比例4:3
  | reference | 4.fill           全屏模式，拉伸视频宽高
  | reference | 4.match          剧矩阵模式模
模式
你出截图，看看你要什么效果。

**Comment by magicLanjie** [comment]
比如说 我列表上面有一个视频，是手机拍摄的，竖排，然后点击全屏的时候，手机就变成横屏的了，视频无法铺满

![111](https://user-images.githubusercontent.com/31203442/44328118-4e8fe100-a493-11e8-905e-81b55886d6ba.png)
![2222](https://user-images.githubusercontent.com/31203442/44328120-4f287780-a493-11e8-855a-2e40a5d92f43.png)

**Comment by magicLanjie** [comment]
就是随便找一个手机是竖屏录制的就好了，比如说下载一个抖音视频，然后都会出现那样的情况！视频是竖屏的情况下，全屏的时候就不应该旋转屏幕，在全屏的时候哪里需要根据视频的高度，宽度，来进行计算！判断是否需要旋转！

**Comment by yangchaojiang** [comment]
计算都是正常视频相对自己，没有偏移，你现在横屏 要竖着看视频

**Comment by magicLanjie** [comment]
(⊙o⊙)…。视频是竖屏的时候，全屏的时候应该也是竖屏，这样才好吧，应该一楼也是这样的问题

**Comment by yangchaojiang** [comment]
视频内容文件属性决定，视频内容旋转角度，视频内容证实自己的。
 不是分辨率决定视频方向，分辨率只是控制大小

**Comment by yangchaojiang** [comment]
getPlayerView().getVideoSurfaceView().setVideoRotation(270);方法可以用的

**Comment by yangchaojiang** [comment]
你在列表上，我增加回调横竖切换

**Comment by magicLanjie** [comment]
感谢

**Comment by yangchaojiang** [comment]
我不是的通过旋转判断的 ，是根据当前手机属于横屏状态和竖屏状态。手机的旋转方向有一个特别类来实现的，我没有用

**Comment by magicLanjie** [comment]
我现在改好了，根据视频的高度，宽度，来判断全屏的时候是否需要变更手机横竖屏的状态了

**Comment by yangchaojiang** [comment]
嗯嗯，威因为你业务需求，需要该改源码事正常。

**Comment by yangchaojiang** [comment]
吧你代码发我，然后写一个方法，是否开启

**Comment by yangchaojiang** [comment]
我看了一下代码，强制切换书竖屏状态了:joy::joy::joy::joy:

**Comment by tjm800** [comment]
请问还需要怎么用吗？我的也是全屏时的竖屏视频（视频是竖屏的）并没有全屏

**Comment by magicLanjie** [comment]
需要修改作者的源码了

**Comment by yangchaojiang** [comment]
哈哈哈。@magicLanjie

**Comment by abaiweb** [comment]
>  	reference	1.fit 正常模式
>  	reference	2.fixed_16_9 保持的是视频的比例16:9
>  	reference	3.fixed_4_3 保持的是视频比例4:3
>  	reference	4.fill 全屏模式，拉伸视频宽高
>  	reference	4.match 剧矩阵模式模
> 模式		
> 你出截图，看看你要什么效果。

这个模式可以在代码中设置嘛？我没有看到呢

**Comment by yangchaojiang** [comment]
@abaiweb xml 布局中
