### ISSUE TITLE
请问为什么我一转屏,就提示"播放异常,视频地址异常,或者网络不可用呢",转屏代码,生命周期代码,main文件都做了设置了呢

### ISSUE THREAD

**Issue by WhitePhoenixv5870** [yangchaojiang/yjPlay#136]
问题现象：xxxxx
错误日志：xxxxxx

**Comment by WhitePhoenixv5870** [comment]
我在onPlayerError 里面直接调用startPlayer方法就没有报错了,不过我有一个新问题就是自定义控制布局之后,怎么使用我新加入的控件呢

**Comment by yangchaojiang** [comment]
请参考demo！自定义布局实例

**Comment by WhitePhoenixv5870** [comment]
原来直接用久可以了,我傻了...

**Comment by WhitePhoenixv5870** [comment]
我把整个demo通过git下下来了,但是运行不起来,只能找到一点写一点

**Comment by yangchaojiang** [comment]
编辑器是目前是3.1的编译！
如果是3.0以下的可能无法编译

**Comment by WhitePhoenixv5870** [comment]
我as用的是3.0.1的,报的错误是Video里面的一些drawable文件找不到

**Comment by WhitePhoenixv5870** [comment]
我as用的是3.0.1的,报的错误是VideoUI里面的一些drawable文件找不到

**Comment by WhitePhoenixv5870** [comment]
应该就是版本的问题吧

**Comment by yangchaojiang** [comment]
不好意思哈，上传github过滤了， 你在pull 就行了
