### ISSUE TITLE
列表播放本地视频出现进度缓存错乱的情况

### ISSUE THREAD

**Issue by chezi008** [yangchaojiang/yjPlay#139]
问题现象：列表播放本地视频出现进度缓存错乱的情况
错误日志：在列表中当一段视频播放完之后继续播放此次视频时，会出现视频从第6秒或者其他时间，而不是初试时间开始播放。
解决方案：可以在onPlayEnd()回调当中初始化当前位置。不知道作者有米有更好的解决方案

`addVideoInfoListener(object :VideoInfoListener{
                        override fun isPlaying(playWhenReady: Boolean) {
                        }

                        override fun onPlayerError(e: ExoPlaybackException?) {
                        }

                        override fun onPlayStart(currPosition: Long) {
                        }

                        override fun onLoadingChanged() {
                        }

                        override fun onPlayEnd() {
                            setPosition(0)
                        }

                    })`

**Comment by yangchaojiang** [comment]
该视频没有正常完毕，再次都会之前在听暂停继续播放的
![image](https://user-images.githubusercontent.com/13806413/42791801-fb5dd6ee-89a4-11e8-95f9-fb1db1a5f82f.png)
这个回调你加上判断的。列表是有会复用的。
