### ISSUE TITLE
软键盘弹出时会导致播放界面闪屏

### ISSUE THREAD

**Issue by I18N486** [yangchaojiang/yjPlay#143]
问题现象：播放界面闪屏
作为一个组件加入布局，布局中的edittext获取焦点导致软键盘弹出时，播放器界面一直闪屏

**Comment by yangchaojiang** [comment]
自己功能清单设置盘但弹出方式或者，视频改成 app:surface_type="texture_view"

**Comment by I18N486** [comment]
添加这个属性，不再闪屏了，感谢支持。
