### ISSUE TITLE
ExoUserPlayer中强引用activity会导致内存泄漏哦

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#147]
Leaks会报错
![image](https://user-images.githubusercontent.com/4688773/43056278-f26d28d2-8e6d-11e8-8c86-2d554ebe0107.png)

**Comment by yangchaojiang** [comment]
检查你的使用没有释放相应资源？ 没有肯定释放肯定要

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/43067244-5ebf4f1c-8e99-11e8-895e-7df52db9a1c5.png)
 看你的截图使用单例模式，单例使用不当的话，容易造成activity 无法正确释放的

**Comment by h3clikejava** [comment]
大哥我这是实例，不是单例！而且ExoUserPlayer类的releasePlayers方法没有释放activity对象，肯定是会泄漏的啊

**Comment by yangchaojiang** [comment]
版本2.1.91
