### ISSUE TITLE
控制隐藏方法无效

### ISSUE THREAD

**Issue by I18N486** [yangchaojiang/yjPlay#148]
隐藏全屏按钮：
videoPlayerView.showFullscreenTempView(View.GONE);

隐藏返回按钮：
baseview中，未开放出来：
showBackView(int visibility, boolean is)；

隐藏全屏按钮方法无效诶，然后可以在videoplayerview中增加方法控制返回按钮的显示隐藏吗？

**Comment by yangchaojiang** [comment]
控制全屏按钮
          //屏蔽控制布局
                            exoPlayerManager.hideControllerView(true);
                            //true如果屏蔽控制布局 但是需要显示全屏按钮。手动显示。
                        } else {
                            //恢复控制布局
                            exoPlayerManager.showControllerView(true);
                        }
}
不好意思，隐藏返回按钮：没有开放

**Comment by yangchaojiang** [comment]
版本2.1.91 
方法：videoPlayerView.setShowBack(false);
