### ISSUE TITLE
[緊急] java.lang.NullPointerException

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#149]
1 java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:618)
--
2 chuangyuan.ycj.videolibrary.video.ExoUserPlayer.setDefaultLoadModel(ExoUserPlayer.java:362)
3 chuangyuan.ycj.videolibrary.video.ExoUserPlayer.createFullPlayer(ExoUserPlayer.java:318)
4 chuangyuan.ycj.videolibrary.video.ExoUserPlayer.createPlayers(ExoUserPlayer.java:294)
5 chuangyuan.ycj.videolibrary.video.ExoUserPlayer$PlayComponentListener.onCreatePlayers(ExoUserPlayer.java:934)
6 chuangyuan.ycj.videolibrary.widget.VideoPlayerView$4.onClick(VideoPlayerView.java:368)

該行task對象可能為空，規避一下。

![image](https://user-images.githubusercontent.com/4688773/43434626-12abaac8-94af-11e8-9e9e-1047afd4373a.png)

**Comment by yangchaojiang** [comment]
赶上是时候了，版本2.191  已修改
