### ISSUE TITLE
Update percent loading

### ISSUE THREAD

**Issue by funnymobiledev** [yangchaojiang/yjPlay#15]
Hi,
Thanks for good library about media player, i used it for some my project.
I have a idea that you can update percent loading, that allow user know when player load and may be play.

**Comment by yangchaojiang** [comment]
Thank you for your support and will consider your great suggestions. For the next version to achieve.

**Comment by yangchaojiang** [comment]
1.5.7 percent loading

**Comment by mdtuyen** [comment]
Thank for good feature
