### ISSUE TITLE
播放离线视频，会有缓冲过程

### ISSUE THREAD

**Issue by chinahbpyj** [yangchaojiang/yjPlay#150]
播放离线视频，怎么去掉缓冲过程，手机本地播放器就没有这样的过程，进去就直接播放了

**Comment by yangchaojiang** [comment]
文件是被加密和切成碎片的。优酷和腾讯和文件加密缓存都是加载过程的

**Comment by chinahbpyj** [comment]
有什么解决办法吗

**Comment by yangchaojiang** [comment]
不用exoplayer缓存哦，自己下载文件。路径的指定下载的文件路径

**Comment by chinahbpyj** [comment]
我就是自己的离线视频

**Comment by h3clikejava** [comment]
确实有这个问题，就是直接播放本地的视频，也会有加载的过程。而且加载过程会显示黑色背景及Loading数字很不友好，我觉得应该显示最后一帧和Loading

**Comment by yangchaojiang** [comment]
缓存文件都是加密处理。加载重新组合一下， 优酷缓存都是一样。 @h3clikejava ，。
没有最后一帧
