### ISSUE TITLE
播放需要重定向（httpResponseCode：302）的url时，播放失败

### ISSUE THREAD

**Issue by diamondlin2016** [yangchaojiang/yjPlay#151]
问题现象：xxxxx
错误日志：xxxxxx

播放需要重定向（httpResponseCode：302）的url时，播放失败

**Comment by diamondlin2016** [comment]
谢谢老哥细心解答，有个疑问，这个重定向功能设计的时候为什么不默认为ture呢

**Comment by yangchaojiang** [comment]
。这个要问exoPlay 开发者了。不是我。因为参数自己改就行了
