### ISSUE TITLE
如果播放本地视频，例子：raw

### ISSUE THREAD

**Issue by dicallc** [yangchaojiang/yjPlay#152]
问题现象：如果播放本地视频，例子：raw

**Comment by yangchaojiang** [comment]
[例子](https://blog.csdn.net/dazhaodai/article/details/73650610)

**Comment by dicallc** [comment]
你好，通过把raw视频转到手机存储卡后，播放失败

**Comment by yangchaojiang** [comment]
你的转到手机存储卡后，就用调用sd目录的方式哦。demo 有
.setPlayUri("/storage/emulated/0/DCIM/Camera/VID_20170717_011150.mp4")
