### ISSUE TITLE
好像不支持 concat协议

### ISSUE THREAD

**Issue by renwfy** [yangchaojiang/yjPlay#156]
问题现象：本地片接的 ffconcat文件
ffconcat version 1.0
file 'http://61.179.109.170/0/w/0579c8aec4b7f685694dbd60181c2ecb.mp4?type=ppbox.launcher.vip&key=7697931f05eec868a5b85535cc650a88&k=6f0914db891b6391aa7025db0dced1e9-6dd0-1533710655'
duration 171
file 'http://61.179.109.170/1/w/0579c8aec4b7f685694dbd60181c2ecb.mp4?type=ppbox.launcher.vip&key=7697931f05eec868a5b85535cc650a88&k=6f0914db891b6391aa7025db0dced1e9-6dd0-1533710655'
duration 178
file 'http://61.179.109.170/2/w/0579c8aec4b7f685694dbd60181c2ecb.mp4?type=ppbox.launcher.vip&key=7697931f05eec868a5b85535cc650a88&k=6f0914db891b6391aa7025db0dced1e9-6dd0-1533710655'
duration 218
file 'http://61.179.109.170/3/w/0579c8aec4b7f685694dbd60181c2ecb.mp4?type=ppbox.launcher.vip&key=7697931f05eec868a5b85535cc650a88&k=6f0914db891b6391aa7025db0dced1e9-6dd0-1533710655'
duration 220

无法播放

**Comment by yangchaojiang** [comment]
支持的。你没有添加cronet协议的库。eoxplayer 是作拓展。需要添加一下/
····
    implementation 'com.google.android.exoplayer:extension-cronet:2.8.2'
····
![default](https://user-images.githubusercontent.com/13806413/43814708-616df94a-9afe-11e8-8f22-6d8058d0345b.png)

![default](https://user-images.githubusercontent.com/13806413/43814731-843594d8-9afe-11e8-9630-913aae809434.png)

**Comment by renwfy** [comment]
添加了这个后 implementation 'com.google.android.exoplayer:extension-cronet:2.8.2'，怎么操作，好像没明白，

我先研究下吧

**Comment by renwfy** [comment]
好像不能引入这个   implementation 'com.google.android.exoplayer:extension-cronet:2.8.2'

![image](https://user-images.githubusercontent.com/6526280/43815034-328b6e08-9b00-11e8-99fc-553ea5c63068.png)

**Comment by yangchaojiang** [comment]
这个拓展需要自己本地 exoplayer 没有远程库

**Comment by yangchaojiang** [comment]
[cronet](https://github.com/google/ExoPlayer/tree/release-v2/extensions)

**Comment by yangchaojiang** [comment]
[查看](https://github.com/google/ExoPlayer/tree/release-v2/extensions/cronet)

**Comment by yangchaojiang** [comment]
你耐心等一下，我需要这个下载到我库里。

**Comment by yangchaojiang** [comment]
如果你播放列表可以用setListUril（）；也可以实现的

**Comment by renwfy** [comment]
我现在就是用这个方式了 setListUril（），就是视频时长不大和谐 ……

**Comment by renwfy** [comment]
我是一个完整的视频，所以要拼接这个

**Comment by yangchaojiang** [comment]
exoplayer 现在没怎么维护了这个拓展。我需要改一下。你方便这个文件问一下发我，我测试需要。
1007181167

**Comment by renwfy** [comment]
你这是qq？
