### ISSUE TITLE
大佬 kotlin怎么初始化播放器

### ISSUE THREAD

**Issue by Leavds** [yangchaojiang/yjPlay#157]
![qq 20180808121320](https://user-images.githubusercontent.com/26810069/43815919-b9392630-9b04-11e8-8ff9-327de3891db8.png)
![qq 20180808121414](https://user-images.githubusercontent.com/26810069/43815920-b986e618-9b04-11e8-82b9-0804f2db2773.png)
![qq 20180808121205](https://user-images.githubusercontent.com/26810069/43815921-ba38fad8-9b04-11e8-82e0-d354169b5c94.png)

**Comment by yangchaojiang** [comment]
当前你的使用控制器的类/ 你要赋值给那个

**Comment by Leavds** [comment]
尴尬了，我这边搞错了
