### ISSUE TITLE
布局文件使用 CoordinatorLayout 和CollapsingToolbarLayout 时ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by TigerSkinZhang** [yangchaojiang/yjPlay#159]
Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at chuangyuan.ycj.videolibrary.widget.BaseView.<init>(BaseView.java:111)
        at chuangyuan.ycj.videolibrary.widget.VideoPlayerView.<init>(VideoPlayerView.java:70)
        at chuangyuan.ycj.videolibrary.widget.VideoPlayerView.<init>(VideoPlayerView.java:59)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116) 
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:88) 
        
布局文件使用 CoordinatorLayout 和CollapsingToolbarLayout
 <android.support.design.widget.CoordinatorLayout
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/background_light"
            android:fitsSystemWindows="true"
            android:layout_above="@+id/bottom"
            >

            <android.support.design.widget.AppBarLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/app_background_color"
                android:fitsSystemWindows="true"
                android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

                <android.support.design.widget.CollapsingToolbarLayout
                    android:id="@+id/toolbar_layout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:fitsSystemWindows="true"
                    app:contentScrim="#1fcfb6"
                    app:expandedTitleMarginEnd="64dp"

                    app:expandedTitleMarginStart="48dp"
                    app:layout_scrollFlags="scroll|exitUntilCollapsed">
                    <chuangyuan.ycj.videolibrary.widget.VideoPlayerView
                        android:id="@+id/player_view"
                        android:layout_width="match_parent"
                        android:layout_height="250dp"
                        android:background="@android:color/transparent"
                        app:player_layout_id="@layout/simple_exo_view"
                        app:player_hint_layout_id="@layout/custom_play_btn_hint"
                        app:player_error_layout_id="@layout/custom_play_error"
                        app:player_replay_layout_id="@layout/custom_play_replay"
                        app:player_gesture_audio_layout_id="@layout/custom_gesture_audio"
                        app:player_gesture_bright_layout_id="@layout/custom_gesture_brightness"
                        app:player_gesture_progress_layout_id="@layout/custom_gesture_pro"
                        app:player_back_image="@drawable/ic_arrow_back_black_24dp"
                        app:player_preview_layout_id="@layout/custom_exo_defaultload"
                        app:resize_mode="fit"
                        app:rewind_increment="0"
                        app:show_timeout="3000"
                        app:surface_type="texture_view"
                        app:use_artwork="true"
                        app:user_watermark="@drawable/watermark_big"
                        />
        

                    <android.support.v7.widget.Toolbar
                        android:id="@+id/toolbar"
                        android:layout_width="match_parent"
                        android:layout_height="?android:attr/actionBarSize"
                        app:layout_collapseMode="pin"
                        android:background="@color/transparent"
                      />

                </android.support.design.widget.CollapsingToolbarLayout>
作者您好，使用过程中遇到以上问题，麻烦有空看看

**Comment by TigerSkinZhang** [comment]
建议使用另外的方法获取activity，可能被CollapsingToolbarLayout包裹的布局context有变化 这个应该管用
 /***
     * 得到活动对象
     *
     * @param context 上下文
     * @return AppCompatActivity app comp activity
     */
    @Nullable
    public static AppCompatActivity getAppCompActivity(@NonNull Context context) {
        if (context instanceof AppCompatActivity) {
            return (AppCompatActivity) context;
        } else if (context instanceof ContextThemeWrapper) {
            return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());
        }
        return null;
    }

**Comment by TigerSkinZhang** [comment]
另外，这个问题低版本设备上不会出现 ，高点的版本会

**Comment by yangchaojiang** [comment]
你好，出问题机型是多少。 我最快时间修复

**Comment by TigerSkinZhang** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/nestedScrollView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:fillViewport="true"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <com.dl7.player.media.IjkPlayerView
                android:id="@+id/player_view"
                android:layout_width="match_parent"
                android:layout_height="250dp" />

            <LinearLayout
                android:id="@+id/ly_tab"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@+id/player_view"
                android:background="#332"
                android:orientation="horizontal"
                android:weightSum="3">

                <com.dl7.tag.TagLayout
                    android:id="@+id/tag_layout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:tag_layout_fit_num="3"
                    app:tag_layout_mode="single_choice"
                    app:tag_view_bg_color_check="@android:color/white"
                    app:tag_view_border_color_check="@android:color/holo_red_light"
                    app:tag_view_text_color_check="@android:color/holo_red_light" />

                <TextView
                    android:id="@+id/tv_comment"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:text="评价"
                    android:textColor="#ffff"
                    android:textSize="17sp" />
            </LinearLayout>

            <android.support.v4.view.ViewPager
                android:id="@+id/vp_data"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/ly_tab" />

        </RelativeLayout>
    </android.support.v4.widget.NestedScrollView>
        <RelativeLayout
            android:id="@+id/bottom"
            android:layout_width="match_parent"
            android:layout_height="49dp"
            android:layout_alignParentBottom="true"
          >

            <TextView
                android:id="@+id/tv_share"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:text="分享"
                android:textSize="16sp"
                android:textColor="#3b3b40" />

            <TextView
                android:id="@+id/tv_fav"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_toLeftOf="@+id/tv_join"
                android:text="收藏"
                android:layout_marginRight="18dp"
                android:textSize="16sp"
                android:textColor="#3b3b40"
                />

            <TextView
                android:id="@+id/tv_join"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:background="#1fcfb6"
                android:gravity="center"
                android:paddingLeft="51dp"
                android:paddingRight="51dp"
                android:text="加入课程"
                android:textColor="#ffffff"
                android:textSize="16sp" />
        </RelativeLayout>
    </RelativeLayout>
7.0以上都可以，这是demo布局，您贴进去运行就知道了

**Comment by TigerSkinZhang** [comment]
贴错

**Comment by TigerSkinZhang** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/nestedScrollView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:fillViewport="true"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <com.dl7.player.media.IjkPlayerView
                android:id="@+id/player_view"
                android:layout_width="match_parent"
                android:layout_height="250dp" />

            <LinearLayout
                android:id="@+id/ly_tab"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@+id/player_view"
                android:background="#332"
                android:orientation="horizontal"
                android:weightSum="3">

                <com.dl7.tag.TagLayout
                    android:id="@+id/tag_layout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:tag_layout_fit_num="3"
                    app:tag_layout_mode="single_choice"
                    app:tag_view_bg_color_check="@android:color/white"
                    app:tag_view_border_color_check="@android:color/holo_red_light"
                    app:tag_view_text_color_check="@android:color/holo_red_light" />

                <TextView
                    android:id="@+id/tv_comment"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:text="评价"
                    android:textColor="#ffff"
                    android:textSize="17sp" />
            </LinearLayout>

            <android.support.v4.view.ViewPager
                android:id="@+id/vp_data"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/ly_tab" />

        </RelativeLayout>
    </android.support.v4.widget.NestedScrollView>
        <RelativeLayout
            android:id="@+id/bottom"
            android:layout_width="match_parent"
            android:layout_height="49dp"
            android:layout_alignParentBottom="true"
          >

            <TextView
                android:id="@+id/tv_share"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:text="分享"
                android:textSize="16sp"
                android:textColor="#3b3b40" />

            <TextView
                android:id="@+id/tv_fav"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_toLeftOf="@+id/tv_join"
                android:text="收藏"
                android:layout_marginRight="18dp"
                android:textSize="16sp"
                android:textColor="#3b3b40"
                />

            <TextView
                android:id="@+id/tv_join"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:background="#1fcfb6"
                android:gravity="center"
                android:paddingLeft="51dp"
                android:paddingRight="51dp"
                android:text="加入课程"
                android:textColor="#ffffff"
                android:textSize="16sp" />
        </RelativeLayout>
    </RelativeLayout>

**Comment by yangchaojiang** [comment]
好的。 在想知道，问题出现修手机型号 Android版本。方便复现问题。

**Comment by TigerSkinZhang** [comment]
华为荣耀8青春版，我在模拟器上试了也是一样的

**Comment by yangchaojiang** [comment]
版本2.2.12 。记得star 谢谢支持哈

**Comment by TigerSkinZhang** [comment]
感谢修复， 感谢您的付出(^o^)

**Comment by yangchaojiang** [comment]
是否以解决

**Comment by TigerSkinZhang** [comment]
刚跑了一下还有错
Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at chuangyuan.ycj.videolibrary.widget.BaseView.intiView(BaseView.java:194)
        at chuangyuan.ycj.videolibrary.widget.BaseView.<init>(BaseView.java:149)
        at chuangyuan.ycj.videolibrary.widget.VideoPlayerView.<init>(VideoPlayerView.java:70)
        at chuangyuan.ycj.videolibrary.widget.VideoPlayerView.<init>(VideoPlayerView.java:59)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116) 
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:88) 
        at com.yiyatech.android.module.courses.activity.CourseDetailActivity.onCreate(CourseDetailActivity.java:82) 
        at android.app.Activity.performCreate(Activity.java:6679) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by yangchaojiang** [comment]
我的锅， 着急了

**Comment by yangchaojiang** [comment]
2.2.13 版本。不行就就 :cop: :cop: :cop: :cop:

**Comment by TigerSkinZhang** [comment]
还需要再麻烦一下。。
  Process: com.yiyatech.android, PID: 13334
    java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at chuangyuan.ycj.videolibrary.video.VideoPlayerManager$Builder.<init>(VideoPlayerManager.java:230)

**Comment by yangchaojiang** [comment]
2.2.15 版本，不行就就

**Comment by TigerSkinZhang** [comment]
@十分感谢，可以了。辛苦哈
