### ISSUE TITLE
能默认全屏播放吗?

### ISSUE THREAD

**Issue by tmxd09887** [yangchaojiang/yjPlay#165]
现在要点全屏播放按钮才能全屏

能默认全屏播放吗?

**Comment by yangchaojiang** [comment]
在功能清单设置横屏模式就行了

**Comment by tmxd09887** [comment]
<activity android:name=".playerActivity"
android:configChanges="orientation|keyboardHidden|screenSize"
android:screenOrientation="landscape"/>

是这样吗？没变化啊。

谢谢

**Comment by yangchaojiang** [comment]
可以的

**Comment by tmxd09887** [comment]
android:screenOrientation="landscape" 可以横屏

但是不能全屏

在playerActivity里加上
		ActionBar actionBar = getSupportActionBar();
		actionBar.hide();
隐藏actionbar
		getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
隐藏状态栏

现在可以全屏

但是没有默认设置啊？

**Comment by yangchaojiang** [comment]
你是不是少代码哦。实现  public void onConfigurationChanged(Configuration newConfig) { }d方法没

**Comment by tmxd09887** [comment]
@Override
	public void onConfigurationChanged(Configuration newConfig) {
		exoPlayerManager.onConfigurationChanged(newConfig);//横竖屏切换
		super.onConfigurationChanged(newConfig);
	}

写了啊

**Comment by tmxd09887** [comment]
找到原因啦

默认是跟随屏幕方向，改变状态才会隐藏actionbar和状态栏。我要的效果是强制横屏状态下全屏（隐藏）。

搞定了，谢谢。
