### ISSUE TITLE
横竖切换的时候，视频会会报错，但其实这个视频可以播放的

### ISSUE THREAD

**Issue by FLYANDHEIGHT** [yangchaojiang/yjPlay#168]

**Comment by FLYANDHEIGHT** [comment]
在观看视频的时候，跳转到其他界面在跳转回来，图像就出不来了，卡住，声音可以播放

**Comment by yangchaojiang** [comment]
实现时实现周期方法，还有功能清单文件申明么

**Comment by FLYANDHEIGHT** [comment]
申请了  
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT" />
    <uses-permission android:name="com.android.launcher.permission.UNINSTALL_SHORTCUT" />
    <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    
    <uses-permission android:name="android.permission.READ_LOGS" />
    
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />

**Comment by FLYANDHEIGHT** [comment]
<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT" />
    <uses-permission android:name="com.android.launcher.permission.UNINSTALL_SHORTCUT" />
    <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    
    <uses-permission android:name="android.permission.READ_LOGS" />
    
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />

**Comment by yangchaojiang** [comment]
我说不是权限。。。。。[查看](https://github.com/yangchaojiang/yjPlay#5%E5%9C%A8%E5%8A%9F%E8%83%BD%E6%B8%85%E5%8D%95%E5%A3%B0%E6%98%8E-androidmanifestxml)
```
       <activity android:name="chuangyuan.ycj.yjplay.MainListActivity"
         android:configChanges="orientation|keyboardHidden|screenSize"
         android:screenOrientation="portrait">
```

**Comment by FLYANDHEIGHT** [comment]
<activity
            android:name=".easyCorrection.onlineEducation.onlineCourse.PlayTimeActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait" />

**Comment by FLYANDHEIGHT** [comment]
<activity
            android:name=".easyCorrection.onlineEducation.onlineCourse.PlayTimeActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait" />

**Comment by FLYANDHEIGHT** [comment]
<activity android:name="easyCorrection.onlineEducation.onlineCourse.PlayTimeActivity"
         android:configChanges="orientation|keyboardHidden|screenSize"
         android:screenOrientation="portrait">

**Comment by FLYANDHEIGHT** [comment]
有的，我用你的demo里面的MainDetailedActivity第一个默认详细播放，也会出现上述那种，播放时调到别的界面超过一分半钟，再回来就只有声音没图像，卡在那

**Comment by yangchaojiang** [comment]
你是使用版本多少

**Comment by FLYANDHEIGHT** [comment]
魅族note3 7.0

**Comment by FLYANDHEIGHT** [comment]
我直接下的demo改的源码

**Comment by yangchaojiang** [comment]
.....

**Comment by FLYANDHEIGHT** [comment]
Audio_PerfServiceNative_userEnable == NULL

**Comment by FLYANDHEIGHT** [comment]
要不我把代码传给你看下？

**Comment by yangchaojiang** [comment]
我浮现了，知道

**Comment by FLYANDHEIGHT** [comment]
好的

**Comment by FLYANDHEIGHT** [comment]
这个问题复杂吗？

**Comment by yangchaojiang** [comment]
h电脑出问题了。需要重装， 我晶尽快修复的

**Comment by FLYANDHEIGHT** [comment]
尽快吧，客户在催着，谢谢了

**Comment by yangchaojiang** [comment]
你好在吗？

**Comment by yangchaojiang** [comment]
你是下载本地的话。，告诉你在那个文件
![default](https://user-images.githubusercontent.com/13806413/44713779-69430500-aae6-11e8-902a-8b21d8b17500.png)
删除两段代码就行了
````
    if(mTakeOverSurfaceTexture)
                mSurfaceTexture = surface;
````

**Comment by FLYANDHEIGHT** [comment]
好的我试试

**Comment by FLYANDHEIGHT** [comment]
还有我想直接设置seek进度点不能拖拽，并且不想出现那种拖拽之后进度条再返回的那种动画

**Comment by yangchaojiang** [comment]
videoPlayerView.getTimeBar().setOpenSeek();     默认是true 你该false

**Comment by FLYANDHEIGHT** [comment]
这方法，seekbar还是能拖，只不过拖拽之后会回到原处

**Comment by yangchaojiang** [comment]
效果只能这样的，你可以该控制

**Comment by yangchaojiang** [comment]
或者你隐藏进度条

**Comment by FLYANDHEIGHT** [comment]
好的
