### ISSUE TITLE
请问一个列表若何滑动到的时候自动播放，上一个视频自动销毁？

### ISSUE THREAD

**Issue by magicLanjie** [yangchaojiang/yjPlay#170]

**Comment by yangchaojiang** [comment]
是你在列表处理listview或者recyleView的回调，然后跳用播放器实例。 播放当前会会自动释放上一个的

**Comment by magicLanjie** [comment]
如何自动播放呢？

**Comment by yangchaojiang** [comment]
自己实现呀。listview或者recyleView的回调  然后调 exoPlayerManager.startPlayer(); 就播放了哦

**Comment by magicLanjie** [comment]
设置了       app:player_list="true"  然后调用start的时候回只有声音没有画面，预览界面没有自动去掉掉

**Comment by yangchaojiang** [comment]
升级到2.2.18b版本。

**Comment by yangchaojiang** [comment]
注意列表复用

**Comment by magicLanjie** [comment]
谢谢了。。

**Comment by magicLanjie** [comment]
大兄弟 我觉得你那个视频宽度小于高度时候的全屏，有点儿骚！厉害，

**Comment by magicLanjie** [comment]
视频是旋转了，可是标题那些都，精度条都在还是在原来的位置

**Comment by yangchaojiang** [comment]
我是参考的视频app处理方式。视频内容选择。布局不旋转。
