### ISSUE TITLE
列表播放，播放几个视频后出现黑屏

### ISSUE THREAD

**Issue by jushenziao** [yangchaojiang/yjPlay#178]
只有声音，没有图像

**Comment by jushenziao** [comment]
点击全屏返回后图像又显示出来了

**Comment by yangchaojiang** [comment]
你请问使用版本是？

**Comment by jushenziao** [comment]
> 你请问使用版本是？

我在master上编译的

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/45725914-aa16d100-bbef-11e8-84b7-71a85ae3285f.png)
