### ISSUE TITLE
切换小窗口或全屏时延迟问题

### ISSUE THREAD

**Issue by jeasonHu** [yangchaojiang/yjPlay#179]
我接入exoplayer,滑动显示小窗口播放、切换全屏  用removeView、addView 操作播放view，但有延迟。看exo的 issues,你有提及这个问题，请较下你的解决方案

**Comment by yangchaojiang** [comment]
自己实现的渲染就行了！不接入EXO player的SurfaceView和TextureView

**Comment by yangchaojiang** [comment]
自己实现的渲染就行了！不接入EXO player的SurfaceView和TextureView

**Comment by jeasonHu** [comment]
> 接入EXO player的SurfaceView和
![image](https://user-images.githubusercontent.com/14819724/45689129-bc5c2500-bb85-11e8-8269-624aef12db7c.png)
看你demo中全屏的逻辑是这样，

**Comment by jeasonHu** [comment]
> 自己实现的渲染就行了！不接入EXO player的SurfaceView和TextureView

有些不明白，能具体点么

**Comment by yangchaojiang** [comment]
自己写SurfaceView和TextureView  不用exoplayer实现的播
