### ISSUE TITLE
UI依赖建议

### ISSUE THREAD

**Issue by sunkeding** [yangchaojiang/yjPlay#18]
//compile project(':VideoUi')
   compile 'com.ycjiang:VideoUi:1.0.4'
目前是这样依赖的，能不能以Module的方式依赖啊，这样可以更加方便的进行UI修改

**Comment by yangchaojiang** [comment]
目前没有开放，该库目的，后期考虑开放出来

**Comment by sunkeding** [comment]
老哥，能否把这个代码的源码开放出来，以module方式哈，然后最小api改为16哦
