### ISSUE TITLE
空指针问题

### ISSUE THREAD

**Issue by sunkeding** [yangchaojiang/yjPlay#180]
Attempt to invoke interface method 'void com.google.android.exoplayer2.source.m$a.onSourceInfoRefreshed(com.google.android.exoplayer2.r, java.lang.Object)' on a null object reference

com.google.android.exoplayer2.source.j.notifySourceInfoRefreshed(ExtractorMediaSource.java)

bugly上报了很多这个错误，谷歌的视频库最开始是r2.5.3，现在升级到了2.8.4;都存在这个问题

**Comment by sunkeding** [comment]
好多手机系统都是Android8.0.0和Android8.1.0；小米手机居多

**Comment by yangchaojiang** [comment]
请问这个库版本你是多了 2.2.19吗

**Comment by yangchaojiang** [comment]
我的库目前没有这个错误吗？

**Comment by sunkeding** [comment]
视频库低版本有这个问题，之前以补丁的形式升级了谷歌库，观察了一段时间是补丁包太大，小米手机兼容性问题，最新的视频库2.8.4版本，暂时没看到该报错，继续观察下

**Comment by yangchaojiang** [comment]
好的，继续观察
