### ISSUE TITLE
播放视频时，把手机息屏待机，再开手机时视频画面不动，只有声音恢复动-2.2.19

### ISSUE THREAD

**Issue by tjm800** [yangchaojiang/yjPlay#181]
问题现象：播放视频时，把手机息屏待机，再开手机时视频画面不动，只有声音恢复动-2.2.19版，手机系统为华为android5.0 畅享5。

**Comment by tjm800** [comment]
感觉和 exoPlayerManager.onPause();有关，因为当我在同样的手机上，点击更换视频源时手动onPause()，再startPlayer(),也是画面不动，声音走而已，跃然请大神帮解决，谢谢！

**Comment by yangchaojiang** [comment]
.....

**Comment by yangchaojiang** [comment]
.onPause() 不能手动的，你要切换视频  显示释放资源，重新制定视频和在播放

**Comment by tjm800** [comment]
播放视频时，把手机锁屏待机，再开锁手机时视频画面不动，只有声音，画面一直是刚锁屏时的画面-2.2.19版，手机系统为华为android5.0 畅享5。

**Comment by tjm800** [comment]
但如果此时点击全屏了，画面就跟着动了

**Comment by yangchaojiang** [comment]
http://oph6zeldx.bkt.clouddn.com/app-release-unsigned_signed_zipalign.apk
你好，试一下，这个版本有没有问题， 我们这目前5没有.0的系统

**Comment by pxhgithup** [comment]
怎么释放资源，重新制定视频和在播放，这样VideoPlayerManager.getInstance().onPause(true)？好像不行

**Comment by yangchaojiang** [comment]
，这样VideoPlayerManager.getInstance().onPause(true) 这是暂停不是释放。palyer.releasePlayers()
