### ISSUE TITLE
取消wifi判定问题

### ISSUE THREAD

**Issue by nuoyan2** [yangchaojiang/yjPlay#185]
因为使用的是网线但是还是会提示不是wifi让点确定 所以能不能把这个判断去掉 通过修改您的源码我实现了，但是您的源码module不怎么好添加（是我的原因） 有没有其它的方法来取消这个判断  ？

   /**
     * 检查当前网络是否可用 
     *
     * @param mContext 活动
     * @return boolean boolean
     */
    public static boolean isWifi(@NonNull Context mContext) {
//        ConnectivityManager connectivityManager = (ConnectivityManager) mContext
//                .getSystemService(Context.CONNECTIVITY_SERVICE);
//        NetworkInfo activeNetInfo = connectivityManager.getActiveNetworkInfo();
//        return activeNetInfo != null
//                && activeNetInfo.getType() == ConnectivityManager.TYPE_WIFI;
        return true;
    }

**Comment by yangchaojiang** [comment]
[#参考172](https://github.com/yangchaojiang/yjPlay/issues/172)

**Comment by nuoyan2** [comment]
已经实现 感谢您的回答
