### ISSUE TITLE
m3u8下载无反应

### ISSUE THREAD

**Issue by shuncaigao** [yangchaojiang/yjPlay#188]
m3u8下载无反应
<service
            android:name=".offline.DemoDownloadService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.exoplayer.downloadService.action.INIT" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </service>

Application:
        ExoWholeDownLoadManger.getSingle().initDownloadManager(this,DemoDownloadService.class);
Activity:
        exoDownloadTracker = ExoWholeDownLoadManger.getSingle().getExoDownloadTracker();
   exoDownloadTracker.toggleDownload(mActivity, mData.getName(), Uri.parse(mPlayUrl), "m3u8");
        exoDownloadTracker.addListener(new ExoDownloadTracker.Listener() {
            @Override
            public void onDownloadsChanged(int state) {
                Log.d(TAG, "taskState：" + state);
            }
        });

**Comment by shuncaigao** [comment]
Log.d(TAG, "taskState：" + state);   
返回 2  
但是文件管理里也是找不到 m3u8 或者ts文件

**Comment by yangchaojiang** [comment]
下载后都是加密文件的。 .exo文件的
