### ISSUE TITLE
（新手）暂停与继续播放问题

### ISSUE THREAD

**Issue by nuoyan2** [yangchaojiang/yjPlay#189]
为什么我调用 exoPlayerManager.onPause(); 可以实现暂停 但是继续播放调用 exoPlayerManager.startPlayer();不会继续播放还是保持暂停状态  谢谢

**Comment by nuoyan2** [comment]
好的我试试

**Comment by yangchaojiang** [comment]
觉得可以卡，点点star。支持一下😂 😂 😂
