### ISSUE TITLE
Viewpager中放视频的话，缩略图无法满屏视频的宽高

### ISSUE THREAD

**Issue by sunkeding** [yangchaojiang/yjPlay#19]
图会很小

**Comment by yangchaojiang** [comment]
Viewpager 没测试过，。 能截图就看一下么

**Comment by sunkeding** [comment]
之前参考MainDetailedActivity的布局出现的，用了MainCustomActivity的布局是正常的

**Comment by yangchaojiang** [comment]
ok .两个图片控件  使用属性不同的。MainDetailedActivity 没有使用  android:scaleType="fitXY"
目前你getPreviewImage() 可以代码进行缩放类型 下版本一致

**Comment by yangchaojiang** [comment]
1.5.7.2  已修复

**Comment by yangchaojiang** [comment]
1.5.7.2

**Comment by 343757500** [comment]
无法正常引用呀

**Comment by yangchaojiang** [comment]
可以了么 可以就star 谢谢支持

**Comment by sunkeding** [comment]
多谢，希望能开放出播放中的进度接口，时刻知道播放了多少秒

**Comment by yangchaojiang** [comment]
这个需求没有 意义不大哦， 你可以再用时候，获取当前进度就行， 提供相应方法哦

**Comment by sunkeding** [comment]
因为是视频播放是写在Viewpager里面，Viewpager里的第一个是视频，后面全是图片，viewpager下方有小圆点，用来指示当前是哪个banner，需要在视频播放的时候隐藏掉小圆点，视频不播放的时候显示小原点

**Comment by yangchaojiang** [comment]
ooo  不好意思，昨天有i忙， 暂停么。还是播放结束

**Comment by sunkeding** [comment]
viewpager写在Activity里面，viewpager上的第一个item是个视频，其他item是图片，viewpager的最底下有小圆点盖在viewpager上方，现在需要监听视频的播放，如果视频正在播放，那么底部小圆点需要隐藏，如果刚进页面或者没播放视频的话是需要把小圆点显示出来的，以此来告诉用户这里是可以左右滑动切换bannner的

**Comment by yangchaojiang** [comment]
哦哦哦， 1.5.7.3 分支版本
 videoPlayerView.getPreviewImage().setScaleType(ImageView.ScaleType.FIT_XY);
缩略图无法满屏视频的宽高 d需要设置自己一下。VideoInfoListener 回调信息 增加isPlaying(boolean isPlayer)   方法回调

**Comment by sunkeding** [comment]
非常感谢哈

**Comment by sunkeding** [comment]
对了，你的分支没提交哦

**Comment by yangchaojiang** [comment]
没，
