### ISSUE TITLE
您好，如何在代码里面统一指定缓冲大小？

### ISSUE THREAD

**Issue by qiusunshine** [yangchaojiang/yjPlay#190]
如题即MAX_BUFFER_MS，不知道如何简单指定缓冲的大小，有没有初始化时直接配置的接口，翻了大神您的源码，有点晕；
我使用的版本是：2.1.91；
期待您的解答，谢谢！

**Comment by yangchaojiang** [comment]
???/ 你要改缓冲大小？？

**Comment by qiusunshine** [comment]
好的，谢谢你

**Comment by qiusunshine** [comment]
我通过反射修改后，发现播放有声音，但是画面是黑的，显示着控制器，这是怎么回事呢？我修改的代码如下：

![image](https://user-images.githubusercontent.com/27729606/47090063-aad56e00-d254-11e8-876d-4f7007454b87.png)

我的想法就是想增大最大缓存时间，比如腾讯X5浏览器的缓存时间就比较长，而exoplayer默认的最大缓存时间只有30s，对于网络不好的情况，经常会进入loading状态

**Comment by yangchaojiang** [comment]
注意我给你截图最后一行代码。

你少了绑定view的通知哪行代码

**Comment by qiusunshine** [comment]
绑定view不是已经绑定过了？这只是反射修改player，哦，我知道了，我先试试，谢谢

**Comment by qiusunshine** [comment]
完美解决问题，谢谢！
