### ISSUE TITLE
播放本地视频如何去除网络加载以及无网络时的提示框？

### ISSUE THREAD

**Issue by I18N486** [yangchaojiang/yjPlay#199]
如题，播放本地视频不需要网络，如何去除网络相关？

**Comment by I18N486** [comment]
范例中支持多种加载模式，setloadtype方法已删除，当前支持切换加载模式吗？去除网络加载模式相关应该如何设置？

**Comment by yangchaojiang** [comment]
[请查看185](https://github.com/yangchaojiang/yjPlay/issues/185)

**Comment by I18N486** [comment]
所以只有通过VideoPlayerManager.getInstance().setClick(true); 去掉网络弹窗；加载模式无法切换是吗？之前版本不是有setloadModule方法么，现在不能设置了吗？

**Comment by yangchaojiang** [comment]
网络加载 目前不支持除去。比可以下载代码。需要显示地方改一隐藏
