### ISSUE TITLE
不能播放本地视频么

### ISSUE THREAD

**Issue by dadakkk** [yangchaojiang/yjPlay#2]
path = /storage/emulated/0/Movies/q.mp4
exoPlayerManager.setPlayUri(path);

**Comment by yangchaojiang** [comment]
是可以播放的，请查看你j路径是否正确

**Comment by yangchaojiang** [comment]
本地播放权限 
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
如果在targetSdkVersion 》=23，申请读取sd运行权限
