### ISSUE TITLE
关于第一次关闭视频地址服务器播放不成功   打开服务器继续播放问题

### ISSUE THREAD

**Issue by nuoyan2** [yangchaojiang/yjPlay#201]
想做个第一次播放关闭服务器 然后出现错误标志后 打开服务器重新开始播放 
 如果是拔掉和插上网线就
 if (exoPlayerManager.isPlaying()){
                        exoPlayerManager.setStartOrPause(false);
                    }
  if (!exoPlayerManager.isPlaying()){
                        exoPlayerManager.setStartOrPause(true);
                    }
就可以实现
不知道为什么关闭和打开服务器服务器这个方法就不行 我用这个方法三秒后检测没有播放就重新播放也好像也不行  
        exoPlayerManager.startPlayer();//开始播放

或者
  if (exoPlayerManager!=null){
            exoPlayerManager.onPause();
            exoPlayerManager.onStop();
            exoPlayerManager.releasePlayers();
        }
  wholeMediaSource.setMediaSource(videoSource);
        exoPlayerManager = new VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_MANUAL, videoPlayerView)
                .setDataSource(wholeMediaSource)
                .setPosition(currPosition)
                .setTitle("")
                .setOnPlayClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
//                        Toast.makeText(MainActivity.this, "定义点击播放事件", Toast.LENGTH_LONG).show();
                        //处理业务操作 完成后，
                        exoPlayerManager.startPlayer();//开始播放
                    }
                })
            .create();
        exoPlayerManager.setLooping(Integer.MAX_VALUE);
        exoPlayerManager.startPlayer();//开始播放
 求指点

**Comment by yangchaojiang** [comment]
请不要手动调用on开头的方法，这些方法周期方法。对应周期的
````
exoPlayerManager.onPause();
exoPlayerManager.onStop();
````
自己要释放 一个方法就行
````
exoPlayerManager.releasePlayers();
````

**Comment by nuoyan2** [comment]
感谢您的回答  昨天晚上我下班了 不好意思 今天测试了下好像并没有成功重新播放 
拔掉网线 打开app播放视频 出现播放错误字体 然后插入网线 我这边有网的时候会调用
   if (!exoPlayerManager.isPlaying()){
                        exoPlayerManager.setStartOrPause(true);
                    }

而且三秒后检查是否正在播放 如果没有就执行下面这段代码
        if (exoPlayerManager!=null){
            exoPlayerManager.releasePlayers();
        }
        MediaSource videoSource = wholeMediaSource.initMediaSource(
                Uri.parse(getString(R.string.uri_test_11)));
        videoPlayerView.setShowBack(false);
        ImageView imageView = videoPlayerView.getPreviewImage();
        imageView.setImageResource(R.mipmap.xxx1);
        wholeMediaSource.setMediaSource(videoSource);
        exoPlayerManager = new VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_MANUAL, videoPlayerView)
                .setDataSource(wholeMediaSource)
                .setPosition(currPosition)
                .setTitle("")
                .setOnPlayClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
//                        Toast.makeText(MainActivity.this, "定义点击播放事件", Toast.LENGTH_LONG).show();
                        //处理业务操作 完成后，
                        exoPlayerManager.startPlayer();//开始播放
                    }
                })
            .create();
        exoPlayerManager.setLooping(Integer.MAX_VALUE);
        exoPlayerManager.startPlayer();//开始播放

但是仍然播放不出

**Comment by yangchaojiang** [comment]
？？？？代码好乱

**Comment by nuoyan2** [comment]
下面的代码是直接复制你的代码... 是一个方法内的

**Comment by nuoyan2** [comment]
在你的MainListInfoCustomActivity类 的onCreate方法里的方法

**Comment by yangchaojiang** [comment]
demo代码。 我没有规范写。只是为了说明:joy::joy::joy::joy::joy:

**Comment by nuoyan2** [comment]
那您帮忙看看为什么不能重新播放  您那边可以试试 操作 一 关闭网络 打开app 播放视频  二 等到出现错误标志然后再打开网络  监听网络进行继续播放 或者重新播放 谢谢

**Comment by yangchaojiang** [comment]
控件有按钮继续播放的呀

**Comment by yangchaojiang** [comment]
的错误页面提示的，不需要自己实现呀

**Comment by nuoyan2** [comment]
控件我隐藏的 我这边不需要有控件的

**Comment by nuoyan2** [comment]
是有错误页面提示 但是我想来网了重新播放

**Comment by yangchaojiang** [comment]
```
exoPlayerManager.setStartOrPause(true);
```
直接播放就行了。 为什么还要在释放，在播放了。

**Comment by nuoyan2** [comment]
如果是播放中 断网exoPlayerManager.setStartOrPause(true); 这个方法是可以在来网的时候继续播放的 但是如果刚开始没网 就打开app播放 就不行了

**Comment by nuoyan2** [comment]
因为我在来网后判断是否在播放 如果没播放就exoPlayerManager.setStartOrPause(true); 然后三秒后我再判断有没有播放 如果没播放我就释放再重新加载资源播放

**Comment by nuoyan2** [comment]
感谢作者的帮助 已经解决  不需要释放资源 在来网的时候直接调用 
  if (!exoPlayerManager.isPlaying()){
                             exoPlayerManager.startPlayer();//开始播放
                          }
就能实现 感谢作者无私的奉献
