### ISSUE TITLE
build signed apk 出错

### ISSUE THREAD

**Issue by tmxd09887** [yangchaojiang/yjPlay#202]
com.ycjiang:VideoPlayModule:2.3.0版本

build错误提示
Warning: com.google.android.exoplayer2.ui.DefaultTrackNameProvider: can't find referenced field 'int exo_track_unknown' in program class com.google.android.exoplayer2.ui.R$string

好像跟混淆有关系，关了混淆就好了
混淆声明
-dontwarn chuangyuan.ycj.**
-keep class chuangyuan.ycj.** { *;}

**Comment by yangchaojiang** [comment]
好的，我看一下

**Comment by yangchaojiang** [comment]
在你的app的strings的xml 里添加
````
  <string name="exo_track_unknown">未知</string>
```
对齐就行了。 下版本修复

**Comment by yangchaojiang** [comment]
都加上就行了。下版本已经修复。 周末不再。陪我的爸妈

**Comment by tmxd09887** [comment]
你好，感谢，暂时没发现问题。
