### ISSUE TITLE
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

### ISSUE THREAD

**Issue by xiaolongwuhpu** [yangchaojiang/yjPlay#205]
帮忙看下哪里是不是没有配置:  mac 环境 
![0ff9c60e-f30e-4c33-ad29-436bf3a56515](https://user-images.githubusercontent.com/13296347/48124194-ad0c7480-e2b6-11e8-8845-26110d158a52.png)

**Comment by yangchaojiang** [comment]
你的studio 版本是多少

**Comment by xiaolongwuhpu** [comment]
我的mac  android studio 版本是3.2.1
引入的gralde 版本是你默认的3.1.4

**Comment by xiaolongwuhpu** [comment]
demo下载下来没有任何改动,自动build时报这个,弄一个多小时了,没找到出错原因

**Comment by jayxioresearch** [comment]
我也碰到了相同的问题，
macOS High Sierra (version 10.13.5)
Android Studio 3.2.1  
Build #AI-181.5540.7.32.5056338, built on October 8, 2018

JRE: 1.8.0_152-release-1136-b06x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

请问您的编译环境是怎样的？谢谢

**Comment by yangchaojiang** [comment]
把你jdk u喊一下。 不好意思 ，昨儿没有上班。

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/48236961-7beb8b80-e3ff-11e8-95d5-a4f539dd2383.png)

**Comment by yangchaojiang** [comment]
请不要使用自带open jdk
@xiaolongwuhpu @yangchaojiang @jayxioresearch

**Comment by xiaolongwuhpu** [comment]
大侠还是不行,已经切换成安装的jdk,默认jdk的路径是: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home,按照你说的,改成了下边图片的路径,还是一样的错误提示.
<img width="1283" alt="wechat48658e152a714561a6fe6b60b2c1bdc5" src="https://user-images.githubusercontent.com/13296347/48242394-f58e7400-e415-11e8-856a-fb8f7ed66752.png">

**Comment by yangchaojiang** [comment]
应该是代码上传插件报错。你这个删除就试试

**Comment by yangchaojiang** [comment]
在window 都是没问题的

**Comment by xiaolongwuhpu** [comment]
1.  注释这个   在 VideoPlayModule/build   49行   apply plugin: 'com.novoda.bintray-release'  报错,找不到这个插件.
2. 再注释这一行后,   报出 Could not find method publish() for arguments [build_ehwhno2gonrfmiombxc21m00t$_run_closure3@78d48eb1] on project ':VideoPlayModule' of type org.gradle.api.Project.

**Comment by yangchaojiang** [comment]
这个是我问题
DefaultMediaSourceEvent
删除就行了。抱歉这个之前测试用。发展实用性不高

**Comment by jayxioresearch** [comment]
谢谢@yangchaojiang， 删除了com.novoda:bintray-release:0.8.1相关引用，并参照已关闭的issue #206, 删除关于“DefaultMediaSourceEvent”的引用后，在Android Studio 3.1.4下可以成功运行（emulator),但是在Android Studio 3.2.1下遇到另一个错误：“error: cannot find symbol variable exo_download_notification_channel_name” in chuangyuan/yjplay/offline/DemoDownloadService.java. 谢谢

**Comment by yangchaojiang** [comment]
你重新clone 已经发布新版本了

**Comment by jayxioresearch** [comment]
谢谢。新版本我遇到了issue #208 中提到的问题。
