### ISSUE TITLE
Error when orientation change 

### ISSUE THREAD

**Issue by sakacyber** [yangchaojiang/yjPlay#207]
Version 2.3.11 or version 2.3.0
Error nullPointerException when screen orientation change on override method onDetachFromWindow() 

java.lang.NullPointerException: Attempt to invoke interface method 'chuangyuan.ycj.videolibrary.video.ExoUserPlayer chuangyuan.ycj.videolibrary.listener.ExoPlayerListener.getPlay()' on a null object reference
        at chuangyuan.ycj.videolibrary.widget.VideoPlayerView.onDetachedFromWindow(VideoPlayerView.java:157)

**Comment by yangchaojiang** [comment]
谢谢反馈。尽快修复的
