### ISSUE TITLE
增加广告视频预览切换，这个怎么使用呢

### ISSUE THREAD

**Issue by qinyang1018** [yangchaojiang/yjPlay#21]
我在demo没有看见有添加广告的，readme上也没有相关介绍，能否告知下应该怎么使用这个功能，谢谢了

**Comment by yangchaojiang** [comment]
这个setPlayUri（）方法是多参数的； 我注释了
exoPlayerManager.setPlayUri(String firstVideoUri, @NonNull String secondVideoUri)；

**Comment by qinyang1018** [comment]
好的  谢谢了
