### ISSUE TITLE
升级到2.3.12，手势没有了？

### ISSUE THREAD

**Issue by tmxd09887** [yangchaojiang/yjPlay#211]
版本 VideoPlayModule:2.3.12

查了下README
默认关闭手势 亮度，音量，快进，等手势
是默认关闭吗？

怎么打开？

`        exoPlayerManager = new VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_GESTURE, videoPlayerView)
                .setPlayerGestureOnTouch(true)
                .create();`

setPlayerGestureOnTouch 设置为true也没用啊

**Comment by yangchaojiang** [comment]
YO有的哦

**Comment by tmxd09887** [comment]
大佬，怎么打开啊？

**Comment by yangchaojiang** [comment]
你开始播放没

**Comment by yangchaojiang** [comment]
没有播放没有手势的

**Comment by tmxd09887** [comment]
已经开始播放了。

手势的意思是，用手势控制亮度和声音，还有快进吧。

现在没法控制啊

必须加这三个自定义layout吗？
` app:player_gesture_audio_layout_id="@layout/custom_gesture_audio"
        app:player_gesture_bright_layout_id="@layout/custom_gesture_brightness"
        app:player_gesture_progress_layout_id="@layout/custom_gesture_pro"`

**Comment by yangchaojiang** [comment]
你是使用自定义啊，没有效果，自己代码实现接口啊，自己实现哦。 删除就是默认的

**Comment by tmxd09887** [comment]
我不是自定义啊，好像你README说默认关闭手势啊

我之前低版本，有手势功能，现在没了啊。我并不是要自定义UI。

**Comment by yangchaojiang** [comment]
参考demo 把

**Comment by tmxd09887** [comment]
参考了DEMO，代码一样。

同样的代码VideoPlayModule:2.3.12和VideoPlayModule:2.3.11没有手势。VideoPlayModule:2.3.0有。

**Comment by yangchaojiang** [comment]
我测试都是有手势 的，检查你的文件是否指定自定义文件，还有代码是否实现接口。实现是不会走默认

**Comment by magicLanjie** [comment]
你的mOnTouchListener接口都没看到调用呢 手势确实不得行了

**Comment by magicLanjie** [comment]
手势确实没有了。也没看到demo 具体怎么实现的 能透露一下么

**Comment by yangchaojiang** [comment]
你可以参考代码，手势不要实现监听事件

**Comment by magicLanjie** [comment]
> 版本2.3.17 试一下。

好的 谢谢
