### ISSUE TITLE
大佬m3u8没法播放

### ISSUE THREAD

**Issue by huluxia** [yangchaojiang/yjPlay#212]
这是视频连接。测试其他的播放器还有腾讯x5都能播放，exo放不了。希望大佬看看

**Comment by huluxia** [comment]
https://url.cn/5BGAsbP

**Comment by yangchaojiang** [comment]
这种连接？？？

**Comment by yangchaojiang** [comment]
你的连接需要重定向把

**Comment by huluxia** [comment]
第二种也没法播放。

**Comment by yangchaojiang** [comment]
连接过其了。 再发一个，目前你连接大概率没有别识别出来了

**Comment by yangchaojiang** [comment]
[可以参考如何添加自定义识别连接](https://github.com/yangchaojiang/yjPlay/issues/204)

**Comment by huluxia** [comment]
我在线的时候博主又没在。最好能加我下我提供m3u8地址给您。我QQ1981770528

**Comment by yangchaojiang** [comment]
加你了
