### ISSUE TITLE
列表播放后进入详情页播放失败

### ISSUE THREAD

**Issue by silence17** [yangchaojiang/yjPlay#213]
看您的Demo，MainListActivity 列表进入到播放详情MainListInfoCustomActivity是自动播放。
我们项目需要进入详情的时候不自动播放，我把播放的代码注释了如下：
        if (exoPlayerManager == null) {
            exoPlayerManager = new VideoPlayerManager
                    .Builder(VideoPlayerManager.TYPE_PLAY_USER, playerView)
                    .setPosition(videoBean.getCurrentPosition())
                    .create();

            for (String key : videoBean.getMap().keySet()) {
                // TODO: 2018/3/1 可以切换不同分辨率
                exoPlayerManager.setPlayUri(videoBean.getMap().get(key));
            }
            // 隐藏控制布局
            exoPlayerManager.showControllerView();
//            exoPlayerManager.startPlayer();
        } else {
            VideoPlayerManager.getInstance().switchTargetViewNew(playerView);
            exoPlayerManager.setPosition(videoBean.getCurrentPosition());
//            exoPlayerManager.setStartOrPause(true);
        }
但运行后点击列表播放视频再进入详情页，点击播放按钮就没有反应不能播放了。麻烦帮忙看一下

**Comment by yangchaojiang** [comment]
谢谢你反馈问题，已经修复

**Comment by silence17** [comment]
好的，我试一下

**Comment by yangchaojiang** [comment]
我还没有提交尼

**Comment by silence17** [comment]
请问您计划什么时候提交，我们项目里需要修改这个bug

**Comment by yangchaojiang** [comment]
你们为什么不自动播放哦

**Comment by silence17** [comment]
我是商品详情页轮播图的第一页是视频，滑动到其他页是图片。
当点击图片查看大图左右滑动还能滑动到视频页，再次滑到视频的时候，产品要求视频不能自动播放。

**Comment by yangchaojiang** [comment]
哦哦哦

**Comment by yangchaojiang** [comment]
版本2.3.13

**Comment by silence17** [comment]
不好意思刚看到，没问题了

**Comment by yangchaojiang** [comment]
那我关闭了哦

**Comment by silence17** [comment]
嗯呢，没问题
