### ISSUE TITLE
默认不播放总时间不显示，集成的版本号：VideoPlayModule-Lite:2.3.13

### ISSUE THREAD

**Issue by silence17** [yangchaojiang/yjPlay#217]
你好，请问进入播放详情默认不播放。视频总长度不能正确获取到总是显示00:00.

默认不播放，想隐藏进度条、时间信息和全选按钮等。但是调用如下方法连播放按钮都隐藏了
                       // 隐藏控制布局
                        exoPlayerManager.hideControllerView();
播放按钮的显示需要自家控制吗

**Comment by yangchaojiang** [comment]
推荐你的接口提供

**Comment by yangchaojiang** [comment]
，加载之前不提供，都是接口获取的
