### ISSUE TITLE
Fragment中 list列表播放，点击全屏后，再点击左上角返回，就会退出整个应用而不是返回到list列表中

### ISSUE THREAD

**Issue by RookieExaminer** [yangchaojiang/yjPlay#22]
使用版本   compile 'com.ycjiang:VideoPlayModule:1.5.7.2'

Fragment中 list列表播放，点击全屏后，再点击左上角返回，就会退出整个应用而不是返回到list列表中。

![img_20171018_150459](https://user-images.githubusercontent.com/23047162/31704949-1924e056-b416-11e7-9aae-a23f437e6687.jpg)

**Comment by yangchaojiang** [comment]
请看看使用说明0 
点击
https://github.com/yangchaojiang/yjPlay#三列表

**Comment by yangchaojiang** [comment]
管理fragment的actvity 实现onBackPressed（）；

**Comment by RookieExaminer** [comment]
可以了 谢谢 非常感谢

**Comment by yangchaojiang** [comment]
记得 star 支持， fork  🤣🤣🤣🤣🤣

**Comment by RookieExaminer** [comment]
好的

**Comment by RookieExaminer** [comment]
刚刚上下滑动报错
java.lang.NullPointerException: Attempt to invoke interface method 'void chuangyuan.ycj.videolibrary.listener.ExoPlayerViewListener.setControllerHideOnTouch(boolean)' on a null object reference
这两个我是定义的全局变量，然后初始化的时候再new出来。
  private VideoPlayerView playerView;
    private ManualPlayer userPlayer;

// convert
 playerView = (VideoPlayerView) helper.getView(R.id.exo_play_context_id_video);
                playerView.setLayoutParams(layoutParamsVideo);
                userPlayer = new ManualPlayer((Activity) mContext, playerView);
                userPlayer.setTitle(item.getGroup().getText());
                userPlayer.setPlayUri(item.getGroup().getMp4_url());

**Comment by RookieExaminer** [comment]
这样每次进来加载布局就一个新的类 会不会太耗费资源什么的了
// convert ViewHolder
VideoPlayerView playerView = (VideoPlayerView) helper.getView(R.id.exo_play_context_id_video);
ManualPlayer userPlayer = new ManualPlayer((Activity) mContext, playerView);
userPlayer.setTitle(item.getGroup().getText());
userPlayer.setPlayUri(item.getGroup().getMp4_url());

**Comment by yangchaojiang** [comment]
i你看代码你操作的，都是在onbingViewHolde 执行的
看一下demo adapter new 的操作 领尽量放在 creVewiHolder  不要在onbingViewHolde。onbingViewHolde 是只是赋值

**Comment by RookieExaminer** [comment]
我是用第三方的adapter库BRVAH http://www.jianshu.com/p/b343fcff51b0
设置在creVewiHolder 里也报错
![6 v 2 eg9e7h x9 o9b](https://user-images.githubusercontent.com/23047162/31706599-0f3439ce-b41c-11e7-8468-388771c66f08.png)

**Comment by RookieExaminer** [comment]
出现的原因是 我点击视频播放按钮。然后快速下滑列表

**Comment by yangchaojiang** [comment]
有由于视频泪飙有特殊性， BRVAH convert（）方法的回调都在onbindViewHodel 执行的
会实例话频繁，
看你BRVAH 的adapter  onCreateViewHoder

**Comment by RookieExaminer** [comment]
//太长了，加载视频的在最下面
    @Override
    protected void convert(BaseViewHolder helper, SatinsBean.DataBeanX.DataBean item) {

        switch (helper.getItemViewType()) {
            case TEXT:

                //加载头像
                String urlIconTEXT = item.getGroup().getUser().getAvatar_url();
                GlideUtils.loadIcon(mContext, urlIconTEXT, (ImageView) helper.getView(R.id.mPortrait_homepage_text));

                helper
                        .setText(R.id.mName_homepage_text, item.getGroup().getUser().getName() + "")//名字
                        .setText(R.id.mContent_homepage_text, item.getGroup().getText() + "")           //内容
                        .setText(R.id.mCategory_homepage_text, item.getGroup().getCategory_name() + "") //类别
                        .setText(R.id.mDigg_count_homepage_text, item.getGroup().getDigg_count() + "")  //点赞数量
                        .setText(R.id.mBury_count_homepage_text, item.getGroup().getBury_count() + "") //不顶次数
                        .setText(R.id.mComment_count_homepage_text, item.getGroup().getComment_count() + "") //评论数量
                        .setText(R.id.mShare_count_homepage_text, item.getGroup().getShare_count() + "") //转发次数

                ;

                /*加载热评*/
                if (item.getComments().size() != 0) {
                    for (int i = 0; i < item.getComments().size(); i++) {
                        //加载热评头像
                        String urlIconCommentsTEXT = item.getComments().get(i).getAvatar_url();
                        GlideUtils.loadIcon(mContext, urlIconCommentsTEXT, (ImageView) helper.getView(R.id.mPortrait_comments_homepage_text));

                        helper.setText(R.id.mName_comments_homepage_text, item.getComments().get(i).getUser_name() + "") //热评名字
                                .setText(R.id.mDiggs_count_comments_homepage_text, item.getComments().get(i).getDigg_count() + "")//点赞数量
                                .setText(R.id.mContent_comments_homepage_text, item.getComments().get(i).getText() + ""); //热评内容

                    }

                } else {
                    //隐藏mLinearLayout 因为热评没数据
                    helper.getView(R.id.mLinearLayout_homepage_text).setVisibility(View.GONE);
                }

                break;
            case IMG:
                helper
                        .setText(R.id.mName_homepage_img, item.getGroup().getUser().getName() + "") //名字
                        .setText(R.id.mContent_homepage_img, item.getGroup().getText() + "")           //内容
                        .setText(R.id.mCategory_homepage_img, item.getGroup().getCategory_name() + "") //类别
                        .setText(R.id.mDigg_count_homepage_img, item.getGroup().getDigg_count() + "")  //点赞数量
                        .setText(R.id.mBury_count_homepage_img, item.getGroup().getBury_count() + "") //不顶次数
                        .setText(R.id.mComment_count_homepage_img, item.getGroup().getComment_count() + "") //评论数量
                        .setText(R.id.mShare_count_homepage_img, item.getGroup().getShare_count() + ""); //转发次数
                //头像链接
                String urlIconIMG = item.getGroup().getUser().getAvatar_url();
                //加载头像
                GlideUtils.loadIcon(mContext, urlIconIMG, (ImageView) helper.getView(R.id.mPortrait_homepage_img));

                /**
                 * urlImageIMG 图片链接
                 * getLarge_image 大图
                 * getMiddle_image 中等图
                 */
                String urlImageIMG = item.getGroup().getLarge_image().getUri();
                int width = item.getGroup().getLarge_image().getR_width();
                int height = item.getGroup().getLarge_image().getR_height();

                //加载内容图片
                GlideUtils.loadImage(mContext, Constant.URLIMAGE + urlImageIMG, (ImageView) helper.getView(R.id.mImage_homepage_img), width, height);

                //加载热评
                if (item.getComments().size() != 0) {
                    for (int i = 0; i < item.getComments().size(); i++) {

                        //加载热评头像
                        String urlIconCommentsIMG = item.getComments().get(i).getAvatar_url();
                        GlideUtils.loadIcon(mContext, urlIconCommentsIMG, (ImageView) helper.getView(R.id.mPortrait_comments_homepage_img));
                        LogUtils.d(TAG, "热评名字   " + item.getComments().get(i).getUser_name() + "    热评头像     " + urlIconCommentsIMG);
                        helper.setText(R.id.mName_comments_homepage_img, item.getComments().get(i).getUser_name() + "") //热评名字
                                .setText(R.id.mDiggs_count_comments_homepage_img, item.getComments().get(i).getDigg_count() + "")//点赞数量
                                .setText(R.id.mContent_comments_homepage_img, item.getComments().get(i).getText() + ""); //热评内容

                    }

                } else {
                    //隐藏mLinearLayout 因为热评没数据
                    helper.getView(R.id.mLinearLayout_homepage_img).setVisibility(View.GONE);
                }
                /**
                 *点击事件
                 */
                helper.addOnClickListener(R.id.mImage_homepage_img);
                break;
            case GIF:
                helper
                        .setText(R.id.mName_homepage_gif, item.getGroup().getUser().getName() + "") //名字
                        .setText(R.id.mContent_homepage_gif, item.getGroup().getText() + "")           //内容
                        .setText(R.id.mCategory_homepage_gif, item.getGroup().getCategory_name() + "") //类别
                        .setText(R.id.mDigg_count_homepage_gif, item.getGroup().getDigg_count() + "")  //点赞数量
                        .setText(R.id.mBury_count_homepage_gif, item.getGroup().getBury_count() + "") //不顶次数
                        .setText(R.id.mComment_count_homepage_gif, item.getGroup().getComment_count() + "") //评论数量
                        .setText(R.id.mShare_count_homepage_gif, item.getGroup().getShare_count() + ""); //转发次数

                //头像链接
                String urlIconGif = item.getGroup().getUser().getAvatar_url();
                //加载头像
                GlideUtils.loadIcon(mContext, urlIconGif, (ImageView) helper.getView(R.id.mPortrait_homepage_gif));

                /**
                 * urlImageGif 图片链接
                 * getLarge_image 大图 动态图
                 * getMiddle_image 中等图 静态图
                 */
                //静态显示，点击后再动态显示
                String urlImageGif = item.getGroup().getMiddle_image().getUri();
                int widthGif = item.getGroup().getLarge_image().getR_width();
                int heightGif = item.getGroup().getLarge_image().getR_height();
                RelativeLayout.LayoutParams layoutParamsGif = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, DensityUtils.dp2px(mContext, heightGif));
                ImageView mImageViewGif = helper.getView(R.id.mImage_homepage_gif);
                layoutParamsGif.setMargins(0, 10, 0, 0);
                mImageViewGif.setLayoutParams(layoutParamsGif);
                //加载图片
                GlideUtils.loadImage(mContext, Constant.URLIMAGE + urlImageGif, mImageViewGif);

                LogUtils.d(TAG + "A", "            " + Constant.URLIMAGE + urlImageGif);
                   /*加载热评*/
                if (item.getComments().size() != 0) {
                    for (int i = 0; i < item.getComments().size(); i++) {

                        //加载热评头像
                        String urlIconCommentsIMG = item.getComments().get(i).getAvatar_url();
                        GlideUtils.loadIcon(mContext, urlIconCommentsIMG, (ImageView) helper.getView(R.id.mPortrait_comments_homepage_gif));
                        LogUtils.d(TAG, "热评名字   " + item.getComments().get(i).getUser_name() + "    热评头像     " + urlIconCommentsIMG);
                        helper.setText(R.id.mName_comments_homepage_gif, item.getComments().get(i).getUser_name() + "") //热评名字
                                .setText(R.id.mDiggs_count_comments_homepage_gif, item.getComments().get(i).getDigg_count() + "")//点赞数量
                                .setText(R.id.mContent_comments_homepage_gif, item.getComments().get(i).getText() + ""); //热评内容

                    }

                } else {
                    //隐藏mLinearLayout 因为热评没数据
                    helper.getView(R.id.mLinearLayout_homepage_gif).setVisibility(View.GONE);
                }
                /**
                 * 点击事件
                 */
                helper.addOnClickListener(R.id.mImage_homepage_gif);
                break;
            case VIDEO:
               /* **************************************加载视频**********************************/
                //  int widthVideo  =item.getGroup().getVideo_width();
                int HeightVideo = item.getGroup().getVideo_height();
                RelativeLayout.LayoutParams layoutParamsVideo = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, HeightVideo);
                VideoPlayerView playerView = helper.getView(R.id.exo_play_context_id_video);
                playerView.setLayoutParams(layoutParamsVideo);
                ManualPlayer userPlayer = new ManualPlayer((Activity) mContext, playerView);
                userPlayer.setTitle(item.getGroup().getText());
                userPlayer.setPlayUri(item.getGroup().getMp4_url());

                break;
            default:
        }
    }

**Comment by yangchaojiang** [comment]
大兄弟 你的赋值你不能new A   你操作是convert里。  重写的onCreateViewHolder（）；

**Comment by yangchaojiang** [comment]
给你一个实例

**Comment by yangchaojiang** [comment]
BRVAH  相互要处理一下

**Comment by yangchaojiang** [comment]
public class BRVAHTestAdapter extends BaseQuickAdapter<String, BRVAHTestAdapter.TestVideoHolder> {
    private Context context;
    public BRVAHTestAdapter(Context context) {
        super(R.layout.item_video1);
        this.context = context;
    }
    @Override
    protected void convert(TestVideoHolder helper, String item) {
        helper.userPlayer.setTitle("" + helper.getAdapterPosition());
        helper.userPlayer.setPlayUri(item);
        Glide.with(context).
                load("http://i3.letvimg.com/lc08_yunzhuanma/201707/29/20/49/3280a525bef381311b374579f360e80a_v2_MTMxODYyNjMw/thumb/2_960_540.jpg")
                .placeholder(R.mipmap.test)
                .into(helper.playerView.getPreviewImage());
    }
    @Override
    protected TestVideoHolder createBaseViewHolder(ViewGroup parent, int layoutResId) {
        return super.createBaseViewHolder(parent, layoutResId);
    }

    class TestVideoHolder extends BaseViewHolder {
        ManualPlayer userPlayer;
        VideoPlayerView playerView;
        View itemView;

        public TestVideoHolder(View view) {
            super(view);
            playerView = (VideoPlayerView) view.findViewById(R.id.item_exo_player_view);
            itemView = view;
            userPlayer = new ManualPlayer((Activity) context, playerView);
        }


    }

**Comment by yangchaojiang** [comment]
public class BRVAHTestAdapter extends BaseQuickAdapter<String, BRVAHTestAdapter.TestVideoHolder> {
private Context context;
public BRVAHTestAdapter(Context context) {
super(R.layout.item_video1);
this.context = context;
}
@override
protected void convert(TestVideoHolder helper, String item) {
helper.userPlayer.setTitle("" + helper.getAdapterPosition());
helper.userPlayer.setPlayUri(item);
Glide.with(context).
load("http://i3.letvimg.com/lc08_yunzhuanma/201707/29/20/49/3280a525bef381311b374579f360e80a_v2_MTMxODYyNjMw/thumb/2_960_540.jpg")
.placeholder(R.mipmap.test)
.into(helper.playerView.getPreviewImage());
}
@override
protected TestVideoHolder createBaseViewHolder(ViewGroup parent, int layoutResId) {
return super.createBaseViewHolder(parent, layoutResId);
}

class TestVideoHolder extends BaseViewHolder {
    ManualPlayer userPlayer;
    VideoPlayerView playerView;
    View itemView;

    public TestVideoHolder(View view) {
        super(view);
        playerView = (VideoPlayerView) view.findViewById(R.id.item_exo_player_view);
        itemView = view;
        userPlayer = new ManualPlayer((Activity) context, playerView);
    }
}
需要自己处理一下

**Comment by RookieExaminer** [comment]
好的 谢谢了

**Comment by yangchaojiang** [comment]
可以了么

**Comment by RookieExaminer** [comment]
不行。 滑动报错。 
代码我是这样设置的：
             helper.textView.setText("厉害了");
                helper.userPlayer.setTitle(item.getGroup().getText());
                helper.userPlayer.setPlayUri(item.getGroup().getMp4_url());
                break;
            default:
        }
    }

    public class SatinViewHolder extends BaseViewHolder {
        ManualPlayer userPlayer;
        VideoPlayerView playerView;
        View itemView;
        TextView textView;

        public SatinViewHolder(View view) {
            super(view);
            itemView = view;
            textView = (TextView) view.findViewById(R.id.mCategory_homepage_video);
            playerView = (VideoPlayerView) view.findViewById(R.id.exo_play_context_id_video);
            userPlayer = new ManualPlayer((Activity) mContext, playerView);
        }

    }
只用设置textView的时候可以 
设置视频 滑动报错
 Process: test.azheng.pers.satin, PID: 30343
                                                                        java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to test.azheng.pers.satin.adapter.SatinAdapter$SatinViewHolder
                                                                            at test.azheng.pers.satin.adapter.SatinAdapter.convert(SatinAdapter.java:35)
                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:882)
                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                            at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                            at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                            at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                            at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                            at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                            at android.os.Handler.handleCallback(Handler.java:742)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by yangchaojiang** [comment]
兄弟看错误哦，明显是类转化错误哦，一个BaseViewHolder 一个SatinViewHolder  改成你你用viewHoder 哦

**Comment by RookieExaminer** [comment]
有点不懂啊 我上面用的自己的定义的
public class SatinAdapter extends BaseMultiItemQuickAdapter<SatinsBean.DataBeanX.DataBean, SatinAdapter.SatinViewHolder> {
 public static class SatinViewHolder extends BaseViewHolder {


        ManualPlayer userPlayer;
        VideoPlayerView playerView;
        View itemView;
        TextView textView;

        public SatinViewHolder(View view) {
            super(view);
            itemView = view;
            textView = (TextView) view.findViewById(R.id.mCategory_homepage_video);
            playerView = (VideoPlayerView) view.findViewById(R.id.exo_play_context_id_video);
            userPlayer = new ManualPlayer((Activity) itemView.getContext(), playerView);
        }

    }
}
