### ISSUE TITLE
导了项目之后报各种找不到 VideoPlayModle 和 Lite 中的类什么情况啊 求回复

### ISSUE THREAD

**Issue by 545554466** [yangchaojiang/yjPlay#221]
![y 9hfce j 38d3 qed5hv n](https://user-images.githubusercontent.com/44362275/49281367-582fd880-f4c7-11e8-840b-6e6f8d93f38d.png)
这是为什么啊大佬？APP和 tv 都报这种错误

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/49283517-e8bce780-f4cc-11e8-94ef-c4fa364b1945.png)

**Comment by yangchaojiang** [comment]
是否引用

**Comment by yangchaojiang** [comment]
是否项目导入成功么

**Comment by 545554466** [comment]
导入成功了啊？和你图片上面的是一样的。

**Comment by yangchaojiang** [comment]
图片那个是建立关系

**Comment by 545554466** [comment]
需要做什么吗？不是很懂。麻烦说的的详细点呗！谢谢。

**Comment by yangchaojiang** [comment]
....参考demo

**Comment by 545554466** [comment]
额！好把。谢谢了。
