### ISSUE TITLE
ffmpeg extension support for exoplayer.

### ISSUE THREAD

**Issue by zhangabvc** [yangchaojiang/yjPlay#222]
Exoplayer cannot play Audio-mpg2 format.So add ffmpeg to support some audio format.
To perform according to this url https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg
But cannot use ffmpeg.
do as follows:
COMMON_OPTIONS="
--target-os=android
--disable-static
--enable-shared
--disable-doc
--disable-programs
--disable-everything
--disable-avdevice
--disable-avformat
--disable-swscale
--disable-postproc
--disable-avfilter
--disable-symver
--disable-swresample
--enable-avresample
--enable-decoder=vorbis
--enable-decoder=opus
--enable-decoder=ffmpeg
--enable-decoder=flac
" &&
cd "${FFMPEG_EXT_PATH}/jni" &&
(git -C ffmpeg pull || git clone git://source.ffmpeg.org/ffmpeg ffmpeg) &&
cd ffmpeg && git checkout release/4.0 &&
./configure
--libdir=android-libs/armeabi-v7a
--arch=arm
--cpu=armv7-a
--cross-prefix="${NDK_PATH}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_PLATFORM}/bin/arm-linux-androideabi-"
--sysroot="${NDK_PATH}/platforms/android-9/arch-arm/"
--extra-cflags="-march=armv7-a -mfloat-abi=softfp"
--extra-ldflags="-Wl,--fix-cortex-a8"
--extra-ldexeflags=-pie
${COMMON_OPTIONS}
&&
make -j4 && make install-libs &&
make clean && ./configure
--libdir=android-libs/arm64-v8a
--arch=aarch64
--cpu=armv8-a
--cross-prefix="${NDK_PATH}/toolchains/aarch64-linux-android-4.9/prebuilt/${HOST_PLATFORM}/bin/aarch64-linux-android-"
--sysroot="${NDK_PATH}/platforms/android-21/arch-arm64/"
--extra-ldexeflags=-pie
${COMMON_OPTIONS}
&&
make -j4 && make install-libs &&
make clean && ./configure
--libdir=android-libs/x86
--arch=x86
--cpu=i686
--cross-prefix="${NDK_PATH}/toolchains/x86-4.9/prebuilt/${HOST_PLATFORM}/bin/i686-linux-android-"
--sysroot="${NDK_PATH}/platforms/android-9/arch-x86/"
--extra-ldexeflags=-pie
--disable-asm
${COMMON_OPTIONS}
&&
make -j4 && make install-libs

cd "${FFMPEG_EXT_PATH}"/jni &&
${NDK_PATH}/ndk-build APP_ABI="armeabi-v7a arm64-v8a" -j4

Finally generated like this libavcodec.so libavresample.so libavutil.so libffmpeg.so for arm64v8.

Modify code on DefaultRenderersFactory.java
@deprecated
public DefaultRenderersFactory(
Context context,
@nullable DrmSessionManager drmSessionManager,
@ExtensionRendererMode int extensionRendererMode,
long allowedVideoJoiningTimeMs) {
this.context = context;
this.extensionRendererMode = EXTENSION_RENDERER_MODE_PREFER ; //Modified
//this.extensionRendererMode = extensionRendererMode; //old
this.allowedVideoJoiningTimeMs = allowedVideoJoiningTimeMs;
this.drmSessionManager = drmSessionManager;
}

**Comment by yangchaojiang** [comment]
ffmpeg  类库给你生成好的。注意查看

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/49483428-1491f180-f86e-11e8-88c1-c785d9d3fa3a.png)

**Comment by yangchaojiang** [comment]
我已经生成好的so.文件。自己引用就行了

**Comment by zhangabvc** [comment]
> 我已经生成好的so.文件。自己引用就行了

怎么引用，总是显示没找到

**Comment by yangchaojiang** [comment]
项目下载下来。依赖的ffmpeg 那个module

**Comment by zhangabvc** [comment]
> 项目下载下来。依赖的ffmpeg 那个module

implementation project(':extension-ffmpeg')
这样吗

**Comment by yangchaojiang** [comment]
是的。

**Comment by zhangabvc** [comment]
> 不是引用的exoplater 是引用我项目的ffmpeg的module,.
> 
> ```
>     implementation project(':ffmpeg')
> ```
你的工程我还没下载下来，59M,经常断。

**Comment by zhangabvc** [comment]
我上传到这里，http://file.yiyuen.com/detail.html?id=999

**Comment by yangchaojiang** [comment]
我现在项目已经很小了。现在是22m的。 图片我已经迁移另一个项目上。

**Comment by yangchaojiang** [comment]
你使用exoplayer 的项目 拓展 。google 帮你生成so文件的。还有版本是否已知问题的。我已经没有问题，可以播放了

**Comment by zhangabvc** [comment]
你上传到这里 http://file.yiyuen.com/index.html，告诉我链接

**Comment by zhangabvc** [comment]
> 你使用exoplayer 的项目 拓展 。google 帮你生成so文件的。还有版本是否已知问题的。我已经没有问题，可以播放了
有声音吗

**Comment by yangchaojiang** [comment]
打错。google 不会帮你生成so文件的

**Comment by yangchaojiang** [comment]
进度已经正确读取的。 没有听到。检查你的文件。

**Comment by zhangabvc** [comment]
> 进度已经正确读取的。 没有听到。检查你的文件。

你能帮我修改我的工程吗

**Comment by yangchaojiang** [comment]
你给我的文件.ts 后缀名 ，。苦笑

**Comment by zhangabvc** [comment]
> 你给我的文件.ts 后缀名 ，。苦笑

ts 流也可以直接播放

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/49490690-166aad80-f88c-11e8-9617-e49e13d69260.png)

**Comment by yangchaojiang** [comment]
是可以播放的

**Comment by zhangabvc** [comment]
> 是可以播放的
一直正常播放，但音频格式是mpeg2，目前exoplayer没有声音。要加入ffmpeg才能播出声音

**Comment by yangchaojiang** [comment]
厉害了

**Comment by zhangabvc** [comment]
> 厉害了

能听到声音吗

**Comment by yangchaojiang** [comment]
我用window 下载mpeg2的解码器，才看到视频的

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/49496054-d7465780-f89f-11e8-845d-e9685451edb4.png)
我看了一下。google说明 文档不支持哦

**Comment by yangchaojiang** [comment]
[https://google.github.io/ExoPlayer/supported-formats.html](https://google.github.io/ExoPlayer/supported-formats.html)

**Comment by zhangabvc** [comment]
> 我用window 下载mpeg2的解码器，才看到视频的

我现在需要在exoplayer 上实现对mpeg2的支持.所以发的加入ffmpeg

**Comment by zhangabvc** [comment]
![888888](https://user-images.githubusercontent.com/44994911/49496165-35733a80-f8a0-11e8-9762-c5cc5801dad7.jpg)

**Comment by yangchaojiang** [comment]
拓展也没有的你要格式哦

**Comment by zhangabvc** [comment]
> 拓展也没有的你要格式哦
感觉并没有把ffmpeg加入进去，所以播放没有音频
我参考的这个，我的库也已经生成，但调用并没有出现，没有出现 load ffmpeg
https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/49498447-0eb80280-f8a6-11e8-8dd5-7daa400173c1.png)
放弃了

**Comment by zhangabvc** [comment]
> ![default](https://user-images.githubusercontent.com/13806413/49498447-0eb80280-f8a6-11e8-8dd5-7daa400173c1.png)
> 放弃了

哪里不对

**Comment by zhangabvc** [comment]
怎么加入ffmpeg

**Comment by yangchaojiang** [comment]
没有你的格式啊

**Comment by zhangabvc** [comment]
> 没有你的格式啊

mpga,mpga_l2, mpge-2,  是同一种格式，你上面的
![image](https://user-images.githubusercontent.com/44994911/49501098-17f89d80-f8ad-11e8-94fc-afc8a219d878.png)

**Comment by zhangabvc** [comment]
我觉得ffmpeg没导入成功

**Comment by yangchaojiang** [comment]
//////不不知道了。。。

**Comment by zhangabvc** [comment]
> 你说可以试一下 exoplayer 原生的库

怎么弄

**Comment by yangchaojiang** [comment]
[https://github.com/google/ExoPlayer](https://github.com/google/ExoPlayer)

**Comment by zhangabvc** [comment]
> https://github.com/google/ExoPlayer

我就是按原生的exoplayer 基础上实现 添加ffmpeg，但感觉没有成功，这是我的工程http://file.yiyuen.com/detail.html?id=999

**Comment by zhangabvc** [comment]
找到方法了吗

**Comment by zhangabvc** [comment]
https://github.com/google/ExoPlayer/issues/5154#issuecomment-443168475
你看看能不能从这里得到启示

**Comment by ghost0906** [comment]
我想请问下，我是在exoplayer的原工程上编译的，extensions下面把ffmpeg已经编译成功了，该如何将extension-ffmpeg导入到demo和library中使用？目前碰到的问题是class not found，找不到FfmpegAudioRenderer类 @zhangabvc

**Comment by yangchaojiang** [comment]
@ghost0906 FfmpegAudioRenderer 引用路径不能改的，要保留google包名路径，的google 源码是写死了
