### ISSUE TITLE
从播放详情返回到fragment播放列表，画面暂停了但是声音还会从头开始播放一遍。VideoPlayModule-Lite:2.3.13

### ISSUE THREAD

**Issue by silence17** [yangchaojiang/yjPlay#223]
Demo中从播放详情（播放中的状态）返回到fragment播放列表，画面暂停了但是声音还会从头开始播放一遍。VideoPlayModule-Lite:2.3.13

**Comment by silence17** [comment]
好的，您还没提交代码哈

**Comment by silence17** [comment]
我下载最新的demo，还是有这个问题呢

**Comment by silence17** [comment]
我下载了2.3.15仍然有问题，能否说明一下怎么修改。因为项目今天就发版比较着急  多谢

**Comment by yangchaojiang** [comment]
看你代码 哪里和demo 一样啊。给回调处理没

**Comment by yangchaojiang** [comment]
这个控制。不是类库实现。是在自己demo实现。配合的实现。

**Comment by silence17** [comment]
我参考的Demo 中ListFragmentActivity--->ClassFragment的视频列表，就有这个问题呢

**Comment by yangchaojiang** [comment]
不好意思。ListFragmentActivity没有实现列表和关联详情播放关联。
 看。manListActivitty.

**Comment by silence17** [comment]
好的，多谢

**Comment by yangchaojiang** [comment]
你看代码知道。没有实现返回结果的。

**Comment by silence17** [comment]
不好意思，您能说明一下是哪个控制吗？我没找到跟我的代码有什么区别呢

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/49495707-df51c780-f89e-11e8-8600-e70f17594aee.png)

**Comment by silence17** [comment]
多谢多谢。我也这样做了，检查了半天才发现我列表页没有视频的时候，详情页没有释放的原因

**Comment by yangchaojiang** [comment]
好的。，解决问题就行，谢谢支持

**Comment by silence17** [comment]
但是还有一个问题，调用VideoPlayerManager.getInstance().switchTargetViewResult(videoPlayerView, currentPosition, false);
这个方法我的一级页面的播放view和二级页面播放的view，必须是同一个视频。我现在是两个页面是不同的视频，用这个方法不能解决我从fragment返回activity后声音一直在播放的问题。还烦请您看一下
