### ISSUE TITLE
Black Screen for player .

### ISSUE THREAD

**Issue by phamdinhhai0810** [yangchaojiang/yjPlay#224]
Hello Yangchaojiang.
I have a error. i put player into Frame Layout height: 200dp.
When player start. It show black screen. Touch screen only show controller. But when i click fullscreen button. Player can show video ( black screen moved). I only use normal code like that:    
exoPlayerManager = new VideoPlayerManager.Builder(this, VideoPlayerManager.TYPE_PLAY_GESTURE, R.id.exo_play_context_id)
                .setDataSource(new DataSource(this)) ....
Can u help me for this black screen ? Thank you.

**Comment by yangchaojiang** [comment]
Hello, check if you play audio or video.

Provide your version for use

**Comment by phamdinhhai0810** [comment]
I use 2.3.12, 2.3.13, 2.3.14.  as i said before. its is black screen until i click fullscreen button on bottom right player

**Comment by phamdinhhai0810** [comment]
Thanks for support. i resolved it.
