### ISSUE TITLE
运行demo出错

### ISSUE THREAD

**Issue by shegang** [yangchaojiang/yjPlay#227]
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;
我使用的是 ：classpath 'com.android.tools.build:gradle:3.2.1'
：classpath 'com.novoda:bintray-release:0.8.1'

compileSdkVersion=26
targetSdkVersion=26
 buildToolsVersion='28.0.3'

**Comment by yangchaojiang** [comment]
buildToolsVersion='28.0.3'
改成26吧

**Comment by yangchaojiang** [comment]
buildToolsVersion='28.0.3'
改成26吧

**Comment by yangchaojiang** [comment]
还有运行260Android studio.的推荐在3.0以上
