### ISSUE TITLE
请问，视频播放的时候点击暂停播放，再重新点击播放视频总是从开头重新开始播放

### ISSUE THREAD

**Issue by silence17** [yangchaojiang/yjPlay#229]
你好，请问视频播放的时候点击暂停播放，再重新点击播放视频总是从开头重新开始播放。
我试了一下您的Demo在MainListActivity、MainDetailedActivity中也有这个问题，请问您有解决方案吗。多谢

**Comment by abaiweb** [comment]
我也遇到了  也不能集成修改。。。。

**Comment by yangchaojiang** [comment]
操作已经内部处理好。自己不用关心哦

**Comment by flute00** [comment]
预览apk中同样问题

**Comment by yy197133** [comment]
> 操作已经内部处理好。自己不用关心哦

现在问题是没处理好...每次都是从头播放

**Comment by yangchaojiang** [comment]
版本是最新吗

**Comment by yy197133** [comment]
> 版本是最新吗

版本是2.3.17，最新的

**Comment by yy197133** [comment]
> 不好意思。这个月加班多，赶项目, 耽搁修复问题。版本修复 2.3.20
> @silence17 @abaiweb @yangchaojiang @flute00 @yy197133

您别这么客气，我们这是用你的项目，你能抽出空来修复，我们很感谢你~这个项目有很多值得我学习的地方，多谢大佬~
