### ISSUE TITLE
执行 ManualPlayer.reset();的时候提示错误

### ISSUE THREAD

**Issue by aipaw** [yangchaojiang/yjPlay#23]
执行 ManualPlayer.reset();的时候提示错误

![image](https://user-images.githubusercontent.com/19816319/31776307-c0cd9c86-b4b0-11e7-8d4d-e6c1dfb38225.png)

**Comment by aipaw** [comment]
然后过一会手机就发烫了

**Comment by yangchaojiang** [comment]
1.5.73分支已修复

**Comment by yangchaojiang** [comment]
7.3中间有个点

**Comment by aipaw** [comment]
(*@ο@*) 哇～，那么快就修复啦

**Comment by yangchaojiang** [comment]
嘿嘿，处理逻顺序问题，但不影响线哦，之前有人反馈哈，用qq😁😁😁

**Comment by aipaw** [comment]
7.3什么时候开源啊

**Comment by yangchaojiang** [comment]
主项目dev 分支
