### ISSUE TITLE
从详情页返回Fragment列表页报错

### ISSUE THREAD

**Issue by wq120695260** [yangchaojiang/yjPlay#231]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean chuangyuan.ycj.videolibrary.listener.ExoPlayerViewListener.isList()' on a null object reference

**Comment by yangchaojiang** [comment]
你使用版本事？代码是否参考demo 实现？

**Comment by wq120695260** [comment]
你好！如何监听是否播放那个弹出框的“确定”，“取消”按钮

**Comment by yangchaojiang** [comment]
目前没有哦。后续版本可以
