### ISSUE TITLE
实例化exoPlayerManager时添加了addUpdateProgressListener，全屏后监听失效

### ISSUE THREAD

**Issue by xiaozou00123** [yangchaojiang/yjPlay#235]
实例化exoPlayerManager时添加了addUpdateProgressListener，不点击全屏，监听是有效的。点击全屏后监听失效

        //实例化
        exoPlayerManager = new VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_MANUAL, videoPlayerView)
                .setDataSource(new OfficeDataSource(this,null))
                //设置视频标题
                .setTitle(data.getContent_title_name())
                //设置水印图
                .setExoPlayWatermarkImg(R.mipmap.ic_launcher)
                .setPlayerGestureOnTouch(true)
                .setPlayUri(playvediourl)
                .addUpdateProgressListener(new AnimUtils.UpdateProgressListener() {
                    @Override
                    public void updateProgress(long Position, long bufferedPosition, long duration) {
                        Log.d(TAG,"Position:"+Position);
                        Log.d(TAG,"bufferedPosition:"+bufferedPosition);
                        Log.d(TAG,"duration:"+duration);

                        if (Position>10*1000){
                            exoPlayerManager.seekTo(0);
                            exoPlayerManager.onPause();
                        }
                    }
                })

是我的方法错误吗

**Comment by yangchaojiang** [comment]
你好，你适用版本那个，不好意思，过年前，事多没有注意哈
