### ISSUE TITLE
使用的时候没有ManualPlayer这个类

### ISSUE THREAD

**Issue by cutesariki** [yangchaojiang/yjPlay#241]
看了好多地方的使用方法都有用到manualplayer这个东西，但是并没有这个

**Comment by cutesariki** [comment]
请问解析rtmp链接是需要额外添加协议吗？

**Comment by yangchaojiang** [comment]
是的
  compile 'com.google.android.exoplayer:extension-rtmp:2.9.5'
然后[使用点击查看](https://github.com/yangchaojiang/yjPlay/blob/master/app/src/main/java/chuangyuan/ycj/yjplay/data/DataSource.java)

**Comment by cutesariki** [comment]
点击视频全屏按钮后视频只会占满fragment而不是整个屏幕，这是因为我使用了列表模式吗？

**Comment by yangchaojiang** [comment]
参考一下demo 的fragment

**Comment by cutesariki** [comment]
全屏加载时无法点击播放器呼出控制器来返回列表，这个有什么方法解决吗

**Comment by yangchaojiang** [comment]
你可以拿到布局文件，实现监听功能！点击返回
