### ISSUE TITLE
点击全屏按钮，只全屏不横竖屏切换

### ISSUE THREAD

**Issue by miniframework** [yangchaojiang/yjPlay#246]
<activity android:name=".videoActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="landscape"
  ></activity>

想点全屏按钮只全屏， 但点击全屏按钮会切成竖屏幕

**Comment by yangchaojiang** [comment]
这个需求比较特殊。，建议下载源码自己修改

**Comment by yangchaojiang** [comment]
.setVerticalFullScreen() 的初始化设置
