### ISSUE TITLE
请问如何从已完成的缓存中取出视频文件

### ISSUE THREAD

**Issue by helixs** [yangchaojiang/yjPlay#247]
有一个需求，边缓存边播的时候监听视频缓存完成后保存到本地。可是我看了半天源码也没发现有类似的操作。请问如何取出缓存文件呢，如果没有方法，思路该从哪里入手呢？

**Comment by helixs** [comment]
普通视频，并未加密的那种

**Comment by yangchaojiang** [comment]
不需要加密的话，直接下载文件，再试使用你的文件路径 默认都是加密，碎片化

**Comment by helixs** [comment]
这些其实我也知道，主要需求就是需要把缓存取出来然后保存到相册给用户使用分享的，那我可能就要试试别的方法能不能合并视频了

**Comment by helixs** [comment]
有了，可以使用AndroidVideoCache用作代理实现
