### ISSUE TITLE
如何设置不弹出数据流量提示，想用这个播放器做一个启动页的视频

### ISSUE THREAD

**Issue by XXQAQ** [yangchaojiang/yjPlay#249]

**Comment by yangchaojiang** [comment]
VideoPlayerManager
单利模式。
isclick的方法
你写true。就不会提示了
最近忙工作

**Comment by XXQAQ** [comment]
太好了多谢！明白你的这个设计了，不过我提个建议，这个API还是不是很规范，等你后续有空可以考虑规范一下API名称，比如isClick可以更名未enableHintGPRS

**Comment by yangchaojiang** [comment]
可以考虑

**Comment by yangchaojiang** [comment]
2.3.50  增加 serEnableHintGPRS 方法
