### ISSUE TITLE
Error when play with switch uri enable

### ISSUE THREAD

**Issue by mdtuyen** [yangchaojiang/yjPlay#25]
There is an error when play list uri and enable next uri when have an error.
Player will goto next item when I reselect current item of list uri.

I checked log and see that:
when swith uri ExoPlayerMediaSourceBuilder call release and there an Exception make ExoUserPlayer jump to onPlayerError and function nextUri of me called.

I don't know that is issue of ExoPlayer or your library but When I remove content of release function in ExoPlayerMediaSourceBuilder  issue no occur.

**Comment by yangchaojiang** [comment]
Hello, ExoPlayer api player.release () the method, the view log has changed the error message, do not call the test did not. Should be an ExoPlayer error

**Comment by yangchaojiang** [comment]
1.9.8 Have been repaired
