### ISSUE TITLE
还是有内存泄漏的问题

### ISSUE THREAD

**Issue by weitto** [yangchaojiang/yjPlay#258]
leaked 信息：  

VideoPlayerManager&Holdeer.holder
VideoPlayerManager.mVideoPlayer
ExoUserPlayer.videoPlayerView
VideoPlayerView.activity

activity代码 基本与Demo一致。    

 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_player_details);
        
        wholeMediaSource = new WholeMediaSource(getApplication(), new Data2Source(getApplication()));
        MediaSource videoSource = wholeMediaSource.initMediaSource(
                Uri.parse("https://mp4.vjshi.com/2019-05-02/f76943bb77730ca3e2b1cc58e082b07a.mp4"));
        wholeMediaSource.setMediaSource(videoSource);
        exoPlayerManager = VideoPlayerManager.getInstance().getVideoPlayer();
        //如果为空，自己new一个
        if (exoPlayerManager == null) {
            exoPlayerManager = new VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_GESTURE, videoPlayerView)
                    .setDataSource(wholeMediaSource)
                    .setPlayUri("https://mp4.vjshi.com/2019-05-02/f76943bb77730ca3e2b1cc58e082b07a.mp4")
                    .setPosition(0)
                    .create()
                    .startPlayer();
        } else {
            VideoPlayerManager.getInstance().switchTargetViewNew(videoPlayerView);
            exoPlayerManager.setPosition(0);
            exoPlayerManager.setStartOrPause(true);
        }
        
    }

    @Override
    public void onResume() {
        super.onResume();
        LogUtils.d("onresume");
        exoPlayerManager.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        LogUtils.d("暂停");
        exoPlayerManager.onPause();
    }

    @Override
    protected void onDestroy() {
        LogUtils.d("释放资源");
        exoPlayerManager.onDestroy();
        super.onDestroy();
    }

**Comment by yangchaojiang** [comment]
目前没有啊方案，是demo 也存在？

**Comment by danKeeper** [comment]
同存在这个问题，请问解决了吗？

**Comment by yangchaojiang** [comment]
leaked 标准版，exoplayer 都有泄露的问题，这个leaked 即时检测。Android 回收不是实时。
使用中 不存在内存泄露问题 闪退

**Comment by danKeeper** [comment]
嗯，过段时间用Profiler监测，确实没有这个问题，多谢
