### ISSUE TITLE
播放视频后，有的视频底下有绿边，是什么原因？

### ISSUE THREAD

**Issue by wuliXY** [yangchaojiang/yjPlay#26]
用的列表模式，视频预览图正常，发现视频的画面尺寸不一样，有的视频播放会底下会有绿边，，能弄成黑色吗？

**Comment by yangchaojiang** [comment]
demo没有视频哦， 是不是你的视频有哦

**Comment by wuliXY** [comment]
原视频正常的哦（换个播放器没绿边），应该和视频高宽有关（有的视频正常没绿边），我是不是还需要设置什么。或者背景颜色？

**Comment by yangchaojiang** [comment]
视频高宽之外到控件的，是黑色的，或者你已经自定义布局样式。方便的提供有问题视频链接

**Comment by Zhangxd77** [comment]
你好，我这边也是有绿色的边，请问你怎么处理的？
