### ISSUE TITLE
使用版本2.3.40 当我第一次进入视频详情后 请求数据后播放视频 然后点击退出 再次进入播放 报mediaSourceBuilder 空指针异常

### ISSUE THREAD

**Issue by jameswanliu** [yangchaojiang/yjPlay#260]
使用版本2.3.40
 当我第一次进入视频详情后 请求数据后播放视频 然后点击退出 再次进入播放 mediaSourceBuilder 空指针异常

不是自定义数据源

我使用kotlin 语言
 private fun playWithUrl(str: String) {
        if (videoPlayer != null) {
            if (videoPlayer.player != null) {
                videoPlayer.player.stop(true)
            }

            if (videoPlayer != null) {
                videoPlayer.setPosition(0)
                LogUtils.i("play url = " + str)
                LogUtils.i("Uri =" + Uri.parse(str).toString())
                videoPlayer.setPlayUri(Uri.parse(str))
                videoPlayer.showControllerView()
                videoPlayer.startPlayer()
            }
        }
    }

调试机器vivo x9

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/61285047-c2954f00-a7f2-11e9-9df1-c9cb9e9c623e.png)

**Comment by yangchaojiang** [comment]
请不要然封装的类，直接内容， 参考demo

**Comment by jameswanliu** [comment]
### **实际代码如下：**


package com.james.movie.ui.activity

import android.app.PictureInPictureParams
import android.content.res.Configuration
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.support.v4.app.ActivityCompat
import android.view.View
import android.widget.ImageView
import chuangyuan.ycj.videolibrary.listener.VideoInfoListener
import chuangyuan.ycj.videolibrary.video.ExoUserPlayer
import chuangyuan.ycj.videolibrary.video.VideoPlayerManager
import com.eightbitlab.rxbus.Bus
import com.eightbitlab.rxbus.registerInBus
import com.google.android.exoplayer2.ExoPlaybackException
import com.james.base.utils.GlideUtils
import com.james.baselibrary.ext.setImage
import com.james.baselibrary.ui.activity.BaseMvpActivity
import com.james.baselibrary.ui.fragment.BaseFragment
import com.james.baselibrary.utils.IntentFlag
import com.james.baselibrary.utils.LogUtils
import com.james.movie.R
import com.james.movie.bean.*
import com.james.movie.mvp.VideoDetailInfoPresenter
import com.james.movie.mvp.view.VideoDetailView
import com.james.movie.rx.InitPlay
import com.james.movie.rx.RefreshPlayEvent
import com.james.movie.ui.adapter.BookStorePageAdapter
import com.james.movie.ui.fragment.PlaySourceFragment
import com.james.movie.ui.fragment.VideoDetailFragment
import com.james.usercenter.component.DaggerVideoComponent
import kotlinx.android.synthetic.main.activity_video.*
import kotlinx.android.synthetic.main.layout_custom_gesture_audio.*
import kotlinx.android.synthetic.main.layout_custom_gesture_bright.*
import org.jetbrains.anko.toast
import rx.android.schedulers.AndroidSchedulers


class VideoActivity : BaseMvpActivity<VideoDetailInfoPresenter>(), VideoDetailView {

    private var _id = 0

    /**
     * 观看进度
     */
    private var seek = 0

    private var pic = ""

    private var name = ""


    private var tagTime: Int = 0

    private var tagName = ""


    private lateinit var playUrl: String


    private lateinit var videoDetailBean: VideoDetailResp

    private var titles = arrayOf("播放列表", "视频介绍")

    private var fragmentList = ArrayList<BaseFragment>()

    private lateinit var bookStorePageAdapter: BookStorePageAdapter

    private lateinit var playSourceFragment: PlaySourceFragment

    private lateinit var videoDetailFragment: VideoDetailFragment

    private lateinit var videoPlayer: ExoUserPlayer

    override fun initInjection() {
        DaggerVideoComponent.builder().activityComponent(activityComponent).build().inject(this)
        mPresenter.mView = this
    }

    override fun setView(): Int {
        return R.layout.activity_video
    }


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initVideo()
    }


    override fun initData() {
        hideTitleBar()
        _id = intent.getIntExtra(IntentFlag.INTENT_ID, 0)
        pic = intent.getStringExtra(IntentFlag.INTENT_VALUE)
        name = intent.getStringExtra(IntentFlag.INTENT_TAG)
        initUi()
        registPlayUrlChange()
        refreshData()
    }


    private fun refreshData() {
        Bus.observe<RefreshPlayEvent>().subscribe {
            loadData()
        }
    }


    private fun initUi() {
        bookStorePageAdapter = BookStorePageAdapter(supportFragmentManager, this, fragmentList, titles)
        vp_main.adapter = bookStorePageAdapter
        tab_main.setupWithViewPager(vp_main, true)
        playSourceFragment = PlaySourceFragment.newIntance()
        videoDetailFragment = VideoDetailFragment.newIntance()
        fragmentList.add(playSourceFragment)
        fragmentList.add(videoDetailFragment)
        bookStorePageAdapter.notifyDataSetChanged()


    }


    private fun registPlayUrlChange() {
        Bus.observe<PlayUrlChange>().subscribe {
            it?.let {
                this.playUrl = it.playLinksBean.links
                playWithUrl(this.playUrl, it.playLinksBean.name, seek)
            }
        }.registerInBus(this)
    }

    private fun changeBright(max: Int, current: Int) {
        exo_play.gestureBrightnessLayout.visibility = View.VISIBLE
        exo_video_bright_pro.max = max
        exo_video_bright_pro.setBackgroundResource(R.mipmap.ic_brightness_6_white_48px)
        exo_video_bright_pro.progress = current
    }

    private fun changeAudio(max: Int, current: Int) {
        exo_play.gestureAudioLayout.visibility = View.VISIBLE
        exo_video_audio_pro.max = max
        exo_video_audio_pro.progress = current
        exo_video_audio_pro.setBackgroundResource(if (current == 0) R.mipmap.ic_volume_off_white_48px else R.mipmap.ic_volume_up_white_48px)
    }

    override fun onResume() {
        super.onResume()
        this.videoPlayer.onResume()
    }

    override fun onConfigurationChanged(configuration: Configuration) {
        super.onConfigurationChanged(configuration)
        this.videoPlayer.onConfigurationChanged(configuration)
    }

    override fun onBackPressedSupport() {
        if (this.videoPlayer.onBackPressed()) {
            super.onBackPressedSupport()
        }
    }


    private fun initVideo() {
       var builder = VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_GESTURE, exo_play).setOnGestureBrightnessListener { max, current ->
            changeBright(max, current)
        }.setOnGestureVolumeListener { max, current ->
            changeAudio(max, current)
        }.setDataSource(Data2Source(this)).addUpdateProgressListener { j, j2, j3 ->
        }.setTitle(name).addVideoInfoListener(object : VideoInfoListener {
            override fun isPlaying(z: Boolean) {}

            override fun onLoadingChanged() {}

            override fun onPlayEnd() {}

            override fun onPlayStart(j: Long) {
                tagTime = j.toInt()
            }

            override fun onPlayerError(exoPlaybackException: ExoPlaybackException?) {
                if (exoPlaybackException?.type == null && this@VideoActivity.playUrl.startsWith("https")) {
                    toast("https 线路可能失效, 尝试其他资源线路")
                }
            }
        })
        videoPlayer = builder.create()
        val previewImage = this.exo_play.previewImage
        previewImage.scaleType = ImageView.ScaleType.CENTER_CROP
        GlideUtils.loadUrlImage(this, pic, previewImage)
        this.videoPlayer.hideControllerView()
    }


    override fun onPause() {
        super.onPause()
        videoPlayer.onPause()
    }


    override fun onDestroy() {
        videoPlayer.releasePlayers()
        videoPlayer.onDestroy()
        if (tagTime != 0 && videoDetailBean != null) {
            mPresenter.upDatePlayHistory(videoDetailBean.id.toString(), tagTime, tagName)
        }
        super.onDestroy()
    }


//    private fun enterPIP(): Boolean {
//        if (Build.VERSION.SDK_INT < 26) {
//            return false
//        }
////        enterPictureInPictureMode(PictureInPictureParams.Builder().build())
//        return true
//    }


    override fun loadData() {
        mPresenter.getPlayHistoryInfo(_id.toString())
    }


    override fun showContent() {

    }


    override fun onGetVideoDetailSuccess(data: VideoDetailResp) {
        data.let {
            videoDetailBean = data
            videoDetailFragment.setData(data.name, data.actor, data.director, data.des)
            playSourceFragment.setLinkData(data.resources)
            playSourceFragment.initUiData(data)
        }
    }


    private fun playWithUrl(url: String, name: String, seek: Int) {
        tagName = name
        if (videoPlayer.player != null) {
            videoPlayer.player.stop(true)
        }
        videoPlayer.setPlayUri(url)
        videoPlayer.setPosition(seek.toLong())
        videoPlayer.startPlayer()
        videoPlayer.showControllerView()
        mPresenter.addPlayHistory(
                PlayHistoryInfo(videoDetailBean.id
                        , videoDetailBean.name, videoDetailBean.pic, name, url, tagTime, 0))
    }

    override fun onGetPlayHistoryInfoSuccess(data: PlayHistoryInfo) {
        mPresenter.getVideoDetail(_id.toString())
        if (data.map.isNotEmpty()) {
            seek = data.tag_time

            LogUtils.i("seek = $seek")
            tagName = data.tag_name
            this.playUrl = data.url
        }
    }

    override fun onGetPlayHistoryInfoFail(msg: String) {
    }
}

**Comment by jameswanliu** [comment]
### 
**实际代码如下**
import android.app.PictureInPictureParams
import android.content.res.Configuration
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.support.v4.app.ActivityCompat
import android.view.View
import android.widget.ImageView
import chuangyuan.ycj.videolibrary.listener.VideoInfoListener
import chuangyuan.ycj.videolibrary.video.ExoUserPlayer
import chuangyuan.ycj.videolibrary.video.VideoPlayerManager
import com.eightbitlab.rxbus.Bus
import com.eightbitlab.rxbus.registerInBus
import com.google.android.exoplayer2.ExoPlaybackException

import kotlinx.android.synthetic.main.activity_video.*
import kotlinx.android.synthetic.main.layout_custom_gesture_audio.*
import kotlinx.android.synthetic.main.layout_custom_gesture_bright.*
import org.jetbrains.anko.toast
import rx.android.schedulers.AndroidSchedulers


class VideoActivity : BaseMvpActivity<VideoDetailInfoPresenter>(), VideoDetailView {

    private var _id = 0

    /**
     * 观看进度
     */
    private var seek = 0

    private var pic = ""

    private var name = ""


    private var tagTime: Int = 0

    private var tagName = ""


    private lateinit var playUrl: String


    private lateinit var videoDetailBean: VideoDetailResp

    private var titles = arrayOf("播放列表", "视频介绍")

    private var fragmentList = ArrayList<BaseFragment>()

    private lateinit var bookStorePageAdapter: BookStorePageAdapter

    private lateinit var playSourceFragment: PlaySourceFragment

    private lateinit var videoDetailFragment: VideoDetailFragment

    private lateinit var videoPlayer: ExoUserPlayer

    override fun initInjection() {
        DaggerVideoComponent.builder().activityComponent(activityComponent).build().inject(this)
        mPresenter.mView = this
    }

    override fun setView(): Int {
        return R.layout.activity_video
    }


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initVideo()
    }


    override fun initData() {
        hideTitleBar()
        _id = intent.getIntExtra(IntentFlag.INTENT_ID, 0)
        pic = intent.getStringExtra(IntentFlag.INTENT_VALUE)
        name = intent.getStringExtra(IntentFlag.INTENT_TAG)
        initUi()
        registPlayUrlChange()
        refreshData()
    }


    private fun refreshData() {
        Bus.observe<RefreshPlayEvent>().subscribe {
            loadData()
        }
    }


    private fun initUi() {
        bookStorePageAdapter = BookStorePageAdapter(supportFragmentManager, this, fragmentList, titles)
        vp_main.adapter = bookStorePageAdapter
        tab_main.setupWithViewPager(vp_main, true)
        playSourceFragment = PlaySourceFragment.newIntance()
        videoDetailFragment = VideoDetailFragment.newIntance()
        fragmentList.add(playSourceFragment)
        fragmentList.add(videoDetailFragment)
        bookStorePageAdapter.notifyDataSetChanged()


    }


    private fun registPlayUrlChange() {
        Bus.observe<PlayUrlChange>().subscribe {
            it?.let {
                this.playUrl = it.playLinksBean.links
                playWithUrl(this.playUrl, it.playLinksBean.name, seek)
            }
        }.registerInBus(this)
    }

    private fun changeBright(max: Int, current: Int) {
        exo_play.gestureBrightnessLayout.visibility = View.VISIBLE
        exo_video_bright_pro.max = max
        exo_video_bright_pro.setBackgroundResource(R.mipmap.ic_brightness_6_white_48px)
        exo_video_bright_pro.progress = current
    }

    private fun changeAudio(max: Int, current: Int) {
        exo_play.gestureAudioLayout.visibility = View.VISIBLE
        exo_video_audio_pro.max = max
        exo_video_audio_pro.progress = current
        exo_video_audio_pro.setBackgroundResource(if (current == 0) R.mipmap.ic_volume_off_white_48px else R.mipmap.ic_volume_up_white_48px)
    }

    override fun onResume() {
        super.onResume()
        this.videoPlayer.onResume()
    }

    override fun onConfigurationChanged(configuration: Configuration) {
        super.onConfigurationChanged(configuration)
        this.videoPlayer.onConfigurationChanged(configuration)
    }

    override fun onBackPressedSupport() {
        if (this.videoPlayer.onBackPressed()) {
            super.onBackPressedSupport()
        }
    }


    private fun initVideo() {
       var builder = VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_GESTURE, exo_play).setOnGestureBrightnessListener { max, current ->
            changeBright(max, current)
        }.setOnGestureVolumeListener { max, current ->
            changeAudio(max, current)
        }.setDataSource(Data2Source(this)).addUpdateProgressListener { j, j2, j3 ->
        }.setTitle(name).addVideoInfoListener(object : VideoInfoListener {
            override fun isPlaying(z: Boolean) {}

            override fun onLoadingChanged() {}

            override fun onPlayEnd() {}

            override fun onPlayStart(j: Long) {
                tagTime = j.toInt()
            }

            override fun onPlayerError(exoPlaybackException: ExoPlaybackException?) {
                if (exoPlaybackException?.type == null && this@VideoActivity.playUrl.startsWith("https")) {
                    toast("https 线路可能失效, 尝试其他资源线路")
                }
            }
        })
        videoPlayer = builder.create()
        val previewImage = this.exo_play.previewImage
        previewImage.scaleType = ImageView.ScaleType.CENTER_CROP
        GlideUtils.loadUrlImage(this, pic, previewImage)
        this.videoPlayer.hideControllerView()
    }


    override fun onPause() {
        super.onPause()
        videoPlayer.onPause()
    }


    override fun onDestroy() {
        videoPlayer.releasePlayers()
        videoPlayer.onDestroy()
        if (tagTime != 0 && videoDetailBean != null) {
            mPresenter.upDatePlayHistory(videoDetailBean.id.toString(), tagTime, tagName)
        }
        super.onDestroy()
    }



    override fun loadData() {
        mPresenter.getPlayHistoryInfo(_id.toString())
    }


    override fun showContent() {

    }


    override fun onGetVideoDetailSuccess(data: VideoDetailResp) {
        data.let {
            videoDetailBean = data
            videoDetailFragment.setData(data.name, data.actor, data.director, data.des)
            playSourceFragment.setLinkData(data.resources)
            playSourceFragment.initUiData(data)
        }
    }


    private fun playWithUrl(url: String, name: String, seek: Int) {
        tagName = name
        if (videoPlayer.player != null) {
            videoPlayer.player.stop(true)
        }
        videoPlayer.setPlayUri(url)
        videoPlayer.setPosition(seek.toLong())
        videoPlayer.startPlayer()
        videoPlayer.showControllerView()
        mPresenter.addPlayHistory(
                PlayHistoryInfo(videoDetailBean.id
                        , videoDetailBean.name, videoDetailBean.pic, name, url, tagTime, 0))
    }

    override fun onGetPlayHistoryInfoSuccess(data: PlayHistoryInfo) {
        mPresenter.getVideoDetail(_id.toString())
        if (data.map.isNotEmpty()) {
            seek = data.tag_time

            LogUtils.i("seek = $seek")
            tagName = data.tag_name
            this.playUrl = data.url
        }
    }

    override fun onGetPlayHistoryInfoFail(msg: String) {
    }
}

**Comment by jameswanliu** [comment]
> 请不要然封装的类，直接内容， 参考demo

### **实际代码如下**



package com.james.movie.ui.activity

import android.app.PictureInPictureParams
import android.content.res.Configuration
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.support.v4.app.ActivityCompat
import android.view.View
import android.widget.ImageView
import chuangyuan.ycj.videolibrary.listener.VideoInfoListener
import chuangyuan.ycj.videolibrary.video.ExoUserPlayer
import chuangyuan.ycj.videolibrary.video.VideoPlayerManager
import com.eightbitlab.rxbus.Bus
import com.eightbitlab.rxbus.registerInBus
import com.google.android.exoplayer2.ExoPlaybackException

import kotlinx.android.synthetic.main.activity_video.*
import kotlinx.android.synthetic.main.layout_custom_gesture_audio.*
import kotlinx.android.synthetic.main.layout_custom_gesture_bright.*
import org.jetbrains.anko.toast
import rx.android.schedulers.AndroidSchedulers


class VideoActivity : BaseMvpActivity<VideoDetailInfoPresenter>(), VideoDetailView {

    private var _id = 0

    /**
     * 观看进度
     */
    private var seek = 0

    private var pic = ""

    private var name = ""


    private var tagTime: Int = 0

    private var tagName = ""


    private lateinit var playUrl: String


    private lateinit var videoDetailBean: VideoDetailResp

    private var titles = arrayOf("播放列表", "视频介绍")

    private var fragmentList = ArrayList<BaseFragment>()

    private lateinit var bookStorePageAdapter: BookStorePageAdapter

    private lateinit var playSourceFragment: PlaySourceFragment

    private lateinit var videoDetailFragment: VideoDetailFragment

    private lateinit var videoPlayer: ExoUserPlayer

    override fun initInjection() {
        DaggerVideoComponent.builder().activityComponent(activityComponent).build().inject(this)
        mPresenter.mView = this
    }

    override fun setView(): Int {
        return R.layout.activity_video
    }


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initVideo()
    }


    override fun initData() {
        hideTitleBar()
        _id = intent.getIntExtra(IntentFlag.INTENT_ID, 0)
        pic = intent.getStringExtra(IntentFlag.INTENT_VALUE)
        name = intent.getStringExtra(IntentFlag.INTENT_TAG)
        initUi()
        registPlayUrlChange()
        refreshData()
    }


    private fun refreshData() {
        Bus.observe<RefreshPlayEvent>().subscribe {
            loadData()
        }
    }


    private fun initUi() {
        bookStorePageAdapter = BookStorePageAdapter(supportFragmentManager, this, fragmentList, titles)
        vp_main.adapter = bookStorePageAdapter
        tab_main.setupWithViewPager(vp_main, true)
        playSourceFragment = PlaySourceFragment.newIntance()
        videoDetailFragment = VideoDetailFragment.newIntance()
        fragmentList.add(playSourceFragment)
        fragmentList.add(videoDetailFragment)
        bookStorePageAdapter.notifyDataSetChanged()


    }


    private fun registPlayUrlChange() {
        Bus.observe<PlayUrlChange>().subscribe {
            it?.let {
                this.playUrl = it.playLinksBean.links
                playWithUrl(this.playUrl, it.playLinksBean.name, seek)
            }
        }.registerInBus(this)
    }

    private fun changeBright(max: Int, current: Int) {
        exo_play.gestureBrightnessLayout.visibility = View.VISIBLE
        exo_video_bright_pro.max = max
        exo_video_bright_pro.setBackgroundResource(R.mipmap.ic_brightness_6_white_48px)
        exo_video_bright_pro.progress = current
    }

    private fun changeAudio(max: Int, current: Int) {
        exo_play.gestureAudioLayout.visibility = View.VISIBLE
        exo_video_audio_pro.max = max
        exo_video_audio_pro.progress = current
        exo_video_audio_pro.setBackgroundResource(if (current == 0) R.mipmap.ic_volume_off_white_48px else R.mipmap.ic_volume_up_white_48px)
    }

    override fun onResume() {
        super.onResume()
        this.videoPlayer.onResume()
    }

    override fun onConfigurationChanged(configuration: Configuration) {
        super.onConfigurationChanged(configuration)
        this.videoPlayer.onConfigurationChanged(configuration)
    }

    override fun onBackPressedSupport() {
        if (this.videoPlayer.onBackPressed()) {
            super.onBackPressedSupport()
        }
    }


    private fun initVideo() {
       var builder = VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_GESTURE, exo_play).setOnGestureBrightnessListener { max, current ->
            changeBright(max, current)
        }.setOnGestureVolumeListener { max, current ->
            changeAudio(max, current)
        }.setDataSource(Data2Source(this)).addUpdateProgressListener { j, j2, j3 ->
        }.setTitle(name).addVideoInfoListener(object : VideoInfoListener {
            override fun isPlaying(z: Boolean) {}

            override fun onLoadingChanged() {}

            override fun onPlayEnd() {}

            override fun onPlayStart(j: Long) {
                tagTime = j.toInt()
            }

            override fun onPlayerError(exoPlaybackException: ExoPlaybackException?) {
                if (exoPlaybackException?.type == null && this@VideoActivity.playUrl.startsWith("https")) {
                    toast("https 线路可能失效, 尝试其他资源线路")
                }
            }
        })
        videoPlayer = builder.create()
        val previewImage = this.exo_play.previewImage
        previewImage.scaleType = ImageView.ScaleType.CENTER_CROP
        GlideUtils.loadUrlImage(this, pic, previewImage)
        this.videoPlayer.hideControllerView()
    }


    override fun onPause() {
        super.onPause()
        videoPlayer.onPause()
    }


    override fun onDestroy() {
        videoPlayer.releasePlayers()
        videoPlayer.onDestroy()
        if (tagTime != 0 && videoDetailBean != null) {
            mPresenter.upDatePlayHistory(videoDetailBean.id.toString(), tagTime, tagName)
        }
        super.onDestroy()
    }


    override fun loadData() {
        mPresenter.getPlayHistoryInfo(_id.toString())
    }


    override fun showContent() {

    }


    override fun onGetVideoDetailSuccess(data: VideoDetailResp) {
        data.let {
            videoDetailBean = data
            videoDetailFragment.setData(data.name, data.actor, data.director, data.des)
            playSourceFragment.setLinkData(data.resources)
            playSourceFragment.initUiData(data)
        }
    }


    private fun playWithUrl(url: String, name: String, seek: Int) {
        tagName = name
        if (videoPlayer.player != null) {
            videoPlayer.player.stop(true)
        }
        videoPlayer.setPlayUri(url)
        videoPlayer.setPosition(seek.toLong())
        videoPlayer.startPlayer()
        videoPlayer.showControllerView()
        mPresenter.addPlayHistory(
                PlayHistoryInfo(videoDetailBean.id
                        , videoDetailBean.name, videoDetailBean.pic, name, url, tagTime, 0))
    }

    override fun onGetPlayHistoryInfoSuccess(data: PlayHistoryInfo) {
        mPresenter.getVideoDetail(_id.toString())
        if (data.map.isNotEmpty()) {
            seek = data.tag_time

            LogUtils.i("seek = $seek")
            tagName = data.tag_name
            this.playUrl = data.url
        }
    }

    override fun onGetPlayHistoryInfoFail(msg: String) {
    }
}

**Comment by jameswanliu** [comment]
> 请不要然封装的类，直接内容， 参考demo

### **实际代码如下**

import android.app.PictureInPictureParams
import android.content.res.Configuration
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.support.v4.app.ActivityCompat
import android.view.View
import android.widget.ImageView
import chuangyuan.ycj.videolibrary.listener.VideoInfoListener
import chuangyuan.ycj.videolibrary.video.ExoUserPlayer
import chuangyuan.ycj.videolibrary.video.VideoPlayerManager
import com.eightbitlab.rxbus.Bus
import com.eightbitlab.rxbus.registerInBus
import com.google.android.exoplayer2.ExoPlaybackException

import kotlinx.android.synthetic.main.activity_video.*
import kotlinx.android.synthetic.main.layout_custom_gesture_audio.*
import kotlinx.android.synthetic.main.layout_custom_gesture_bright.*
import org.jetbrains.anko.toast
import rx.android.schedulers.AndroidSchedulers


class VideoActivity : BaseMvpActivity<VideoDetailInfoPresenter>(), VideoDetailView {

    private var _id = 0

    /**
     * 观看进度
     */
    private var seek = 0

    private var pic = ""

    private var name = ""


    private var tagTime: Int = 0

    private var tagName = ""


    private lateinit var playUrl: String


    private lateinit var videoDetailBean: VideoDetailResp

    private var titles = arrayOf("播放列表", "视频介绍")

    private var fragmentList = ArrayList<BaseFragment>()

    private lateinit var bookStorePageAdapter: BookStorePageAdapter

    private lateinit var playSourceFragment: PlaySourceFragment

    private lateinit var videoDetailFragment: VideoDetailFragment

    private lateinit var videoPlayer: ExoUserPlayer

    override fun initInjection() {
        DaggerVideoComponent.builder().activityComponent(activityComponent).build().inject(this)
        mPresenter.mView = this
    }

    override fun setView(): Int {
        return R.layout.activity_video
    }


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initVideo()
    }


    override fun initData() {
        hideTitleBar()
        _id = intent.getIntExtra(IntentFlag.INTENT_ID, 0)
        pic = intent.getStringExtra(IntentFlag.INTENT_VALUE)
        name = intent.getStringExtra(IntentFlag.INTENT_TAG)
        initUi()
        registPlayUrlChange()
        refreshData()
    }


    private fun refreshData() {
        Bus.observe<RefreshPlayEvent>().subscribe {
            loadData()
        }
    }


    private fun initUi() {
        bookStorePageAdapter = BookStorePageAdapter(supportFragmentManager, this, fragmentList, titles)
        vp_main.adapter = bookStorePageAdapter
        tab_main.setupWithViewPager(vp_main, true)
        playSourceFragment = PlaySourceFragment.newIntance()
        videoDetailFragment = VideoDetailFragment.newIntance()
        fragmentList.add(playSourceFragment)
        fragmentList.add(videoDetailFragment)
        bookStorePageAdapter.notifyDataSetChanged()


    }


    private fun registPlayUrlChange() {
        Bus.observe<PlayUrlChange>().subscribe {
            it?.let {
                this.playUrl = it.playLinksBean.links
                playWithUrl(this.playUrl, it.playLinksBean.name, seek)
            }
        }.registerInBus(this)
    }

    private fun changeBright(max: Int, current: Int) {
        exo_play.gestureBrightnessLayout.visibility = View.VISIBLE
        exo_video_bright_pro.max = max
        exo_video_bright_pro.setBackgroundResource(R.mipmap.ic_brightness_6_white_48px)
        exo_video_bright_pro.progress = current
    }

    private fun changeAudio(max: Int, current: Int) {
        exo_play.gestureAudioLayout.visibility = View.VISIBLE
        exo_video_audio_pro.max = max
        exo_video_audio_pro.progress = current
        exo_video_audio_pro.setBackgroundResource(if (current == 0) R.mipmap.ic_volume_off_white_48px else R.mipmap.ic_volume_up_white_48px)
    }

    override fun onResume() {
        super.onResume()
        this.videoPlayer.onResume()
    }

    override fun onConfigurationChanged(configuration: Configuration) {
        super.onConfigurationChanged(configuration)
        this.videoPlayer.onConfigurationChanged(configuration)
    }

    override fun onBackPressedSupport() {
        if (this.videoPlayer.onBackPressed()) {
            super.onBackPressedSupport()
        }
    }


    private fun initVideo() {
       var builder = VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_GESTURE, exo_play).setOnGestureBrightnessListener { max, current ->
            changeBright(max, current)
        }.setOnGestureVolumeListener { max, current ->
            changeAudio(max, current)
        }.setDataSource(Data2Source(this)).addUpdateProgressListener { j, j2, j3 ->
        }.setTitle(name).addVideoInfoListener(object : VideoInfoListener {
            override fun isPlaying(z: Boolean) {}

            override fun onLoadingChanged() {}

            override fun onPlayEnd() {}

            override fun onPlayStart(j: Long) {
                tagTime = j.toInt()
            }

            override fun onPlayerError(exoPlaybackException: ExoPlaybackException?) {
                if (exoPlaybackException?.type == null && this@VideoActivity.playUrl.startsWith("https")) {
                    toast("https 线路可能失效, 尝试其他资源线路")
                }
            }
        })
        videoPlayer = builder.create()
        val previewImage = this.exo_play.previewImage
        previewImage.scaleType = ImageView.ScaleType.CENTER_CROP
        GlideUtils.loadUrlImage(this, pic, previewImage)
        this.videoPlayer.hideControllerView()
    }


    override fun onPause() {
        super.onPause()
        videoPlayer.onPause()
    }


    override fun onDestroy() {
        videoPlayer.releasePlayers()
        videoPlayer.onDestroy()
        if (tagTime != 0 && videoDetailBean != null) {
            mPresenter.upDatePlayHistory(videoDetailBean.id.toString(), tagTime, tagName)
        }
        super.onDestroy()
    }





    override fun loadData() {
        mPresenter.getPlayHistoryInfo(_id.toString())
    }


    override fun showContent() {

    }


    override fun onGetVideoDetailSuccess(data: VideoDetailResp) {
        data.let {
            videoDetailBean = data
            videoDetailFragment.setData(data.name, data.actor, data.director, data.des)
            playSourceFragment.setLinkData(data.resources)
            playSourceFragment.initUiData(data)
        }
    }


    private fun playWithUrl(url: String, name: String, seek: Int) {
        tagName = name
        if (videoPlayer.player != null) {
            videoPlayer.player.stop(true)
        }
        videoPlayer.setPlayUri(url)
        videoPlayer.setPosition(seek.toLong())
        videoPlayer.startPlayer()
        videoPlayer.showControllerView()
        mPresenter.addPlayHistory(
                PlayHistoryInfo(videoDetailBean.id
                        , videoDetailBean.name, videoDetailBean.pic, name, url, tagTime, 0))
    }

    override fun onGetPlayHistoryInfoSuccess(data: PlayHistoryInfo) {
        mPresenter.getVideoDetail(_id.toString())
        if (data.map.isNotEmpty()) {
            seek = data.tag_time

            LogUtils.i("seek = $seek")
            tagName = data.tag_name
            this.playUrl = data.url
        }
    }

    override fun onGetPlayHistoryInfoFail(msg: String) {
    }
}

**Comment by yangchaojiang** [comment]
我感觉你的周期
![图片](https://user-images.githubusercontent.com/13806413/61438667-8e489c80-a972-11e9-948b-230e05d086b7.png)
建议 手动初始化设置一下 mediaSourceBuilder
