### ISSUE TITLE
使用荣耀v10 刘海屏手机（系统9.0） 进入全屏后 自动退出播放

### ISSUE THREAD

**Issue by jameswanliu** [yangchaojiang/yjPlay#261]
使用荣耀v10 刘海屏手机（系统9.0） 进入全屏后 自动退出播放，没有报错（2.3.40 版本有做 这方面的适配吗）

**Comment by yangchaojiang** [comment]
有截图吗

**Comment by jameswanliu** [comment]
> 有截图吗
sorry this is my mistake （configChanges 属性没有设置） 
![image](https://user-images.githubusercontent.com/7357320/61519090-a507f580-aa3d-11e9-8ea5-579ed4292da8.png)

**Comment by yangchaojiang** [comment]
你没有实现方法， 还有功能清单声明看一下

**Comment by yangchaojiang** [comment]
参考demo
