### ISSUE TITLE
请问如何查看视频已经缓存完毕

### ISSUE THREAD

**Issue by helixs** [yangchaojiang/yjPlay#262]
播放在线mp4视频前：
1、如何通过key也就是默认url，查询当前视频已经缓存完毕或者查看缓存的进度？
  CacheUtil.getCached这个传入的参数也太多了，有点看不懂。
2、已经缓存的完毕的视频，播放时为什么还会有二次进度条呢，可以一次性加载完毕吗？

**Comment by yangchaojiang** [comment]
目前不提供进度的封装
需要自己CacheUtil 这个跟自己的查询缓存进度

**Comment by helixs** [comment]
setPlayUri之前，暴露一个simpleCache出来，调用下面方法

/**
 * 判断视频是否已经缓存完毕
 */
fun getVideoCacheIsOk(url:String, cache: Cache, key:String? =null):Boolean{
    val dataspec= DataSpec(
            Uri.parse(url),
            /* absoluteStreamPosition= */ 0,
            C.LENGTH_UNSET.toLong(),
            key?:url,
            DataSpec.FLAG_ALLOW_CACHE_FRAGMENTATION)
    val current = CacheUtil.getCached(dataspec,cache, CacheUtil.DEFAULT_CACHE_KEY_FACTORY)
    return current.first==current.second
}

**Comment by yangchaojiang** [comment]
可以 我更新一下

**Comment by helixs** [comment]
@yangchaojiang 我仅仅做的短视频测试，长视频和其他方式暂时没有试过。
