### ISSUE TITLE
ExoUserPlayer多个界面播放问题

### ISSUE THREAD

**Issue by lidynast** [yangchaojiang/yjPlay#263]
ExoUserPlayer在A页面播放视频，视频播放完成之后跳转B界面（B界面也有一个ExoUserPlayer播放视频），当从B界面返回A界面后，A界面的ExoUserPlayer中player为空、视频不能播放，请问这种情况怎么解决呢

**Comment by yangchaojiang** [comment]
参看demo，两个页面是独立话， 不做关联操作。不是独立， 参看demo的 列表请详情是实例代码。
你肯定少些代码了
