### ISSUE TITLE
Not set referer using stream

### ISSUE THREAD

**Issue by hoangnguyen15** [yangchaojiang/yjPlay#264]
I use to transmit referer DataSourceListener stream but with an error, the error code "Response code: 403". 
Stream for me: 

> https://live2.bongdaf.net/5998f632d6307767f123645dde6f5e671566419216/i7/playlist.m3u8

My code

> 
public class Data2Source implements DataSourceListener {

    private Context context;

    public Data2Source(Context context) {
        this.context = context;
    }

    @Override
    public com.google.android.exoplayer2.upstream.DataSource.Factory getDataSourceFactory() {
        //默认数据源工厂
        DefaultHttpDataSourceFactory defaultHttpDataSourceFactory = new DefaultHttpDataSourceFactory(context.getPackageName(), null, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, true);
        defaultHttpDataSourceFactory.setDefaultRequestProperty("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36");
        defaultHttpDataSourceFactory.setDefaultRequestProperty("Referer", "https://bongdaf.net/truc-tiep/all-boys-vs-central-cordoba-sde-srnENR602.html?ads=1");
        return defaultHttpDataSourceFactory;

    }

> exoPlayerManager = new VideoPlayerManager.Builder(VideoPlayerManager.TYPE_PLAY_USER, mPlayerView)
                .setPlayUri(urlm3u8)
                .setDataSource(new Data2Source(M3u8Activity.this))
               .create()
                .startPlayer();

and I have tried using extends HttpDataSource.BaseFactory but I do not know how to add exoPlayerManager.

Please give me solution. thank u

**Comment by yangchaojiang** [comment]
[https://github.com/google/ExoPlayer/issues/5422](https://github.com/google/ExoPlayer/issues/5422)
[https://github.com/google/ExoPlayer/issues/4320](https://github.com/google/ExoPlayer/issues/4320)

**Comment by hoangnguyen15** [comment]
so i won't use your library but instead of exoplayer? . I need to guide getDefaultRequestProperties () set referer from your library !. please support . thank u

**Comment by hoangnguyen15** [comment]
When I debug I don't see the getDataSourceFactory method running in the Data2Source class. Please check and support

**Comment by yangchaojiang** [comment]
My reference class library, using the basis of exoplayer

**Comment by hoangnguyen15** [comment]
There are no instructions to transmit to your library. I have succeeded with exoplayer but I want to do with your library

**Comment by hoangnguyen15** [comment]
Please give me the sample code from your library

**Comment by yangchaojiang** [comment]
error: "Response code: 403".
![图片](https://user-images.githubusercontent.com/13806413/63661701-3d885700-c7ee-11e9-81df-0ac8fe7ac439.png)
The core processing is handled by the exoplayer class library, not my class library. My library's original foundation was simplified to simplify access time costs.
Due to the redirection of your video link, this exoplayer issue is also feedback.
