### ISSUE TITLE
LinearLayout can not be  cast to Textview

### ISSUE THREAD

**Issue by qsw-net** [yangchaojiang/yjPlay#267]
<style name="ExoMediaTitleLayout">
        <item name="android:id">@id/exo_controls_title</item>
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">35dp</item>
        <item name="android:layout_alignParentTop">true</item>
        <item name="android:background">@drawable/exo_bg_video_top</item>
        <item name="android:gravity">center_vertical|start</item>
    </style>

**Comment by yangchaojiang** [comment]
no
