### ISSUE TITLE
怎样可以实现抖音播放效果

### ISSUE THREAD

**Issue by neo2616** [yangchaojiang/yjPlay#271]
controller无法重写。不能实现抖音播放样式。playerView里面是不是应该有setController()才可以吧

**Comment by neo2616** [comment]
这个项目问题 1  不能重写controller。
2 两次闪退。闪退表示项目不成熟，也可能是手机问题，原因不想去查了。
优点 对exo的良好封装。
下载服务功能很吸引人，但不够好。专注更重要。
结论:不适合商用。
我又回到gsy了

**Comment by yangchaojiang** [comment]
每个开源都苦，实现思路，本库不着重controller，
而是

**Comment by yangchaojiang** [comment]
两次闪退 情吧日志发以出来。

**Comment by yangchaojiang** [comment]
controller  建立不是controller 基础开发的
