### ISSUE TITLE
1.竖屏全屏动画位置问题，2.视频尺寸回调问题

### ISSUE THREAD

**Issue by caiyoufei** [yangchaojiang/yjPlay#273]
感谢老哥的奉献

我在初次使用yjPlay时遇到一些问题，望大佬解答，Thanks
当前使用版本：implementation 'com.ycjiang:VideoPlayModule-Lite:2.3.50'

1.竖屏全屏开启，不论原视频在哪个位置播放，动画都是从左上角开始扩大的，比如我设置适配在屏幕中心位置播放，如下图
![GIF (1)](https://user-images.githubusercontent.com/11989916/68068453-74975d80-fd87-11e9-8c42-f181b9d1c2cd.gif)
2.能不能添加一个视频尺寸的回调，方便根据视频尺寸设置是否开启竖屏全屏功能

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/68071001-817c7700-fdb0-11e9-867d-96dc3abfed42.png)

**Comment by yangchaojiang** [comment]
视频尺寸的回调，方便根据视频尺寸设置是否开启竖屏全屏功能
应该你是自己的接口给哦。这个解析比较慢的

**Comment by caiyoufei** [comment]
@yangchaojiang 大佬

第一个问题你没明白，我说的是动画的位置，不是开启竖屏。动画的开始位置不能从原播放位置开始放大嘛？每次从左上角，如果视频不在左上角这个动画看起来很别扭。

第二个问题，并不需要很快解析出来，因为开始播放后才展示全屏按钮，所以在开始播放的时候或者prepare完成后回调一次视频尺寸就好了，开始播放后才设置横屏或者竖屏全屏，并不影响其他逻辑

**Comment by yangchaojiang** [comment]
视频尺寸，。哪有放在前端的解析，这个依赖网络。

你可以参考的demo  仿抖音那个示例看看

**Comment by caiyoufei** [comment]
算了，我还是重新找办法吧
