### ISSUE TITLE
安卓Q上直播不了

### ISSUE THREAD

**Issue by ysnows** [yangchaojiang/yjPlay#275]
E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)

**Comment by yangchaojiang** [comment]
应该兼容 我在更新升级ExoPlayerImplInternal 版本

**Comment by ysnows** [comment]
好的

**Comment by yangchaojiang** [comment]
试试2.2.52
