### ISSUE TITLE
setStartOrPause无效

### ISSUE THREAD

**Issue by leeyushi** [yangchaojiang/yjPlay#277]
初始化音频的时候，必须要startPlayer，这样下面这句才会生效
mExoPlayerManager.setStartOrPause(true);
这样我将面临两种选择
1：初始化的时候就startPlay
2：在播放与暂停的时候，新增一些自定义属性去监听是否为第一次初始化
第一种初始化的时候一般不会去播放的
第二种我觉得是增加一些不必要的逻辑判断...

**Comment by yangchaojiang** [comment]
setStartOrPause  方法肯定，视频初始化，才能用。exoplayer 内部也是的，。

**Comment by leeyushi** [comment]
> setStartOrPause 方法肯定，视频初始化，才能用。exoplayer 内部也是的，。

所以有没有其它初始化的方法，而是非startPlay才可以初始化

**Comment by leeyushi** [comment]
找到了，用
mExoPlayerManager.getPlayer().getPlaybackState() == Player.STATE_IDLE
判断是否初始化

**Comment by yangchaojiang** [comment]
没有，内部是
````
 player.prepare(mediaSourceBuilder.getMediaSource(), !haveResumePosition, false);
`````
你可以在初始化时候只用create方法，展示你的封面和标题，不会加载视频，不会自动播放， 内部会自动处理，点击播放。

**Comment by leeyushi** [comment]
不行，只用create方法，内部自动处理的点击事件也不会进行播放，只有startPlay过后，内部才可以处理点击播放与暂停，你去demo库里面测试一下

**Comment by yangchaojiang** [comment]
麻烦看定义布局，我这里妹哟问题的，

**Comment by leeyushi** [comment]
> 麻烦看定义布局，我这里妹哟问题的，

你去看demo库里面的倒数第二条“播放音频”这一个
我刚刚又去核对了，不显示startPlay内部点击是无法处理的

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/69523744-94ddc500-0f9f-11ea-986a-ea69f9c5b8fd.png)

**Comment by yangchaojiang** [comment]
音频实现这个回调
