### ISSUE TITLE
大佬,有没有直接可以调用的快进或者快退的方法

### ISSUE THREAD

**Issue by OvenCroc** [yangchaojiang/yjPlay#280]
使用版本:2.3.50
我用来做android tv开发, 在监听到遥控器按下做或者右的时候会调用showControllerView(false)来显示进度条, 但是要按下下进度条才能够获取到焦点, 这个时候点击左右的时候才能快进或者快退, 我想问一下大佬有没有直接可以用来快进或者快退的方法, 谢谢大佬

**Comment by yangchaojiang** [comment]
快进或者快退，自己实现自定局部快进或者快退按钮 setpsition就行了

**Comment by OvenCroc** [comment]
> 
> 
> 快进或者快退，自己实现自定局部快进或者快退按钮 setpsition就行了

大佬我试了setposition了不能实现快进快退的效果, 只能是设置开始播放时候的进度位置, 不过后来我看你源码里面exoplayermanager有一个seekto方法, 是可以有效的, 最后通过seekto方法实现的, 不管怎样, 还是感谢大佬啦

**Comment by yangchaojiang** [comment]
不好意思，记错了，是seekto   最近在忙其他事。尴尬了

**Comment by OvenCroc** [comment]
> 
> 
> 不好意思，记错了，是seekto 最近在忙其他事。尴尬了

没有没有 大佬的这个库已经帮了我很多忙了 感谢你在忙中还来回复我, 给你添麻烦了
