### ISSUE TITLE
关于VideoPlayerView控件先隐藏根据判断显示的问题

### ISSUE THREAD

**Issue by chentaozs** [yangchaojiang/yjPlay#282]
问题现象：你好，在使用VideoPlayerView的时候因为用到了判断显示和隐藏，我就先全部隐藏了，然后满足条件初始化显示的时候就会没有效果，只有占位显示背景色的效果。后来我慢慢排查把他从始至终都是显示的时，就一切正常。我只用了一个手机测试：华为POT-AL00a，找到原因后对功能没有太大影响，望您有时间可以看下，希望您的项目可以越来越好，我先star为敬

**Comment by yangchaojiang** [comment]
我有内部控制，所以你外部使用无效。

**Comment by chentaozs** [comment]
ok，晓得了，谢谢解惑
