### ISSUE TITLE
关于先初始化player  后通过网络获取数据设置uri   在期间数据为null

### ISSUE THREAD

**Issue by ganzhex2019** [yangchaojiang/yjPlay#290]
下面是初始化palyer 
  exoPlayerManager = VideoPlayerManager
            .Builder(VideoPlayerManager.TYPE_PLAY_USER, videoPlayerView!!)
            .setDataSource(wholeMediaSource!!)
            .setPosition(0)
            .setOnPlayClickListener {
        
                 exoPlayerManager?.startPlayer()
              
            }
            .create()

这是设置uri
 exoPlayerManager!!.setPlayUri(filmUrl.urlInfo.first().result.first().finalUrl)

在期间如果网络出现问题  exoPlayerManager?.startPlayer()   出现异常  请问怎么判断数据为空  我找了下  好像没有这个数据  比如 getUri之类

**Comment by ganzhex2019** [comment]
就是这里   怎么判断数据   请求 
exoPlayerManager?.startPlayer()

**Comment by yangchaojiang** [comment]
使用问题哦
这是设置uri
```
exoPlayerManager!!.setPlayUri(filmUrl.urlInfo.first().result.first().finalUrl)
```
这个方法只能在.create()之前的调用，不能单独拿出来的

**Comment by ganzhex2019** [comment]
1.我的意思是一般播放器核心是先实例化 
2.url设置之类的都是后期动态添加，也就是你的工厂类里面  好吧  我先看看你的源码 和exoplayer
其实你的播放库是支持这种动态添加的  只是在没有添加url之前  数据确实为null   我是通过把baseView把播放按钮暴露出来  设置获取网络地址前后是否可点击  问题可解决 但是觉得不够好
3 最后希望大佬升级到androidX 和exoplayer 最新版  网上的exoplayer实在太少  短期想写好一个自定义播放器确实不容易  再次感谢你的开源库

**Comment by yangchaojiang** [comment]
我现在更改内部代码，exoplayer官网主要一些问题，我再看，

**Comment by yangchaojiang** [comment]
初始化采用官网，流式的api调用。uil 提前准备好， 尼说的场景是，动态添加uil 尼要判断一下，
是否拿到uil 才能调用
````
exoPlayerManager?.startPlayer()
````
