### ISSUE TITLE
最新版  exoPlayerManager.setPlayUri(urlList)  urlList几百条的时候报错

### ISSUE THREAD

**Issue by ganzhex2019** [yangchaojiang/yjPlay#293]
java.lang.OutOfMemoryError: Could not allocate JNI Env

NativeCrypto: AppData::create pipe(2) failed: Too many open files

onPlayerError:java.lang.OutOfMemoryError: Could not allocate JNI Env

请问是否有解决的办法   加载几百条列表的时候

**Comment by yangchaojiang** [comment]
哥不用一些加载这么多哦。内存没法这么多。
```
setPlayUri()
```
你可以后面动态追加
支持动态追加
