### ISSUE TITLE
demo下载不了！

### ISSUE THREAD

**Issue by mutoujun** [yangchaojiang/yjPlay#296]
demo下载不了，文档也不太清晰，自定义布局有哪些，布局里的id又是哪些，也不知道

**Comment by yangchaojiang** [comment]
https://github.com/yangchaojiang/yjPlay/blob/master/READMELAYUOT.md  这是就是好么

**Comment by yangchaojiang** [comment]
demo 下载 你是网络问题，github仓库 不是我决定  用git下载

**Comment by mutoujun** [comment]
> demo 下载 你是网络问题，github仓库 不是我决定 用git下载



> https://github.com/yangchaojiang/yjPlay/blob/master/READMELAYUOT.md 这是就是好么

这个文档不太清晰，就比如调节音量按钮怎么加就没有

**Comment by mutoujun** [comment]
> demo 下载 你是网络问题，github仓库 不是我决定 用git下载

我用git下载也是失败，下载速度只有10几k，跟网络没关系吧，网络差也不至于这么慢吧，然后下到一半就是下载失败

**Comment by yangchaojiang** [comment]
服务器gitbug 不是我的， 不行开梯子。 按钮自己写呀 。
![image](https://user-images.githubusercontent.com/13806413/84882061-4883df00-b0c1-11ea-923a-9d011aea6b74.png)

**Comment by yangchaojiang** [comment]
·```
   //为你布局显示内容自定义内容
              videoBrightnessPro.setMax(mMax);
              videoBrightnessImg.setImageResource(chuangyuan.ycj.videolibrary.R.drawable.ic_brightness_6_white_48px);
              videoBrightnessPro.setProgress(currIndex);
``
在回调中，给你按钮赋值就行了

**Comment by mutoujun** [comment]
> ·```
> //为你布局显示内容自定义内容
> videoBrightnessPro.setMax(mMax);
> videoBrightnessImg.setImageResource(chuangyuan.ycj.videolibrary.R.drawable.ic_brightness_6_white_48px);
> videoBrightnessPro.setProgress(currIndex);
> ``
> 在回调中，给你按钮赋值就行了

我知道按钮自己写，但是就是说文档里没提到怎么做，不知道该怎么做

**Comment by mutoujun** [comment]
> 服务器gitbug 不是我的， 不行开梯子。 按钮自己写呀 。
> ![image](https://user-images.githubusercontent.com/13806413/84882061-4883df00-b0c1-11ea-923a-9d011aea6b74.png)

可以通过邮件把demo发给我一下吗，谢谢你了，我是真的下载不下来，我的邮箱：824532767@qq.com，麻烦您了，感激不尽

**Comment by mutoujun** [comment]
> > ·```
> > //为你布局显示内容自定义内容
> > videoBrightnessPro.setMax(mMax);
> > videoBrightnessImg.setImageResource(chuangyuan.ycj.videolibrary.R.drawable.ic_brightness_6_white_48px);
> > videoBrightnessPro.setProgress(currIndex);
> > ``
> > 在回调中，给你按钮赋值就行了
> 
> 我知道按钮自己写，但是就是说文档里没提到怎么做，不知道该怎么做

好的，我看到了，谢谢

**Comment by yangchaojiang** [comment]
会用梯子吗？
