### ISSUE TITLE
请问一下如果要在播放中重新切换新的视频源怎么办？

### ISSUE THREAD

**Issue by dadakkk** [yangchaojiang/yjPlay#3]
实在播放中。需要切换视频源么。 你可以调用setPlayUri方法，重新加载

**Comment by yangchaojiang** [comment]
一般来说，在播放中切换视频源么？。你可以重新setPlayUri 方法可以重新加载、

**Comment by tjm800** [comment]
如果要在播放中重新切换新的视频源,视频画面不更新，只有声音，画面还停留在上一个视频的画面，只有点一次全屏再缩小回来，才可以更新画面。怎么处理？

**Comment by yangchaojiang** [comment]
你可以选择分辨率的逻辑处理
