### ISSUE TITLE
关于多广告视频的问题

### ISSUE THREAD

**Issue by Greathfs** [yangchaojiang/yjPlay#30]
我觉得exoPlayerManager.setPlayUri(0,url1,url2)这个方法的第二个参数是否可改成List 这样就可以支持多个广告视频了

**Comment by yangchaojiang** [comment]
需要控制。捏可以实现回调自己处理

**Comment by yangchaojiang** [comment]
默认是一个。捏可以实现回调监听 然后自己处理

**Comment by yangchaojiang** [comment]
demo 有实例

**Comment by yangchaojiang** [comment]
exoPlayerManager.setOnWindowListener(new VideoWindowListener() {}
