### ISSUE TITLE
不支持Androidx

### ISSUE THREAD

**Issue by creativityingenuity** [yangchaojiang/yjPlay#300]
编译版本29不通过，不兼容x

**Comment by yangchaojiang** [comment]
错误谢谢， ，便于i不通过问题很多，。 我这边可以编译。错误日志

**Comment by creativityingenuity** [comment]
![图片](https://user-images.githubusercontent.com/12170093/90866770-f44df180-e3c6-11ea-9d3e-8e422d1463ae.png)


使用**implementation 'com.ycjiang:VideoPlayModule-Lite:2.3.60'**

**Comment by yangchaojiang** [comment]
好的 ，。已经升级到2.3.61版本，，谢谢反馈
