### ISSUE TITLE
本地视频无法播放

### ISSUE THREAD

**Issue by gxs-gc** [yangchaojiang/yjPlay#302]
错误截图
![图片](https://user-images.githubusercontent.com/12170093/91375467-5c7c5780-e84d-11ea-8f06-b791cb942eab.png)

代码
 val dataSource = DataSpec(RawResourceDataSource.buildRawResourceUri( R.raw.nan ))
        val raw = RawResourceDataSource(this)
        raw.open(dataSource)
        exoPlayerManager = VideoPlayerManager.Builder(this,VideoPlayerManager.TYPE_PLAY_GESTURE, R.id.exo_play)
            .setLoopingMediaSource( Integer.MAX_VALUE,raw.uri)
            .setVerticalFullScreen(true)
            .create()
            .startPlayer()

最新61版本

**Comment by yangchaojiang** [comment]
需要本地链接使用这个数据源。，默认只读取网络链接
······
        return  new   DefaultDataSourceFactory(context, context.getPackageName());
·····
![image](https://user-images.githubusercontent.com/13806413/91409047-6b77ff80-e877-11ea-9a24-7c7f2582c9d0.png)
