### ISSUE TITLE
列表模式播放空指针 java.lang.NullPointerException

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#31]
ava.lang.RuntimeException:Unable to pause activity  : java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.Player.setPlayWhenReady(boolean)' on a null object reference

Caused by:
--
5 java.lang.NullPointerException:Attempt to invoke interface method 'void com.google.android.exoplayer2.Player.setPlayWhenReady(boolean)' on a null object reference
6 com.google.android.exoplayer2.ui.PlaybackControlView$1.dispatchSetPlayWhenReady(PlaybackControlView.java:237)
7 com.google.android.exoplayer2.ui.PlaybackControlView.showNo(PlaybackControlView.java:1073)
8 chuangyuan.ycj.videolibrary.widget.VideoPlayerView$ComponentListener.reset(VideoPlayerView.java:948)
9 chuangyuan.ycj.videolibrary.video.ManualPlayer.reset(ManualPlayer.java:166)
10 chuangyuan.ycj.videolibrary.video.ManualPlayer.onListPause(ManualPlayer.java:139)
11 chuangyuan.ycj.videolibrary.video.VideoPlayerManager.onPause(VideoPlayerManager.java:62)

**Comment by yangchaojiang** [comment]
谢谢您反馈。会在下个版本修复

**Comment by yangchaojiang** [comment]
d这个周末内，上线新版本的

**Comment by yangchaojiang** [comment]
1.9.8 已修复
