### ISSUE TITLE
设置多线路播放，播放器没有选择线路的按钮

### ISSUE THREAD

**Issue by atLearn** [yangchaojiang/yjPlay#34]
设置多线路播放，播放器没有选择线路的按钮

**Comment by yangchaojiang** [comment]
有的 请看使用说明，需要自己手动开启
//开启多线路设置，默认关闭
 exoPlayerManager.setShowVideoSwitch(true);

**Comment by atLearn** [comment]
已经按照说明设置了 但是播放视频还是没有线路的按钮

**Comment by yangchaojiang** [comment]
只有横屏才会显示的，demo已经有实例代码
