### ISSUE TITLE
不能同时设置广告视频和多线路视频播放吗

### ISSUE THREAD

**Issue by atLearn** [yangchaojiang/yjPlay#35]
先设置广告视频，然后设置多线路视频，广告视频会被后面的覆盖，请问有办法同时设置吗。还是说只能等广告视频播放完了，在去设置多线路视频切换过来，这样就不能无缝切换了。

**Comment by yangchaojiang** [comment]
目前还不支持。可以考虑

**Comment by yangchaojiang** [comment]
你需求很急么？

**Comment by atLearn** [comment]
嗯，比较急，能不能考虑下。我现在看源码还不是看得很懂

**Comment by atLearn** [comment]
你好 有没有考虑增加同时设置广告视频和多线路视频播放的功能

**Comment by yangchaojiang** [comment]
在调试哦

**Comment by yangchaojiang** [comment]
目前效果，还是有点差。

**Comment by atLearn** [comment]
麻烦你了 效果差是怎样的，你原来的版本不是支持切换的吗，只是设置多线路，之前设置的地址会被覆盖，不知道我这样理解对不。

**Comment by yangchaojiang** [comment]
处于mediasurce 对象不一样哦， 无法动态移除mediasurce，支持 移除和添加，有点问题。

**Comment by yangchaojiang** [comment]
兄弟，好消息， @atLearn :bowtie:

**Comment by yangchaojiang** [comment]
已经支持

**Comment by atLearn** [comment]
万分感谢，大神你啥时候更新上去

**Comment by atLearn** [comment]
好的 是dev这个分支么 感觉版本很久之前的

**Comment by yangchaojiang** [comment]
分支还没有的上传

**Comment by atLearn** [comment]
好的

**Comment by yangchaojiang** [comment]
我已经上传 就是主分支

**Comment by yangchaojiang** [comment]
怎么样，目前多分辨广告视频只能在第一个。

**Comment by atLearn** [comment]
你说是广告视频多分辨率 还是广告视频和多分辨视频（正片）的无缝连接

**Comment by yangchaojiang** [comment]
广告视频和多分辨视频（正片）的无缝连接0

**Comment by atLearn** [comment]
大神，非常感谢你！

**Comment by yangchaojiang** [comment]
版本1.9.81 完善 @atLearn
