### ISSUE TITLE
视频播放 点击弹出控制界面时 视频播放变卡了

### ISSUE THREAD

**Issue by Greathfs** [yangchaojiang/yjPlay#36]
现在是我在播放视频时 控制界面右侧需要有剧集列表 用的RecyclerView实现的,但是弹出控制界面后,明显感觉视频播放变卡了

**Comment by yangchaojiang** [comment]
？？/ 亲截图看一下，你是怎么操作的

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/33751957-7dcd26dc-dc19-11e7-85c5-24b102280db8.png)
d大概界面就是这样的 点击后弹出控制界面 我们放的是电视剧 右侧是剧集列表

**Comment by yangchaojiang** [comment]
这个操作，我还没试过。。。 @Greathfs 😂 😂 😂

**Comment by Greathfs** [comment]
这个问题已解决,是下面显示播放时间和总时间那个TextView的问题

**Comment by yangchaojiang** [comment]
好👍
