### ISSUE TITLE
[Support] How to add fastforward and rewind button to control media?

### ISSUE THREAD

**Issue by mdtuyen** [yangchaojiang/yjPlay#38]
Hi,
I need implement fastforward and rewind button to mediaplayer.

Please help me.

**Comment by yangchaojiang** [comment]
Hello, you can copy the layout style in simple_exo_playback_control_view.xml to your custom layout,
Add to
````
    <ImageButton android:id="@id/exo_ffwd"
      style="@style/ExoMediaButton.FastForward"/>
and
    <ImageButton android:id="@id/exo_rew"
      style="@style/ExoMediaButton.Rewind"/>
````
Control. Note: The location of the layout control can be set freely, but please do not delete the existing layout control.
  Then play the view to achieve fast forward and rewind increments.

![image](https://user-images.githubusercontent.com/13806413/33751076-309bd6ca-dc13-11e7-9280-c85930b1f20f.png)
Fast forward and rewind functions.。

**Comment by yangchaojiang** [comment]
I will be in the next version, with fast forward and rewind instance layout, easy reference
Thanks for your support

**Comment by mdtuyen** [comment]
Thanks for your support. 

I have another question. 
I want to increate speed video (1x, 2x, ....) with your library, how do i implement it.

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/33753232-3df40b72-dc21-11e7-8915-5c3c1cbe4b88.png)

**Comment by mdtuyen** [comment]
Thanks you so much, 

I want to add feature is scale screen. 
This library can do it now ?

**Comment by yangchaojiang** [comment]
Can you elaborate? A little do not understand？ Thanks

**Comment by mdtuyen** [comment]
Yes, 
I want implement it for TV the player will suport scale and select resolution.

**Comment by yangchaojiang** [comment]
support    note： In landscape mode, the Select Resolution button is displayed
```
//Open the resolver switch button, the default off
   exoPlayerManager.setShowVideoSwitch(true); 
           String [] test={"http://120.25.246.21/vrMobile/travelVideo/zhejiang_xuanchuanpian.mp4","http://120.25.246.21/vrMobile/travelVideo/zhejiang_xuanchuanpian.mp4","http://120.25.246.21/vrMobile/travelVideo/zhejiang_xuanchuanpian.mp4"};

           String[] name={"Super", "HD", "SD"};
           exoPlayerManager.setPlaySwitchUri(test,name);
           //Start playing the video
           exoPlayerManager.startPlayer();
```

**Comment by mdtuyen** [comment]
@yangchaojiang
As I know, with hls address I can extract to many resolution

```
private List<String> getResolution(){
        List<String> resolution = new ArrayList<>();
        if (trackSelector != null) {
            MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
            if (mappedTrackInfo != null) {
                TrackGroupArray trackGroups = trackSelector.getCurrentMappedTrackInfo().getTrackGroups(0);
                for (int groupIndex = 0; groupIndex < trackGroups.length; groupIndex++) {
                    TrackGroup group = trackGroups.get(groupIndex);
                    for (int trackIndex = 0; trackIndex < group.length; trackIndex++) {
                        String out = DemoUtil.buildTrackName(group.getFormat(trackIndex));
                        resolution.add(out);
                    }
                }
            }
        }
        return resolution;
    };
```

**Comment by yangchaojiang** [comment]
There is an operation  666

**Comment by yangchaojiang** [comment]
We are api return to provide data format, so I will design

**Comment by mdtuyen** [comment]
Thank you so much!

**Comment by yangchaojiang** [comment]
What is your operation? do not really understand

**Comment by mdtuyen** [comment]
I want to implement double click to fast forward button to increate speed rate to 2x, 4x, ....
and click play speed rate will go to normal.
