### ISSUE TITLE
如何把控制的ui隐藏啊，就是只有视频的播放器，或者说怎么自定义ui

### ISSUE THREAD

**Issue by guojiadui** [yangchaojiang/yjPlay#4]

**Comment by yangchaojiang** [comment]
目前没有开放直接控制ui操作，后期帮可以加。 
![image](https://user-images.githubusercontent.com/13806413/29649393-5db24f54-88c6-11e7-8bc9-7d7ccf49a1eb.png)
红线就是控制ui布局  自定义， 注意控件id不能自己定义.引用定义好id

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/29649575-83488ffc-88c7-11e7-88a6-2bfbdff3b619.png)
创建你的控制ui布局在根布局上使用，隐藏属性 就可以了， 下版本，我会开放代码隐藏。

**Comment by guojiadui** [comment]
支不支持软解码和硬解码的选择

**Comment by yangchaojiang** [comment]
可以支持的。  需要单独引用库，库本身已经常规视频已经做比较好，所以我没有引用
https://google.github.io/ExoPlayer/supported-formats.html  视频格式支持
https://github.com/google/ExoPlayer   google

**Comment by guojiadui** [comment]
如果有一些视频有声音，但卡在了第一个画面，能解决吗

**Comment by yangchaojiang** [comment]
是黑屏 ，还是，用这个播放器吗？？

**Comment by guojiadui** [comment]
还是用这个播放器，http://185.73.239.15:25461/live/1/1/911.ts这个链接只有声音

**Comment by yangchaojiang** [comment]
请插检查文件是否文件有问题，我用专业电脑解码播放器，播放， 也是的卡在第一个画面。

![image](https://user-images.githubusercontent.com/13806413/29699854-6f4ab676-8992-11e7-9653-a95e8f122ddc.png)

**Comment by guojiadui** [comment]
基于ijplay的播放器可以播放

**Comment by guojiadui** [comment]
基于vlc的也可以播放

**Comment by yangchaojiang** [comment]
好的，问题我记录一下

**Comment by yangchaojiang** [comment]
问题解决, 选择渲染模式surface_type   texture_view类型换一下 ，就可以了。
图片没法上传

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/29707126-c4ea9d98-89b6-11e7-8c9d-b2ed6eb1622c.png)
 
您好 ，可以控件渲染模式     app:surface_type="texture_view"  换成 texture_view 问题没有了
@guojiadui

**Comment by guojiadui** [comment]
有一些视频是播放不出声音的，能有什么办法解决

**Comment by yangchaojiang** [comment]
不好意思，昨天忙， 请问那些什么视频， 能看一下么

**Comment by guojiadui** [comment]
就是上次我给你的链接，可以播，没声音的

**Comment by yangchaojiang** [comment]
有声音哦。

**Comment by guojiadui** [comment]
http://185.73.239.15:25461/live/1/1/924.ts 这个没有，对于这种国外链接，表示心好累

**Comment by guojiadui** [comment]
我看了几个基于exo的都没有声音

**Comment by guojiadui** [comment]
用android系统的自带的MediaPlayer就有声音，可以是硬解码，不稳定

**Comment by yangchaojiang** [comment]
兄弟可以吗， 国外的哦

**Comment by guojiadui** [comment]
啥意思

**Comment by yangchaojiang** [comment]
http://185.73.239.15:25461/live/1/1/924.ts 好像已经关闭了

**Comment by yangchaojiang** [comment]
你们直播是都是国外的服务器么

**Comment by guojiadui** [comment]
是国外的，好像是对ip进行限制了，只有我这里的ip才可以访问，坑爹

**Comment by yangchaojiang** [comment]
。。。。比较坑哦。。苦笑
