### ISSUE TITLE
如下描述（友盟错误反馈）

### ISSUE THREAD

**Issue by chinahbpyj** [yangchaojiang/yjPlay#40]
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.u.h()' on a null object reference
	at chuangyuan.ycj.videolibrary.e.b$a.onScroll(GestureVideoPlayer.java)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:622)
	at chuangyuan.ycj.videolibrary.e.b.onTouch(GestureVideoPlayer.java)

**Comment by yangchaojiang** [comment]
你使用版本多少？。

**Comment by chinahbpyj** [comment]
我是直接导入的工程，依赖：compile 'com.ycjiang:VideoUi:1.0.8'

**Comment by yangchaojiang** [comment]
你引用是我Ui 部分哦，
![image](https://user-images.githubusercontent.com/13806413/33813842-56f2506a-de61-11e7-9938-69536d1ef2bb.png)

**Comment by chinahbpyj** [comment]
对，我在这个基础上面做了一点修改

**Comment by yangchaojiang** [comment]
你修改了。，那你维护自己维护。
1.9.8版本GestureVideoPlayer  代码控制 我已经400行 左右代码。

**Comment by yangchaojiang** [comment]
我可以参考 我现在版本代码。进行相应

**Comment by chinahbpyj** [comment]
好的，之前是有这个问题吗，但是在我手机上面没有出现过

**Comment by yangchaojiang** [comment]
没有
