### ISSUE TITLE
你的解码怎么做的

### ISSUE THREAD

**Issue by guojiadui** [yangchaojiang/yjPlay#41]
是用了软解码，还是先硬解码失败后在用软解码的，如何选择软硬解码

**Comment by yangchaojiang** [comment]
我用 默认解码方式。eoxplayer  默认拓展 采用java 反射方式， 是自己的话。下载源码修改我红线内。添加你的
![image](https://user-images.githubusercontent.com/13806413/33919295-de880a32-dff2-11e7-8fa2-7f0d076cfda5.png)
