### ISSUE TITLE
w无法播放优酷m3u8地址

### ISSUE THREAD

**Issue by Greathfs** [yangchaojiang/yjPlay#42]
测试地址作者可以去优酷网址上抓下地址,机型换成ipad即可获取视频的m3u8地址,作者可以测试下

ps:
```
@Override
    public MediaSource initMediaSource(Uri uri) {
        int streamType = Util.inferContentType(uri);
        switch (streamType) {
            case C.TYPE_SS:
                return new SsMediaSource(uri, new DefaultDataSourceFactory(context, null,
                        getDataSource()),
                        new DefaultSsChunkSource.Factory(getDataSource()),
                        mainHandler, sourceEventListener);
            case C.TYPE_DASH:
                return new DashMediaSource(uri, new DefaultDataSourceFactory(context, null, getDataSource()),
                        new DefaultDashChunkSource.Factory(getDataSource()), mainHandler, sourceEventListener);
            case C.TYPE_HLS:
                return new HlsMediaSource(uri, getDataSource(), 5, mainHandler, sourceEventListener);
            case C.TYPE_OTHER:
                return new ExtractorMediaSource(uri, getDataSource(), new DefaultExtractorsFactory(), mainHandler, null,uri.getPath());
            default:
                throw new IllegalStateException("Unsupported type: " + streamType);
        }
```
我断点看了下,没有走Hls那个case,走的是的Other,所以播放不了,不知道作者这个问题作者怎么解决呢

**Comment by yangchaojiang** [comment]
请查看你链接是否符合标准链接     判断方式是处理符合标准的。一般m3u8 都有.m3u8后缀名的

**Comment by Greathfs** [comment]
优酷的是这样的:http://pl-ali.youku.com/playlist/m3u8?vid=XMzIwOTg2NDEwNA%3D%3D&type=hd2&ups_client_netip=27599c2a&ups_ts=1513131749&utid=5Hy3Eusu8XsCASdZnCpz%2BNem&ccode=0502&psid=87fe99b3b982d820b2a178c773bb6ec7&duration=2724&expire=18000&ups_key=8eb784ef038b6bc07e073fbabe26d2ba

**Comment by Greathfs** [comment]
作者可以借鉴下这个库:
https://github.com/brianwernick/ExoMedia
这个库是可以播放优酷m3u8的

**Comment by yangchaojiang** [comment]
都是也可以的 exoplayer 判断链接 链接结尾处@ ，我只知道默认标着判断判断，我也是提供 自定义的方式，你可以自己实例化HlsMediaSource().  调用该类setMediaSource()  播放器使用你的

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/33920042-d2247128-dff6-11e7-8b4e-4ee00598a9cb.png)
 
下个版本 我会优化链接方法判断，不采用exoplayer提供链接类型。毕竟我们国内，视频链接都有验证信息什么

**Comment by yangchaojiang** [comment]
谢谢你的建议

**Comment by yangchaojiang** [comment]
版本1.9.81 完善 @Greathfs 谢谢支持
