### ISSUE TITLE
你的MediaSource 为空 当前视频类型,或者实现类型2

### ISSUE THREAD

**Issue by chinahbpyj** [yangchaojiang/yjPlay#43]
<img width="744" alt="_20171213124140" src="https://user-images.githubusercontent.com/10917933/33922072-21da698c-e003-11e7-8c49-288f7ef61288.png">
请问这个是怎么回事

**Comment by yangchaojiang** [comment]
如果你视频源 你是ss hsl dsh 类型中  请依赖完整版。

**Comment by yangchaojiang** [comment]
如果你视频源 你是 smoothstreaming, dash,hls 类型中 请依赖完整版。

**Comment by yangchaojiang** [comment]
如果你视频源 是 smoothstreaming, dash,hls 类型中 请依赖完整版
