### ISSUE TITLE
Media still load after fast forward or back forward ?

### ISSUE THREAD

**Issue by mdtuyen** [yangchaojiang/yjPlay#44]
Example:
My video loaded to 5 minutes, I back forward to 4 minutes, it still reload.

**Comment by yangchaojiang** [comment]
Cache memory data buffer before and after the 5 points data. At this time 4 minutes of data is no longer in the cache, has been removed, so need to reload.

**Comment by mdtuyen** [comment]
I want to cached all video have been loaded and I if I have no close player I can go to any point but don't need reload.

What I have to do ?

**Comment by yangchaojiang** [comment]
You reference to the demo code on the cache instance.

**Comment by mdtuyen** [comment]
Hi @yangchaojiang 
I think it not relation to cache,
If video loaded previous (I can see on secondary processbar, when I change seekbar in secondary processbar loaded video shouldn't reload.
