### ISSUE TITLE
一个严重问题

### ISSUE THREAD

**Issue by iammasir** [yangchaojiang/yjPlay#46]
低配手机在切换全屏和取消全屏的时候，首先会卡顿，声音正常播放画面定格不动。我最近也在改造exo。也遇到了同样的问题

**Comment by yangchaojiang** [comment]
是的，低配手机会有情况。我目前也没有好的办法解决。

**Comment by yangchaojiang** [comment]
你出现手机时？

**Comment by iammasir** [comment]
华为che1 cl20 安卓4.4系统

**Comment by yangchaojiang** [comment]
我查了资料，发现时exoplayer 本身bug. 基于exoplayer 在设设备 5.1以下的版本。基本会有画面卡顿情况，我打算官网反馈。

**Comment by yangchaojiang** [comment]
已修复2.2.11版本
