### ISSUE TITLE
播放视频过程中会出现画面闪动的问题

### ISSUE THREAD

**Issue by Greathfs** [yangchaojiang/yjPlay#48]
播放优酷m3u8视频时，画面会闪
Android 4.2版本

**Comment by Greathfs** [comment]
![default](https://user-images.githubusercontent.com/18097997/34656675-6002c290-f458-11e7-8e95-73af117825d2.gif)

就是这样

**Comment by yangchaojiang** [comment]
已修复2.2.11版本
