### ISSUE TITLE
How to increate cache to prevent reload when click rewind or seek to loaded process?

### ISSUE THREAD

**Issue by mdtuyen** [yangchaojiang/yjPlay#49]
Hi,

How to increate cache to prevent reload when click rewind or seek to loaded process?

**Comment by yangchaojiang** [comment]
You can customize the memory buffer byte size  Modify as follows
![image](https://user-images.githubusercontent.com/13806413/34137342-6b71687e-e4a5-11e7-90c5-79d54c962735.png)
![image](https://user-images.githubusercontent.com/13806413/34137363-8e35fb18-e4a5-11e7-8ef9-439e5807d4b4.png)
