### ISSUE TITLE
 debug 可以正常播放，release播放崩溃

### ISSUE THREAD

**Issue by chinahbpyj** [yangchaojiang/yjPlay#51]
用的是你的工程完整版，debug 可以正常播放，release播放崩溃，错误提示：java.lang.IllegalStateException: 你的MediaSource 为空 当前视频类型,或者实现类型2

**Comment by chinahbpyj** [comment]
已解决，加混淆设置
-dontwarn chuangyuan.ycj.**
-keep class chuangyuan.ycj.** { *;}

**Comment by yangchaojiang** [comment]
混淆声明，我会加上，谢谢支持。
