### ISSUE TITLE
ima 这个 module 的代码没有上传

### ISSUE THREAD

**Issue by feicien** [yangchaojiang/yjPlay#52]
直接下载最新代码，无法编译

**Comment by yangchaojiang** [comment]
不好意思了。漏掉了。马上上传

**Comment by yangchaojiang** [comment]
ok

**Comment by feicien** [comment]
还有一个问题，VideoUI module 中的一个 style 的 item 中有空格
    <style name="ExoMediaTimeBar">
        <item name=" android:layout_width">0dp</item>
        <item name=" android:layout_height">wrap_content</item>
        <item name=" android:layout_gravity">center_vertical</item>
        <item name=" android:layout_marginRight">10dp</item>
        <item name=" android:layout_weight">1</item>
        <item name="bar_height">2dp</item>
        <item name="buffered_color">@android:color/white</item>
        <item name="played_color">#FF7000</item>
        <item name="unplayed_color">#a5ffffff</item>
    </style>

如果 buildToolsVersion 是 25.0.3 的话，会编译失败

**Comment by yangchaojiang** [comment]
空格没有影响吧，你clean project试一下

**Comment by DouDan** [comment]
同第二个问题，有空格，编译失败，clean过了

**Comment by yangchaojiang** [comment]
我提交一下。好了
