### ISSUE TITLE
最近遇到一个小问题,希望作者帮忙解决下

### ISSUE THREAD

**Issue by Greathfs** [yangchaojiang/yjPlay#54]
播放正片之前需要播放几段广告,但是如果播放广告时网速很慢,就会出现重复播放的问题,比如我正在播放第一个广告,播到了10秒钟,开始缓冲,缓冲结束了 又从头开始播放了...

关于播广告网速慢的情况,作者有什么好的建议吗

**Comment by yangchaojiang** [comment]
这个不但从客户端解决，例如手机网速可以，当时还是加载慢，应该解决资源服务器带宽和dns加速，

**Comment by Greathfs** [comment]
我记得exoplayer有个网速慢的监听啊  就是网速很慢的时候 会回调一个方法 作者记得吗?
