### ISSUE TITLE
你好，请问怎么设置滑动屏幕快进时间以秒为进度

### ISSUE THREAD

**Issue by chinahbpyj** [yangchaojiang/yjPlay#55]
怎么设置滑动屏幕快进时间以秒为进度

**Comment by yangchaojiang** [comment]
是显示的，自己自定义布局和实现监听，可以参考demo，自定义布局

**Comment by chinahbpyj** [comment]
app:fastforward_increment="1000"
   app:rewind_increment="1000"
设置的跟实际的不一致

**Comment by yangchaojiang** [comment]
可以按钮设置，不是滑动。另一套控制布局使用

**Comment by chinahbpyj** [comment]
好的。谢谢
