### ISSUE TITLE
请问怎么按全屏就显示地址异常，需在按一次播放

### ISSUE THREAD

**Issue by marscl** [yangchaojiang/yjPlay#57]

**Comment by marscl** [comment]
http://live.aikan.miguvideo.com/wd_r2/cctv/cctv1hd/1200/01.m3u8

**Comment by yangchaojiang** [comment]
4.在功能清单声明 AndroidManifest.xml
在activity节点 加上“android:configChanges="orientation|keyboardHidden|screenSize"”
 如下实例：
        <activity android:name="chuangyuan.ycj.yjplay.MainListActivity"
         android:configChanges="orientation|keyboardHidden|screenSize"
         android:screenOrientation="portrait">
加了么

**Comment by marscl** [comment]
加了

**Comment by yangchaojiang** [comment]
你版本是多少哦，。 demo 没有那问题的哦

**Comment by marscl** [comment]
1.9.83 请问具体参照哪个demo

**Comment by yangchaojiang** [comment]
示例程序哦的，尼吧链接复制到示例程序试一下/

**Comment by marscl** [comment]
MainDetailedActivity.java这个吗

**Comment by yangchaojiang** [comment]
github 仓库里项目
