### ISSUE TITLE
建议增加临时缓存功能

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#58]
从AActivity跳转到BActivity的时候，即使播放同一个Url，也需要重新加载数据，如果允许配置缓存功能，进到第二个Activity的时候播放相同内容是无需重新加载的。

https://stackoverflow.com/questions/28700391/using-cache-in-exoplayer

**Comment by yangchaojiang** [comment]
或许会考虑。最近比较忙

**Comment by yangchaojiang** [comment]
1.9.91 增加。查看 demo 使用案例
