### ISSUE TITLE
切换播放路径 切换不了视频

### ISSUE THREAD

**Issue by Greathfs** [yangchaojiang/yjPlay#60]
```
exoPlayerManager.setPlayUri(videoUrl);
 //开始启动播放视频
exoPlayerManager.startPlayer();
```  

我有50集电视剧,播放完第一集自动切换到下一集,我切换播放路径后不起作用

**Comment by Greathfs** [comment]
ijkplayer 执行releasePlayer()后执行play()方法即可

**Comment by yangchaojiang** [comment]
你可以uris 集合哦。播放器自动切换到下一集  
![image](https://user-images.githubusercontent.com/13806413/34553724-10aaf286-f164-11e7-9e11-442aad1b8808.png)

**Comment by Greathfs** [comment]
我也想到这个了,但是我们的地址每次都必须从我们后台获取,所以一开始我没有uris,只有对应的id集合,播到第几集时我去后台拿地址播放

**Comment by Greathfs** [comment]
我刚才试了试
```
exoPlayerManager.onDestroy();
 exoPlayerManager = null;
exoPlayerManager = new GestureVideoPlayer(this, videoPlayerView, new DataSource(this));
```

这样是可以的,当时总感觉不是那么好

**Comment by yangchaojiang** [comment]
releasePlayer(). 重新setUril 路径，。在调用startPlayer();

**Comment by Greathfs** [comment]
这个办法我试了,没起作用 ,你那边也可以测试下

**Comment by yangchaojiang** [comment]
那个自己new MediaSourceBuilder().  自己处理媒体数据/查看demo  MainCustomMediaActivity

**Comment by Greathfs** [comment]
OK,我试一试

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/34554632-ca36944a-f168-11e7-9c81-985e81e5976f.png)
![image](https://user-images.githubusercontent.com/18097997/34554653-e2076806-f168-11e7-9568-1a93bc85d865.png)
我的是m3u8地址 应该是hls类型 结果直接报错了
![image](https://user-images.githubusercontent.com/18097997/34554677-10d318d8-f169-11e7-95de-4bd0161f62c9.png)

**Comment by yangchaojiang** [comment]
WholeMediaSource 这个是完整版多媒体。

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/34554745-5840f4ec-f169-11e7-807d-671dac2814a4.png)

**Comment by yangchaojiang** [comment]
嗯

**Comment by Greathfs** [comment]
好像是切源成功了,但是为什么不是从头播放呢?

**Comment by yangchaojiang** [comment]
你调重置进度方法哦

**Comment by Greathfs** [comment]
还是没弄好...大佬给写下吧 麻烦了

**Comment by Greathfs** [comment]
就是切换视频地址这里 , 试了好多个办法都不管用

**Comment by Greathfs** [comment]
我执行那个重置进度条的方法,还是无法重头播放 切换视频源应该是切换成功了,之前一直以为切不过去呢

**Comment by yangchaojiang** [comment]
晚上给你看看啊。 我现在忙着工作的事尼

**Comment by yangchaojiang** [comment]
@Override
            public void onPlayEnd() {
                 //多媒体管理类。释放多媒体资源。 不是控制类。
                wholeMediaSource.release();
                wholeMediaSource.setMediaUri(Uri.parse(getString(R.string.url_hls)));
                exoPlayerManager.startPlayer();
            }

**Comment by yangchaojiang** [comment]
完美解决

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/34592392-8803d902-f1fe-11e7-9aa7-d3260474dc84.png)
我就是这样写的呢 没起作用

**Comment by yangchaojiang** [comment]
你使用1.9.83版本？

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/34592484-5ff84ec4-f1ff-11e7-84c4-d96d0021d833.png)

**Comment by Greathfs** [comment]
我是这么导入的

**Comment by yangchaojiang** [comment]
不一定哦

**Comment by yangchaojiang** [comment]
更新到最新了么？

**Comment by yangchaojiang** [comment]
好了吗？

**Comment by Greathfs** [comment]
我今天再试试,周末家里没有公司设备,测试不了
