### ISSUE TITLE
多次用到黑色背景，建议支持自定义

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#64]
代码中多次用到黑色背景，如果需求中背景不是黑色的，突然跳出黑色就会很唐突。
例如
BaseView中232和264行直接用的android.R.color.black。

**Comment by yangchaojiang** [comment]
...最近比较忙。今天才看到。。。为什么不是黑色？

**Comment by h3clikejava** [comment]
UI设计的是灰色背景啊，如果把视频控件写在UI里，播放Loading的时候就会是黑色的。

**Comment by yangchaojiang** [comment]
欧欧哦。原来这样哦，

**Comment by yangchaojiang** [comment]
现在支持点击播放时，不隐藏封面图哦，的所以不会与黑色的背景了

**Comment by yangchaojiang** [comment]
在的app的res资源文件声明：
```
 <color name="exo_player_background_color">#000000</color>
```
就可以更换背景色
