### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#65]
Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.seekTo(int, long)' on a null object reference
chuangyuan.ycj.videolibrary.video.ExoUserPlayer$PlayComponentListener.replayPlayers(ExoUserPlayer.java:884)
-- 
chuangyuan.ycj.videolibrary.widget.VideoPlayerView$7.onClick(VideoPlayerView.java:346)

**Comment by yangchaojiang** [comment]
请问你如何操作的，新的版本，没有原来，只是新增。

**Comment by h3clikejava** [comment]
错误统计SDK上报的啊，空指针规避一下就好了啊

**Comment by yangchaojiang** [comment]
你的代码行，已经不是新版的。更新到1.9.93
