### ISSUE TITLE
另另外个java.lang.NullPointerException

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#67]
Attempt to invoke virtual method 'long com.google.android.exoplayer2.SimpleExoPlayer.getCurrentPosition()' on a null object reference

chuangyuan.ycj.videolibrary.video.GestureVideoPlayer$PlayerGestureListener.onScroll(GestureVideoPlayer.java:345)
android.view.GestureDetector.onTouchEvent(GestureDetector.java:619)
chuangyuan.ycj.videolibrary.video.GestureVideoPlayer$1.onTouch(GestureVideoPlayer.java:289)
android.view.View.dispatchTouchEvent(View.java:10019)

**Comment by yangchaojiang** [comment]
请问你如何操作的，新的版本，没有原来，只是新增。

**Comment by h3clikejava** [comment]
错误统计SDK上报的啊，空指针规避一下就好了啊
