### ISSUE TITLE
ExoPlayer新版的 java.lang.NullPointerException

### ISSUE THREAD

**Issue by h3clikejava** [yangchaojiang/yjPlay#68]
Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource$Listener.onSourceInfoRefreshed(com.google.android.exoplayer2.source.MediaSource, com.google.android.exoplayer2.Timeline, java.lang.Object)' on a null object reference

com.google.android.exoplayer2.source.ExtractorMediaSource.notifySourceInfoRefreshed(ExtractorMediaSource.java:380)
com.google.android.exoplayer2.source.ExtractorMediaSource.onSourceInfoRefreshed(ExtractorMediaSource.java:372)
com.google.android.exoplayer2.source.ExtractorMediaPeriod.maybeFinishPrepare(ExtractorMediaPeriod.java:555)
com.google.android.exoplayer2.source.ExtractorMediaPeriod.access$000(ExtractorMediaPeriod.java:51)
com.google.android.exoplayer2.source.ExtractorMediaPeriod$1.run(ExtractorMediaPeriod.java:153)
android.os.Handler.handleCallback(Handler.java:751)

**Comment by yangchaojiang** [comment]
请问你如何操作的，新的版本，没有原来方法，只是新增。

**Comment by h3clikejava** [comment]
错误统计SDK上报的啊，空指针规避一下就好了啊

**Comment by yangchaojiang** [comment]
你的版1.9.93吗？已经判断了的
