### ISSUE TITLE
怎么播放 RTMP 流

### ISSUE THREAD

**Issue by dev-fancyluo** [yangchaojiang/yjPlay#7]
exoPlayerManager = new ManualPlayer(this, R.id.exo_play_context_id, new DataSource());
exoPlayerManager.setPlayUri("rtmp://192.168.1.201:1935/live/StreamLK");

public class DataSource implements DataSourceListener {
    @Override
    public com.google.android.exoplayer2.upstream.DataSource.Factory getDataSourceFactory() {
        return new RtmpDataSourceFactory();
    }
}

这样行不通。。

**Comment by dev-fancyluo** [comment]
问题我解决了，想请教一个问题，exo好像默认的使用tcp连接，您知道怎么使用udp来进行连接吗？

**Comment by yangchaojiang** [comment]
好的，你需要用到udp方式么

**Comment by yangchaojiang** [comment]
基本采用是tcp链接， udp方式还没具体的研究。

**Comment by yangchaojiang** [comment]
exoplayer 文档也没有udp说明 苦笑
