### ISSUE TITLE
错误页面，重新开始播放页面这样的页面点击两次才能触发点击事件

### ISSUE THREAD

**Issue by chinahbpyj** [yangchaojiang/yjPlay#70]
第一次点击没有反应，第二次点击才有反应

**Comment by yangchaojiang** [comment]
不好意思，最近太忙了了， 可能不能及时回复，
版本时1.9.93的吗？？？？。  demo都是一次。无需两次

**Comment by chinahbpyj** [comment]
你好，demo也是点击两次才能触发点击事件。

**Comment by yangchaojiang** [comment]
oooooo

**Comment by yangchaojiang** [comment]
好的，今晚我好好看一下

**Comment by yangchaojiang** [comment]
我确定一下。1.9.93版本，没有情况出现两次，需要一次。
检查使用版本哈。 或者把你能操作截图是最好的。
