### ISSUE TITLE
run的时候报了这个错

### ISSUE THREAD

**Issue by 3126004008** [yangchaojiang/yjPlay#71]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException:
 java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

**Comment by yangchaojiang** [comment]
编辑报错。 请检查你的 clean project  或者 rebuild project    不是框架本身。

**Comment by 3126004008** [comment]
@yangchaojiang 说错了，rebuild project的时候没问题，但一run起来，就会报这个错！

**Comment by MacauNext** [comment]
問題應該出現在那個IMA, 我也同樣錯誤,用不了

**Comment by yangchaojiang** [comment]
？？？？

**Comment by MacauNext** [comment]
把exoplayer library 下载到本地会出错
java.lang.RuntimeException: Unable to start activity ComponentInfo{chuangyuan.xiangjiang.yjplay/chuangyuan.ycj.yjplay.media.MainCustomMediaActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class chuangyuan.ycj.videolibrary.widget.VideoPlayerView

**Comment by MacauNext** [comment]
在app buidle裡面加上minSdkVersion 改成21, 加上multiDexEnabled true, 就可以成功, 但会有一半的手机运行不了。

**Comment by 3126004008** [comment]
@MacauNext 我将gradle版本提升到4.1，将android studio的版本提升到3.0，然后它run成功了！

**Comment by yangchaojiang** [comment]
项目现在是在3.0编译的。:joy::joy::joy:

**Comment by 3126004008** [comment]
@yangchaojiang ok！之前一直用的是2.3没升级，刚好趁这次用，就升级了，哈哈^_^

**Comment by yangchaojiang** [comment]
谢谢支持，记得问题close了
