### ISSUE TITLE
多线路不能用会出错

### ISSUE THREAD

**Issue by MacauNext** [yangchaojiang/yjPlay#73]
多线路不能用会出错

//开启多线路设置，默认关闭
      exoPlayerManager.setShowVideoSwitch(true);
      //支持List列表
      String [] test={"http://120.25.246.21/vrMobile/travelVideo/zhejiang_xuanchuanpian.mp4",
      "http://120.25.246.21/vrMobile/travelVideo/zhejiang_xuanchuanpian.mp4",
       http://120.25.246.21/vrMobile/travelVideo/zhejiang_xuanchuanpian.mp4"};
       String[] name={"超清","高清","标清"};
       exoPlayerManager.setPlaySwitchUri(test,name);

**Comment by MacauNext** [comment]
还有就是影片播完了, 会自己跳到那一个的中央2台的视频, 如何決解? 
 debug: 
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 5470210
W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010

**Comment by yangchaojiang** [comment]
？？？？

**Comment by yangchaojiang** [comment]
其他的之uri 注释了哦

**Comment by MacauNext** [comment]
没有, 这是你说明里的, 不过已经depreciated,, 你源码里面的多了个parameter,也用不了。

**Comment by yangchaojiang** [comment]
exoPlayerManager.setPlaySwitchUri(0,test,name);
加个索引  可以参看demo.

**Comment by MacauNext** [comment]
Demo, MainDetailedActivity.java 裡面的
//----------
 test = new String[]{getString(R.string.uri_test_9), getString(R.string.uri_test_7), getString(R.string.uri_test_8)};
        String[] name = {"超清", "高清", "标清"};
        //开启线路设置
         exoPlayerManager.setShowVideoSwitch(true);
        // exoPlayerManager.setPlaySwitchUri(0,test,name);
      exoPlayerManager.setPlaySwitchUri(0, 0, getString(R.string.uri_test_11), Arrays.asList(test), Arrays.asList(name));
//--------------
有4条连结参数, 预设是哪一条, 可以播, 到换不了。

**Comment by yangchaojiang** [comment]
exoPlayerManager.setPlaySwitchUri(0, 0, getString(R.string.uri_test_11), Arrays.asList(test), 
这个是同时支持多线路和广告视频的，
