### ISSUE TITLE
滑动快进的时候 视屏太快了

### ISSUE THREAD

**Issue by JuanMaoForLuo** [yangchaojiang/yjPlay#76]
滑动快进的时候 视屏太快了 正常的是以秒走的 但是我轻轻滑动一下直接几分钟的视频过去了 ，布局文件设置了fastforward_increment和rewind_increment也无效

**Comment by yangchaojiang** [comment]
？？？？ 慢慢划， 这个两个点击按钮fastforward_increment和rewind_increment也 方式不是手势。
你自己控制滑动进度[查看](https://github.com/yangchaojiang/yjPlay/blob/master/READMELAYUOT.md#%E4%BA%8C%E6%89%8B%E5%8A%BF%E5%B8%83%E5%B1%80%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80%E5%B8%83%E5%B1%80%E4%B8%8D%E9%9C%80%E8%A6%81%E6%8C%87%E5%AE%9A%E6%8E%A7%E4%BB%B6id)

**Comment by JuanMaoForLuo** [comment]
emmm...我的意思是这样的呢 国人的习惯都是想快进的时候直接很快速的向屏幕右侧快速 ‘’点划‘’ 一下 然后视频往前快进那么5-10秒左右 但感觉作者你的这个播放器的 点划快进增量 似乎太过于多了点 直接往前快进了好几分钟 这个如果我想设置或者修改的话 请问可以通过怎样的办法呢？

**Comment by yangchaojiang** [comment]
上一条消息 查看 链接 就是让自己控制，

**Comment by JuanMaoForLuo** [comment]
好的 我看看 感谢楼主的回复 n.n

**Comment by yangchaojiang** [comment]
好的
 滑动我是腾讯视频， 当前进度和 滑动距离和加上当前视频总时长，做一个换算。得到宽快进和快退 进度

**Comment by yangchaojiang** [comment]
不好意思，开放的是view显示，没有开放最后控制设置进度回。

**Comment by JuanMaoForLuo** [comment]
哈哈 是啊 我就觉得这个不太好 看看博主你能否改进一下 我也好尝试集成在项目中 快进快退的增量过大了些 ，感谢博主回复 ，已点赞star

**Comment by yangchaojiang** [comment]
2.1.0 版本 已经开放，你实现手势进度接口就有。

**Comment by yangchaojiang** [comment]
谢谢支持哈

**Comment by JuanMaoForLuo** [comment]
好的博主 感谢回复

**Comment by JuanMaoForLuo** [comment]
博主 似乎有些bug呢 这个endGestureProgress的回调为什么调节亮度和音量的时候都会回调呢？ 点击一下屏幕的时候也会回调 这样的话 我设置position的时候重新startplay（）就一直回到原点

**Comment by JuanMaoForLuo** [comment]
这个应该是横向滑动时候 进行监听回调的吧 而且要保证视频有快进快退增量产生的时候进行 我在看下你的源码

**Comment by JuanMaoForLuo** [comment]
应该是OnTouchListener的逻辑有些许问题 应该在MotionEvent.ACTION_UP的时候判断是否横向滑动产生的吧

**Comment by yangchaojiang** [comment]
if 判断出问题了 :joy: :joy: :joy: :joy:

**Comment by yangchaojiang** [comment]
应该放在    if (newPosition >= 0) {}里

**Comment by yangchaojiang** [comment]
我用统一处理的，没有根据手势判断的

**Comment by yangchaojiang** [comment]
2.1.3 试一下。加了判断

**Comment by JuanMaoForLuo** [comment]
你好博主 昨天的问题大部分修复了 但是我发现的还有一个问题是 滑动完毕后 就是快进了之后 点击一下屏幕 显示用户操作界面 然后这个endGestureProgress回调也会走 导致又回到了原点 比如我从0分钟 快进到了5分钟 然后视频播放到了5:10秒的时候 点击一下屏幕显示出用户操作页面 并没有滑动 视频又回到了5分钟那里开始了

**Comment by yangchaojiang** [comment]
endGestureProgress  参数用完后， 重新付值为-1。试一下

**Comment by JuanMaoForLuo** [comment]
不行呢 快进完之后 调节亮度 还有调节音量 也会回调endGestureProgress() 小问题挺多的`` joy joy joy joy

**Comment by yangchaojiang** [comment]
重新为-1 就不会。

**Comment by JuanMaoForLuo** [comment]
emmm...用起来麻烦了 其实我想反映的问题简单只是 快进快退增量过多的问题 呃...博主你只需要在“ 当前进度和 滑动距离和加上当前视频总时长，做一个换算”这里 修改一下换算规则 就可以了 不过没事了 就这样吧 感谢博主的回复n.n

**Comment by JuanMaoForLuo** [comment]
long newPosition = (int) (position + deltaX * duration / screenWidthPixels);这里

**Comment by JuanMaoForLuo** [comment]
快退变成了快进

**Comment by yangchaojiang** [comment]
自己处理的，就不要找我。看看自己哪里没有处理正确。
