### ISSUE TITLE
在tv上，本来就是横屏的，如何全屏，如下面的ui

### ISSUE THREAD

**Issue by guojiadui** [yangchaojiang/yjPlay#8]
![image](https://user-images.githubusercontent.com/13541599/30320831-77097b7e-97e6-11e7-8ca7-36e6ebf876e8.png)

**Comment by yangchaojiang** [comment]
您好 可以AndroidManifest 清单上应activity节点上添加 
  android:screenOrientation="landscape"，你的ui 就是横屏状态

**Comment by guojiadui** [comment]
不是这个，我已经设置横屏了，现在是在横屏情况下无法全屏

**Comment by yangchaojiang** [comment]
项目代码实现么。全屏的功能么？看看你代码

**Comment by yangchaojiang** [comment]
检查代码逻辑是否存在问题，检查一下。

**Comment by guojiadui** [comment]
我在你的项目VideoPlayerView加了这个，在acitvity外面调用就蹦了
![image](https://user-images.githubusercontent.com/13541599/30321859-20b8557a-97ea-11e7-93a4-c457f6bbb3b7.png)

**Comment by yangchaojiang** [comment]
朋友，是tv 就不能用常规方式处理，手机切换全屏横屏和竖屏有两个状态，tv，你的是只有横屏上惊进行全屏和非全屏切换。逻辑处理是不一样的

**Comment by yangchaojiang** [comment]
你可以加我qq 1007181167
