### ISSUE TITLE
打开网络视频的时候没有LOADING吗？

### ISSUE THREAD

**Issue by tmxd09887** [yangchaojiang/yjPlay#81]
因为打开网络视频比较慢，开始加载的时候，感觉不到已经开始加载，让用户等待的机制，用户会以为错误就放弃等待了。

已经开始播放后，是有LOADING，但美中不足啊!

谢谢

**Comment by yangchaojiang** [comment]
有啊，。。。。。LOADING 有两种模式

**Comment by tmxd09887** [comment]
/**设置加载百分比显示模式**/
   exoPlayerManager.setLoadModel(LoadModelType.PERCENR);

是这个吗？设置了没生效啊，没看到效果。是必须哪个LAYOUT模式下才能用吗？

**Comment by yangchaojiang** [comment]
网速快，才会看不到LOADING 布局的 。

**Comment by yangchaojiang** [comment]
现在exoplayer 2.7.0 版本加载很快的。

**Comment by tmxd09887** [comment]
没有啊，加载很长时间啊，我在YJPLAY的DEMO也没看到加载效果。加了你QQ了，能聊下吗？
