### ISSUE TITLE
你好，setPlaybackParameters（f，f） 没有效果. 打印的log一直都是1.0f

### ISSUE THREAD

**Issue by Limy1992** [yangchaojiang/yjPlay#82]

**Comment by yangchaojiang** [comment]
请问你是用版本？？

**Comment by Limy1992** [comment]
在调播放倍率的时候需要onPause一下，然后在onResume才有作用。刚解决。用的是最新版的2.1.35

**Comment by yangchaojiang** [comment]
2.1.37 版本

**Comment by Limy1992** [comment]
谢谢

**Comment by Limy1992** [comment]
完整版的-2.1.37，直接setPlaybackParameters 还是没有效果 。   视频倍率播放的时候，声音会变。

**Comment by Limy1992** [comment]
你好，完整版的 -2.1.37直接setPlaybackParameters  还是没有效果

**Comment by yangchaojiang** [comment]
wodemo 已经效果，你的代码设置startplayer() 设置哦

**Comment by yangchaojiang** [comment]
没有问题了 把

**Comment by Limy1992** [comment]
没有问题了， 参数2 pitch不用特意设置大于或者小于1.0f,,  否则声音会变。  只设置参数1 speed就好。声音的快慢会跟着同步。 我测得时候是这样的。 8.0手机。

**Comment by yangchaojiang** [comment]
倍数1是正常播放，默认是1
小于1，大于1，声音跟着的。不然画面和声音不同步
