### ISSUE TITLE
找不到v7包中的ActionBarActivity 

### ISSUE THREAD

**Issue by chengh2016** [yangchaojiang/yjPlay#84]
导入项目中报错，原谅我技术太菜，一头雾水，求解决 TT
Error:(19, 30) 错误: 找不到符号
符号:   类 ActionBarActivity
位置: 程序包 android.support.v7.app

**Comment by yangchaojiang** [comment]
???? 这个不是我的系统v7b包  ，你是不是移除我的类库引用v7包

**Comment by chengh2016** [comment]
不是，是我依赖你的库之后，我项目中原先用的ActionBarActivity 就找不到了

**Comment by yangchaojiang** [comment]
我应用v7版本是26.1.0  系统api 估计移除 ActionBarActivity  现在都用AppCompatActivity 这个类。

**Comment by chengh2016** [comment]
嗯，谢谢，以去掉ActionBarActivity ，但是现在右下角的全屏和退出全屏按钮替换不了，还有左上角的返回按钮如何去除，谢谢

**Comment by yangchaojiang** [comment]
麻烦看文档好吗？[看说用说明](https://github.com/yangchaojiang/yjPlay)
