### ISSUE TITLE
你好，想问下，如何获取视频第一帧显示到封面图那里？

### ISSUE THREAD

**Issue by Zhangxd77** [yangchaojiang/yjPlay#86]
你好，我是在网上找了段代码，关于获取第一帧。这个方法挺耗时的，我是起了个线程，但是也很耗时，不知道您有什么好的意见吗？下面是我的方法
`    //获取视频缩略图
    private Bitmap createVideoThumbnail(String url) {
        Bitmap bitmap = null;
        MediaMetadataRetriever retriever = new MediaMetadataRetriever();
        try {
            retriever.setDataSource(url, new Hashtable<String, String>());
            bitmap = retriever.getFrameAtTime(0, MediaMetadataRetriever.OPTION_NEXT_SYNC);
        } catch (IllegalArgumentException ex) {
            Log.d(TAG, "获取视频缩略图失败");
        } finally {
            try {
                retriever.release();
            } catch (RuntimeException ex) {
                Log.d(TAG, "释放MediaMetadataRetriever资源失败");
            }
        }
        return bitmap;
    }`

**Comment by yangchaojiang** [comment]
用gilde 哦

**Comment by yangchaojiang** [comment]
这个方法并不耗时 网络视频相对比较慢， 想要视频媒体信息才能 才能获取视频第一帧哦

**Comment by Zhangxd77** [comment]
你好，我没搞明白这个地方怎么用glide?是在我那个方法获取的bitmap使用吗？

**Comment by Zhangxd77** [comment]
还有这个 视频媒体信息 怎么获取？？麻烦你了，

**Comment by yangchaojiang** [comment]
更加在图片一样哈。 只是图片链接换成视频链接

**Comment by Zhangxd77** [comment]
Glide.with(this).load(url).into(videoPlayer); 您说的是这个意思吗？videoPlayer就是VideoPlayerView。但是into只能放ImageView，不能放咱们这个类型啊，您能不能给来段demo

**Comment by yangchaojiang** [comment]
。。。。。。你刚学Androjd 么？ init 放Image View 控件 哦，提供获取显示封面图的ImageView 方法

**Comment by Zhangxd77** [comment]
videoPlayerView.setPreviewImage(bimtap); 我是要用这个方法，不是要放在imageview里，我想显示在播放视频封面图。你是不是理解错了？

**Comment by yangchaojiang** [comment]
内部方法也是Image View 我提供两种方式哦， 一个设置数据。提供视频封面图控件。。看demo 示例么

**Comment by yangchaojiang** [comment]
内部方法也是Image View 我提供两种方式哦， 一个设置数据。提供视频封面图控件。。看demo 示例么

**Comment by yangchaojiang** [comment]
解决尼了吧。记得star 一下支持。谢谢
