### ISSUE TITLE
如何暂停播放？

### ISSUE THREAD

**Issue by 793383996** [yangchaojiang/yjPlay#88]
onPause之后无法手动点击继续播放，如何暂停和停止播放？

**Comment by yangchaojiang** [comment]
onPause()周期方法发。 请不要手动调用。
  /***
     * 设置播放或暂停
     * @param value true 播放  false  暂停
     */
    public void setStartOrPause(boolean value) {
        if (player != null) {
            player.setPlayWhenReady(value);
        }
    }

**Comment by 793383996** [comment]
感谢哥哥，哥哥最帅

**Comment by yangchaojiang** [comment]
star 一下，谢谢支持啦:bowtie::bowtie:
