### ISSUE TITLE
播放过程中把网络断了，再把网络连上，点击播放器重试，不能重新链接

### ISSUE THREAD

**Issue by Zhangxd77** [yangchaojiang/yjPlay#92]
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

这个是错误原因

**Comment by Zhangxd77** [comment]
连上了，断了WiFi又再连上了，点报这个错误

**Comment by yangchaojiang** [comment]
请问你自定义布局了么i

**Comment by Zhangxd77** [comment]
没自定义布局。WiFi也已经再次连接了
下面这个是我布局引用部分（图片发不上来，总是失败我就复制代码了）：
`      <chuangyuan.ycj.videolibrary.widget.VideoPlayerView
            android:id="@+id/videoPlayer"
            android:layout_width="match_parent"
            android:layout_height="@dimen/y425"
            android:background="@android:color/transparent"
            app:controller_layout_id="@layout/simple_exo_playback_control_view"
            app:fastforward_increment="1000"
            app:player_hint_layout_id="@layout/custom_play_btn_hint"
            app:player_layout_id="@layout/simple_exo_view"
            app:player_list="true"
            app:player_load_layout_id="@layout/custom_exo_play_load"
            app:player_replay_layout_id="@layout/custom_play_replay"
            app:resize_mode="fit"
            app:rewind_increment="0"
            app:show_timeout="3000"
            app:surface_type="texture_view"
            app:use_controller="true" />`

**Comment by Zhangxd77** [comment]
报错信息：
除了上面之前发的，还有 
onPlayerStateChanged::网络状态差，请检查网络。。。

**Comment by Zhangxd77** [comment]
麻烦看到这个问题的话，能给回复一下，谢谢
