### ISSUE TITLE
视频全屏后，会有一条绿色线怎么可以去掉

### ISSUE THREAD

**Issue by Zhangxd77** [yangchaojiang/yjPlay#95]
问题现象：视频全屏后的绿色的线 怎么可以去掉？怀疑是不是视频尺寸小就暴露出来了
![111](https://user-images.githubusercontent.com/20806535/38015608-d70a83bc-329e-11e8-8036-ae46d1163221.png)

**Comment by yangchaojiang** [comment]
请问你使用版本多少。方不方便视频链接给一下。我测试

**Comment by Zhangxd77** [comment]
版本是2.1.1.
不好意思，我这个视频是接口获取的，有加密然后还有时效。。
我刚刚发现，如果视频播放完，点重播以后绿色线就会没有了。如果需要我可以写个demo,发给你个apk.

**Comment by Zhangxd77** [comment]
然后麻烦你帮忙看下issue 92,那个也是我提问的，那个应该属于个bug.能否看下怎么解决，谢谢

**Comment by yangchaojiang** [comment]
更新到版本2.1.41。查看demo 都是没有问题的

**Comment by Zhangxd77** [comment]
不好意思我看错了。。是2.1.41这俩问题都是有的啊我这边
断开网再重连上WiFi后，点击重播还是播不了
再就是线也存在

**Comment by Zhangxd77** [comment]
方便加一下您qq吗

**Comment by wjygg** [comment]
靠谱么 这个播放器 想播直播

**Comment by Zhangxd77** [comment]
我是播放视频，不是直播，不太清楚

**Comment by yangchaojiang** [comment]
@wjygg  直播的没问题哈。直播的压力，主要是推流上和服务器， 不是在播放端。

**Comment by yangchaojiang** [comment]
已修复2.2.11版本
