### ISSUE TITLE
播放控制界面，不能停留

### ISSUE THREAD

**Issue by tmxd09887** [yangchaojiang/yjPlay#96]
问题现象：播放的时候，控制界面，比如按钮快进暂停这些，没法停住，点了屏幕就返回播放了，下载了最新的2.1.41也一样

错误日志：
chuangyuan.ycj.videolibrary.factory.BufferingLoadControl: targetBufferSizeReached:false
chuangyuan.ycj.videolibrary.factory.BufferingLoadControl: playbackSpeed:1.0
不知道算不算错误日志

**Comment by yangchaojiang** [comment]
这个可不是错误日志哦。
