### ISSUE TITLE
加载字幕MediaSource无效

### ISSUE THREAD

**Issue by tmxd09887** [yangchaojiang/yjPlay#97]
问题现象：字幕没显示，附带代码
错误日志：无错误日志

Uri videoUri = Uri.parse("http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_5mb.mp4");
Uri subtitleUri = Uri.parse("http://cafe.itban.com/media/Classicaloid-ep24.srt");
mediaSourceBuilder=new MediaSourceBuilder(this,new dataSource(getApplication()));

exoPlayerManager = new ManualPlayer(this,mediaSourceBuilder, videoPlayerView);

//构建视频媒体资源.
MediaSource videoSource = new ExtractorMediaSource(videoUri, new DefaultDataSourceFactory(
				context, "exo"), new DefaultExtractorsFactory(), null, null);

//构建子标题媒体源
Format subtitleFormat = Format.createTextSampleFormat(
null, // 跟踪的标识符。可能是null。
MimeTypes.APPLICATION_SUBRIP, // mime类型。必须正确设置
0, // 跑道的选择标志。
null); // 字幕语言。可能是null。

MediaSource subtitleSource = new SingleSampleMediaSource(subtitleUri, new DefaultDataSourceFactory(context, "exo"), subtitleFormat, C.TIME_UNSET);
// 播放带有副标题的视频
MergingMediaSource mergedSource = new MergingMediaSource(videoSource, subtitleSource);

//设置
mediaSourceBuilder.setMediaSource(mergedSource);
exoPlayerManager.startPlayer();

MP4文件可播放，SRT也可下载。文件是别的github文件里找到的。

**Comment by yangchaojiang** [comment]
我看看

**Comment by yangchaojiang** [comment]
这个日志[.srt encoding problem](https://github.com/google/ExoPlayer/issues/1419

**Comment by tmxd09887** [comment]
换了字幕和视频文件，还是无效

Uri videoUri = Uri.parse("http://video.udacity-data.com.s3.amazonaws.com/topher/2017/April/58f50a3e_01-media-intro-hs-a/01-media-intro-hs-a_480p_1000kbps.mp4");
Uri subtitleUri = Uri.parse("http://video.udacity-data.com.s3.amazonaws.com/topher/2017/April/58f502be_08-l-add-simple-exoplayer-view/subtitles/lang_en_vs1.srt");

不过谢谢你的帮助。字幕方案，等有时间我在研究。
