### ISSUE TITLE
多线路切换失败，代码如下。点击线路切换，并没有切换视频

### ISSUE THREAD

**Issue by laibinzhi** [yangchaojiang/yjPlay#99]
问题现象：xxxxx
错误日志：xxxxxx

 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        videoPlayerView = findViewById(R.id.exo_play_context_id);
        mediaSourceBuilder = new MediaSourceBuilder(this, new DataSource(getApplication()));
        exoPlayerManager = new ManualPlayer(this, mediaSourceBuilder, videoPlayerView);
        //设置视频标题
        exoPlayerManager.setTitle("视频标题");

        test = new String[]{getString(R.string.uri_test_7), getString(R.string.uri_test_9), getString(R.string.uri_test_8)};
        String[] name = {"超清", "高清", "标清"};
        //开启线路设置
        exoPlayerManager.setShowVideoSwitch(true);
        exoPlayerManager.setPlaySwitchUri(0,test,name);

        Glide.with(this)
                .load(getString(R.string.uri_test_image))
                .fitCenter()
                .placeholder(R.mipmap.test)
                .into(videoPlayerView.getPreviewImage());
    }

**Comment by yangchaojiang** [comment]
是不好意思，久等了，最近有点忙，今天才看到。已经找问题了，我会尽快修复的，

**Comment by yangchaojiang** [comment]
版本2.1.51 已修改。 谢谢支持。
